### ISSUE TITLE
Cannot set "--registry_address"

### ISSUE THREAD

**Issue by averrin** [micro/micro#10]
root@f6f37458c0a8:/go# micro list services --registry "consul" --registry_address "consul:8500"
Incorrect Usage.

NAME:
   micro list services - List services in registry

USAGE:
   micro list services [arguments...]

OR ignore it:

root@f6f37458c0a8:/go# micro --registry "consul" --registry_address "consul:8500" list services
Get http://127.0.0.1:8500/v1/catalog/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused

even from env

root@f6f37458c0a8:/go# env | grep MICRO
MICRO_REGISTRY_ADDRESS=consul:8500
MICRO_REGISTRY=consul
root@f6f37458c0a8:/go# micro list services
Get http://127.0.0.1:8500/v1/catalog/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused

but 

server --registry "consul" --registry_address "consul:8500"

works

**Comment by asim** [comment]
Micro is a command line executable that has sub commands whereas the server binary does not. The expectation is that global flags such as registry and registry_address be set after execution of the binary and any further commands. So your second method of use `micro --registry "consul" --registry_address "consul:8500" list services` is correct.

**Comment by averrin** [comment]
so
micro --registry "consul" --registry_address "consul:8500" list services

ignore it=(

**Comment by asim** [comment]
Indeed. Sorry if there's any confusion. I can update the docs to make it more clear.

**Comment by averrin** [comment]
But how i can force new registry_address ?

root@f6f37458c0a8:/go# micro --registry "consul" --registry_address "consul:8500" list services
Get http://127.0.0.1:8500/v1/catalog/services: dial tcp 127.0.0.1:8500: getsockopt: connection refused

Why micro still trying 127.0.0.1?

**Comment by asim** [comment]
Ah yea I see what you're saying. It's a bug. I'm looking at it now. Give me a few minutes.

**Comment by asim** [comment]
Ok this should be fixed. Please try again and let me know.

**Comment by averrin** [comment]
yeah, now works. thanks!

**Comment by asim** [comment]
No worries. Thanks for trying out micro!
