### ISSUE TITLE
Sidecar

### ISSUE THREAD

**Issue by amedeiros** [micro/micro#102]
This isn't really an issue more of a question. With registering via sidecar is there away to supply sidecar with more information about the service such as the different endpoints. For example I have a service in go-micro using protobuf. In the micro UI it shows its request and response structure etc. Is this only supported by directly registering to the registry in conjunction with protobuf? If that is the case can you kindly point me in the right direction of the code base where this takes place thanks.

**Comment by asim** [comment]
Note Service structure and the Endpoints field. This will be registered with discovery and made available everywhere else https://github.com/micro/go-micro/blob/master/registry/service.go#L3L9

The server looks at registered handlers and extracts the relevant information to be registered with discovery https://github.com/micro/go-micro/blob/master/server/extractor.go#L65L102.

Please direct future questions to the Slack. Thanks.
