### ISSUE TITLE
How to register the nats

### ISSUE THREAD

**Issue by liang68** [micro/micro#104]
In my api and service with plugins (such as : --broker=nats --transport=nats --registry=nats) to run.When I use micro api to access my services access to be illogical, I guess because I service registry to the nats, all messages are forwarded through nats, therefore cannot be accessed.Is that when I don't use any parameters service can normal visit

**Comment by asim** [comment]
Please look at the readme where it tells you how to build the micro toolkit with plugins https://github.com/micro/micro#build-with-plugins. Import the plugin, rebuild the binary with the plugin, use flags to set the plugin.

**Comment by liang68** [comment]
Thank you for your answer, finally want to understand the relationship between all of components

**Comment by zhongliangong** [comment]
Thank you. I found this thread helpful (although closed).
