### ISSUE TITLE
Possibility to use as API Gateway to graphql or REST services

### ISSUE THREAD

**Issue by operezfuentes** [micro/micro#105]
Hi, 
I'm trying to understand it is possible to use micro as framework to implement an API Gateway to microservices implementing REST and/or grapql interfaces

As API Gateway will expose a graphql graph and will request to our microservices using it's interfaces that currently are implemented in REST and/or Graphql and in near future in grpc

Thanks
Oscar

**Comment by asim** [comment]
Please read the API documentation to see what's currently supported https://micro.mu/docs/api.html#handlers. Alternatively join the [Slack](http://slack.micro.mu/) to discuss alternative solutions with the community.

The API supports http proxying which would allow you to implement REST in your api services. The toolkit also supports plugins if you wanted to add your own /graphql handler https://micro.mu/docs/plugins-toolkit.html. There's currently no graphql support.
