### ISSUE TITLE
HipChat Idle?

### ISSUE THREAD

**Issue by pawmart** [micro/micro#106]
Hey there,

Any ideas how we can keep @micro user not going idle? This requires restart of the docker micro image to re-register the bot to make it 'active' again.

idle bot does not respond to any requests.

**Comment by asim** [comment]
Simple fix is to enable keepalive in the hipchat client https://godoc.org/github.com/micro/hipchat#Client.KeepAlive

I'll do that and then close this.

**Comment by asim** [comment]
https://github.com/micro/go-bot/commit/742bd0742bc7169b8fec30bc09e977ff12609d7e

Update to pull the change
