### ISSUE TITLE
go get github.com/micro/micro/v2  can not get the codes

### ISSUE THREAD

**Issue by gitksqc** [micro/micro#1063]
go get github.com/micro/micro/v2

package github.com/micro/micro/v2: cannot find package "github.com/micro/micro/v2" in any of:
	/usr/local/go/src/github.com/micro/micro/v2 (from $GOROOT)
	/home/ss/tools/golang/ws/src/github.com/micro/micro/v2 (from $GOPATH)

**Comment by asim** [comment]
export GO111MODULE=on
