### ISSUE TITLE
Can a client send protobufs to the API

### ISSUE THREAD

**Issue by alexbilbie** [micro/micro#108]
Can a client only send JSON body to a proxied API or can it send a conforming protocol buffer too?

Basically one of my API endpoints is expecting potentially quite a lot of data to be sent by an iOS app in one payload. In JSON form the payload is huge, a protocol buffer serialization payload is significantly smaller.

**Comment by asim** [comment]
TLDR: You can send protobuf

The default handler expects an api request and response type you can find here https://micro.mu/docs/api.html#handlers. With that handler it does not interpret the body. The "rpc" handler will accept json or protobuf and expects you to set content-type. The "proxy" handler is just a proxy so you can again send whatever you want.
