### ISSUE TITLE
Micro API (RPC) doesn't satisfy JSON-RPC 2.0 RFC 

### ISSUE THREAD

**Issue by DexterHD** [micro/micro#110]
The problem is, that with current implementation of micro api I can't use third-party JSON-RPC clients and libraries, because "Micro API" in RPC mode doesn't satisfy RFCs.
In [RFC](http://www.jsonrpc.org/specification#request_object) request doesn't have field `service` it have only field with name `method`. 
When I use Micro API in RPC mode I need to send this request:
```
{
  "jsonrpc": "2.0",
  "service": "com.example.srv",
  "method": "StructureName.MethodName",
  "request": {"name": "Asim Aslam"},
  "id": 1
}
```
But correct request must be something like this:
```
{
  "jsonrpc": "2.0",
  "method": "com.example.srv.StructureName.MethodName",
  "params": [{"name": "Asim Aslam"}],
  "id": 1
}
```

Also this applicable for JSON-RPC Responses which must have fields like: `json-rpc`,`result`,`error`,`id`

**Comment by asim** [comment]
The micro api says nothing about trying to honour the json rpc spec at all. The rpc handler essentially uses the http path along with namespace to determine service and method. It uses the content-type header to determine how to pass that request along. It's assuming the body will be encoded json or protobuf.

The default go-micro client internally uses the codecs for json-rpc or proto-rpc. The micro api uses the go-micro client when its attempting to forward the request to a backend service. 

If you want a json-rpc 2.0 codec look here https://github.com/micro/go-plugins/tree/master/codec/jsonrpc2. Again note codecs are used by go-micro. This is for internal communication.

The micro api makes use of the default client. You can initialise the codec for the default client by including a separate go file on build.

```
package main

import (
    "github.com/micro/go-micro/client"
    "github.com/micro/go-plugins/codec/jsonrpc2"
)

func init() {
    client.Init(
        client.Codec("application/json", jsonrpc2.NewCodec),
    )
}
```

**Comment by asim** [comment]
If you're looking for the micro api to handle json rpc 2.0 then you need to write your own plugin for that which intercepts the request and handles it.

**Comment by asim** [comment]
It sounds like you're talking about the /rpc endpoint. This is a simple convenience mechanism for calling the service you want. Again this is not meant to honour json-rpc.

**Comment by DexterHD** [comment]
Thanks for feedback. I think I will try to make my own plugin for micro-api which will work using json-rpc 2.0
