### ISSUE TITLE
micro query doesn't show enum value

### ISSUE THREAD

**Issue by tudurom** [micro/micro#112]
This is the protobuf message:

```protobuf
message Account {
	string uuid = 1;

	// service or user
	Type type = 2;

	// username, service name etc
	string client_id = 3;

	// password
	string client_secret = 4;

	// unix timestamps
	int64 created = 6;
	int64 updated = 7;
}
```

`Type` is defined like so:

```protobuf
enum Type {
	USER = 0;
	SERVICE = 1;
}
```

The problem is that when I run `micro query <my method>` the `type` field isn't shown:

![screenshot](https://ptpb.pw/f2Q6.png)

How can I fix this?

**Comment by asim** [comment]
Nil/default values are not returned due to the way in which json marshalling works. It would likely require a specific version of json encoding for this, as available here https://github.com/golang/protobuf/tree/master/jsonpb.

**Comment by tudurom** [comment]
i tried setting a non-default value and it's still not showing

**Comment by asim** [comment]
The value cannot be 0. The default enum value is 0.

**Comment by tudurom** [comment]
i mean, if i set the `type` field in the response as 1 it's still not showing with `micro query`

**Comment by asim** [comment]
That seems highly unlikely. I've tested locally and it works.

**Comment by tudurom** [comment]
Seems like it was a bug in my code. Sorry for wasting you time.
