### ISSUE TITLE
How to route an outside service to micro system

### ISSUE THREAD

**Issue by catalsdevelop** [micro/micro#1128]
Hi,there. I have a running web app api and want to integrate it to go-micro system. I dig a lot from micro/doc, but some documents is outdated and don't know how to do next

 env:
```
micro: v2.9.3
go-micro: v2.9.1
```

outside service: node+express api, serve at `http://localhost:3000`, handle `/` and `/node`

my steps:

`run node service`
`MICRO_SERVER_NAME=com.foo.api.js MICRO_PROXY_ENDPOINT=http://localhost:3000  micro proxy`
`micro api --namespace=com.foo --handler=proxy`

problem:

`micro call --output raw com.foo.api.js /js` and `micro call --output raw com.foo.api.js /js/node` all cause same error 
```
error calling com.foo.api.js./js: {"id":"go.micro.client","code":500,"detail":"malformed method name: \"/js\"","status":"Internal Server Error"}
```

but `micro call --output raw com.foo.api.js /js/xxx` (xxx=anything) can be routed to my node service `/` handler

visit api from http `http://localhost:8080/js` cause
```
2020-07-29 12:17:35.045224 I | http: proxy error: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00"
::1 - - [29/Jul/2020:12:17:35 +1200] "GET /js HTTP/1.1" 502 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"
```

How to fix this , cheers.

**Comment by asim** [comment]
Set namespace to com.foo.api

**Comment by Ioridy** [comment]
@catalsdevelop Did you fixed the problem?
I just got the same problem.
Can you provide a  demo code to learn how to fix if it is convenient for you
