### ISSUE TITLE
Question: Specifying --selector argument to micro CLI client

### ISSUE THREAD

**Issue by ramukima** [micro/micro#113]
Is it possible to specify --selector option to the micro client ? I am not able to use it like -

micro --selector="intend-to-specify-a-filter-criteria" query endpoint-address api.endpoint

This would be equivalent to specifying selector.WithFilter using go-micro. Always displays usage. Any documentation references ?

**Comment by asim** [comment]
The selector flag only allows you to specify a selector, not filters. There's currently no way to do that via flags and unlikely to be anything for it. Just like adding wrappers to the micro cli you would need to modify the default client to include a wrapper that sets your filter. An example would be something like the dc filter https://github.com/micro/examples/blob/master/client/dc_filter/dc_filter.go

**Comment by ramukima** [comment]
We do use the selector with filter on the client code that uses go-micro client library. However, I was looking to see if that was possible using the micro CLI. 

Possibly something like StringMatchSelectorFilter included in the micro CLI could do this trick ? i.e. Include "few generic" selector filter by default in the micro CLI code ?

**Comment by asim** [comment]
StringMatch what? Select filters are much like wrappers, its bespoke code for a specific purpose. Micro does not have an opinion on these things. Baking it into the toolkit is a non goal.

**Comment by ramukima** [comment]
Understood that it may be a non-goal for micro CLI. My point was - Just like go-micro allows me to wrap a client by adding selector with filters, can the micro CLI allow me to do that by using extra parameters. Few generic implementations can be used like "performing a string match using selector with filters on specified argument to that extra parameter".

If it does not sound like an option, I am glad you closed the issue.

**Comment by asim** [comment]
Again it's a non goal however if you would like to create a PR that demonstrates how this code would work feel free and we can discuss whether it makes sense to include it in the tooling.
