### ISSUE TITLE
Integrate autotls

### ISSUE THREAD

**Issue by prasannavl** [micro/micro#114]
It would be nice if micro api has an option to just do autotls from https://godoc.org/golang.org/x/crypto/acme/autocert taking the certmanager's options on the command line.

**Comment by asim** [comment]
What would this look like? What would the options be?

**Comment by prasannavl** [comment]
How about? 

micro web --acme --accept-tos [--acme-cache "/cache/location"] [-acme-whitelist "www.example.com"]

(accept-tos - only for the formality of it)
(the cache location - so that it can that cache location can them be used along with other `micro ...` commands pointing to the dir from where to read from 
Practically, it only makes sense to do this on front-facing servers, so likely the HTTP, and RPC reverse proxies - hence I chose the `web` command, but may not may not apply to all of micro commands - I'm haven't thought that through whether it makes sense.

**Comment by asim** [comment]
Do you have an example of this being implemented elsewhere in this form?

**Comment by asim** [comment]
Looking at this now. We'll see what I come up with.

**Comment by asim** [comment]
https://github.com/micro/micro/pull/120

**Comment by asim** [comment]
The PR has been merged. ACME support is now built in.
