### ISSUE TITLE
Provide an option for --proto_dir to micro new 

### ISSUE THREAD

**Issue by sheetaljoshi** [micro/micro#115]
It would be great to include ways to provide an option for a --proto_dir for micro new along with already provided options i.e. fqdn, namespace, alias and type. This way we could generate the code for the proto files that I have already written vs sample example.proto. I do agree we would anyways provide implementation for the handler and subscriber functions, but this would avoid making errors at least on function declaration.

**Comment by asim** [comment]
How would this work? Can you provide an example? Are we looking to generate template code based on it? How would we do that?

**Comment by asim** [comment]
No response in 1 week. Closing.
