### ISSUE TITLE
How forward URL root Path to the web micro service directly?

### ISSUE THREAD

**Issue by qudenger** [micro/micro#116]
Hi, @asim . I wrote  a web micro service for my home page,  when I visited _mysite.com_/, I don't want to display the dashboard, but rather display the homepage of the web service directly. What should I do?

**Comment by asim** [comment]
You want something like this https://github.com/micro/go-plugins/tree/master/micro/index#route-to-service

**Comment by qudenger** [comment]
Great! That's it what I exactly want.Thanks, asim.
