### ISSUE TITLE
service Example

### ISSUE THREAD

**Issue by petermota** [micro/micro#117]
Hi,

I have started to use your framework (still learning Golang and protobuf) and I have found some issues with your 'service' example. It works but the documentation is not up to date. The problem is in the namespace and the endpoint name, it should be:

```
$ micro list services
consul
greeter
$ micro get service greeter
service  greeter

version latest

Id	Address	Port	Metadata
greeter-0e01f3ee-9bca-11e7-8f65-64b9e8bebc10	192.168.1.100	55293	type=helloworld,transport=http,broker=http,server=rpc,registry=consul

Endpoint: Greeter.Hello
Metadata: stream=false

Request: {
	name string
}

Response: {
	greeting string
}

$ micro query greeter Greeter.Hello '{"Name": "John"}'
{
	"greeting": "Hello John"
}
```

Apart from this Great work!. I like the simplicity (and power) of your framework.

best regards
Pedro

**Comment by asim** [comment]
Which service example do you mean? The one listed in the readme contains the correct name https://github.com/micro/examples/blob/master/greeter/srv/main.go#L23

**Comment by petermota** [comment]
Ooops, we are talking about different services. I was talking about this:

https://github.com/micro/examples/blob/master/service/main.go

It's the 'service' service in examples. It does the same as 'greeter'? Maybe you should delete the first one?

**Comment by asim** [comment]
It would be advisable to follow the readme rather than piecing together the instructions from one thing and the code from somewhere else. Greeter is just used as a simple service to demonstrate a number of different things. It appears in many places under many names.
