### ISSUE TITLE
proto-gen-micro doesn't update the HandlerImpl

### ISSUE THREAD

**Issue by eric-chao** [micro/micro#1178]
Why proto-gen-micro doesn't update the HandlerImpl?

For example:

I add a method ‘Add()’ to 'service Helloworld',  like below:

service Helloworld {
        rpc Add(AddRequest) returns (AddResponse) {}
	rpc Call(Request) returns (Response) {}
	rpc Stream(StreamingRequest) returns (stream StreamingResponse) {}
	rpc PingPong(stream Ping) returns (stream Pong) {}
}

then execute: micro proto

helloworld/handler/helloworld.go doesn't update.

Anything wrong?

**Comment by xzjkya** [comment]
As far as I understand the handler's in Micro are your application's logic. What `protoc` does is create a bunch of boilerplate code that you would have to create anyway. `proto.` files are language agnostic. The command takes what its in there and creates the structures, functions, methods, classes, etc you need to communicate over the wire with `protobuf` for Y different programming languages. While also dealing with some internals. Now all you have to do is call the classes that manages the communication.

**Comment by asim** [comment]
what is `micro proto`? Do make proto.

**Comment by eric-chao** [comment]
> what is `micro proto`? Do make proto.

sorry,  a spelling mistake.

**Comment by eric-chao** [comment]
> what is `micro proto`? Do make proto.

spelling mistake, sorry.
