### ISSUE TITLE
how to get MultipartForm  from Request

### ISSUE THREAD

**Issue by weisd** [micro/micro#119]
I post a file form to micro api, how can I get the File ?

**Comment by weisd** [comment]
@asim

**Comment by asim** [comment]
If you use the default handler in the micro api then you'll receive a copy of the body of the request. You can then use the golang multipart library to parse it https://golang.org/pkg/mime/multipart/. 

If you use the proxy handler then it will essentially reverse proxy the request to you in which case you'd likely be using standard net/http handlers in your api service and be able to parse the request.

**Comment by asim** [comment]
I wrote a simple example for you https://github.com/micro/examples/tree/master/form
