### ISSUE TITLE
Greeter service: RegisterTTL and RegisterInterval settings cause service to be marked as unhealthy

### ISSUE THREAD

**Issue by abjb** [micro/micro#12]
In master/examples/greeter/server/main.go:
micro.RegisterTTL(time.Second*10),
micro.RegisterInterval(time.Second*20),

This causes the service to be marked as unhealty for around 50% of the time. My guess is that the values for TTL and Interval need to be swapped like this:
micro.RegisterTTL(time.Second*20),
micro.RegisterInterval(time.Second*10),

**Comment by asim** [comment]
Good spot. I set it like this for testing purposes but never flipped back. Fixed https://github.com/micro/micro/commit/155da68a81c461187da22649c637b13011df5879
