### ISSUE TITLE
Installation broken for v3

### ISSUE THREAD

**Issue by ctrysbita** [micro/micro#1206]
```bash
> go version
go version go1.14.6 linux/amd64

> go env -w GO111MODULE=on
> go get github.com/micro/micro/v3

go: github.com/micro/micro/v3 upgrade => v3.0.0-alpha
# github.com/coreos/etcd/clientv3/balancer/picker
Programs/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
Programs/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
Programs/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
Programs/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
```
Also tested on windows with same error.

**Comment by canaanpaul** [comment]
change  go mode google.golang.org/grpc v1.27.0 to google.golang.org/grpc v1.26.0

**Comment by ctrysbita** [comment]
@canaanpaul I mean installing micro command line tool. Not Go project.

**Comment by canaanpaul** [comment]
@ctrysbita this issue was caused by  micro does not support grpc 1.27, you can reduce grpc to 1.26, you can run：
 go get github.com/micro/micro/v3 
and then go to gopath/src/github.com/micro and modify the go.mod file, 
execute go get again or go install will work.

**Comment by ctrysbita** [comment]
@canaanpaul Not work when using go mod.

**Comment by asim** [comment]
Please install one of the release binaries, otherwise downgrade grpc to 1.26 using a replace statement. See our go.mod for reference.
