### ISSUE TITLE
when 'handler=proxy' the url path map things.

### ISSUE THREAD

**Issue by Arion-Dsh** [micro/micro#122]
when use proxy, registry a service like 'go.micro.api.foo' and service address is '127.0.0.1:9000' .  

the url map is 
```
"8080/foo" => ":9000/foo" 
":8080/foo/a" =>'':9000/foo/a"
```
the namespace always in the service path.

How I get the ":9000/" or ":9000/ther"? 

registry another service? but the old project have many url like this.

there have a easy way to map url like 
```
":8080/foo" => ":9000"
":8080/foo/a =>":9000/a"
```
?

**Comment by asim** [comment]
- /foo/* always maps to service foo
- /a always maps to service a
- / has no mapping 

If you want to set a service for the index try a plugin like this https://github.com/micro/go-plugins/tree/master/micro/index

If you want to do some sort of prefix stripping use something like this https://github.com/micro/examples/tree/master/plugins/prefix

The api is not meant to handle all scenarios, its dynamic routing. If you want further functionality you must build it as plugins or use some other gateway.

**Comment by Arion-Dsh** [comment]
oh, thanks. I figure it out 

I believe I need use the web for proxy the services.  It's set X-Micro-Web-Base-Path in header to remove prefix.

but I wonder why  api and sidecar haven't.
