### ISSUE TITLE
used v2, But some of the problems appear in version 1.18

### ISSUE THREAD

**Issue by jroam** [micro/micro#1223]
I used v2:

"github.com/micro/go-micro/v2"

`go build `
question is as follows:
`
go: finding module for package github.com/micro/go-micro/server
go: finding module for package github.com/micro/go-micro/client
go: found github.com/micro/go-micro/client in github.com/micro/go-micro v1.18.0
# beahu/services/usersrv/boot
boot/boot.go:28:46: cannot use service.Server() (type "github.com/micro/go-micro/v2/server".Server) as type "github.com/micro/go-micro/server".Server in argument to user.RegisterUserHandler:
	"github.com/micro/go-micro/v2/server".Server does not implement "github.com/micro/go-micro/server".Server (wrong type for Handle method)
		have Handle("github.com/micro/go-micro/v2/server".Handler) error
		want Handle("github.com/micro/go-micro/server".Handler) error

`

Thinks!

**Comment by asim** [comment]
Something in your code is looking for v1. If you are using protoc-gen-micro then upgrade github.com/micro/micro/v2/protoc-gen-micro
