### ISSUE TITLE
how to call go-micro srv by grpc native client

### ISSUE THREAD

**Issue by lezi1022** [micro/micro#125]

**Comment by asim** [comment]
A go-micro service by default uses http for transport and proto-rpc or json-rpc for encoding. To call a go-micro service from a grpc service you must first create a go-micro based grpc service using our plugins. 

The easiest way to do this is to use [go-grpc](https://github.com/micro/go-grpc) which initialises the grpc client and server plugins for you. 

You can also find some grpc examples in the [examples/grpc](https://github.com/micro/examples/tree/master/grpc) repo

**Comment by lezi1022** [comment]
my backend service are build on go-micro framework, and provide gRPC interface( we would't consider providing json http interface) . is it suitable for my mobile app act as  a go-micro gRPC client ?  if it is, l'm afraid of go-micro load balance not suitable for me. and consul will deploy on internet for mobile app service discovery,  it will expose internal services (ip ,port and so on) to internet,  is it safe?

**Comment by asim** [comment]
Mobile apps should not directly interact with go-micro services. Your service discovery should not be directly exposed on the internet. This is what the micro api gateway is for.

**Comment by JitenPalaparthi** [comment]
> Mobile apps should not directly interact with go-micro services. Your service discovery should not be directly exposed on the internet. This is what the micro api gateway is for.

1) I want to consume the service in flutter/android .. so do you suggest to use api-gateway for that ?
