### ISSUE TITLE
RE: `micro new` doesn't work on Windows #61

### ISSUE THREAD

**Issue by dundich** [micro/micro#129]
new.go 
74 LINE: path.Dir and filepath.Dir don't seem to work with Windows paths

	// write the files
	for _, file := range c.Files {
		f := filepath.Join(c.GoDir, file.Path)
		dir := path.Dir(f)  //BUG !!!!!!!!!!!!!!!!!!!!
		dir := filepath.Dir(f) // IS OK

see: https://github.com/micro/micro/pull/130

**Comment by asim** [comment]
PR merged
