### ISSUE TITLE
How to freeze micro version with dependencies?

### ISSUE THREAD

**Issue by PavelPrischepa** [micro/micro#131]
I want to build a docker image with a fixed version of micro and go dependencies. I plan to do it with `dep`:
```
git checkout git@github.com:micro/micro.git
dep ensure
git add Gopkg.toml
git add Gopkg.lock

# Build micro
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w' -i -o micro ./main.go 

# Build docker image
...
```
So, my question is does it the best solution to build consistent _micro_ docker image?

[Stackoverflow issue](https://stackoverflow.com/questions/48520523/how-to-freeze-micro-version-with-dependencies).

**Comment by asim** [comment]
People take a number of different approaches to this. The most common I've seen is the use of glide. I imagine dep is similar in that it locks dependency versions when you actually use it. This approach should be fair straight forward. Join the slack if you want to discuss with other users too.

**Comment by ealves-pt** [comment]
I answered your Stackoverflow issue but we have been using Glide to achieve what you have mentioned. There are a couple of missing features (when I compare with the Javascript world) but it does the job quite well, reliable and fast.

**Comment by PavelPrischepa** [comment]
Thank you guys, I'll check dep vs glide in case of performance and convenience.
