### ISSUE TITLE
Running services ends in error=No entrypoint found

### ISSUE THREAD

**Issue by Schnavid** [micro/micro#1318]
Currently testing the framework. The helloworld example works completely fine.

If i try to start a service, generated by the cli:

```
micro new testservice
cd testservice
make proto
micro run .
micro status
```
The micro stats command outputs 
```testservice latest  testservice.tar.gz        error   n/a     11s ago         owner=micro, group=micro, error=No entrypoint found```

Any suggestions why i am running into a `No entrypoint found` error?

**Comment by asim** [comment]
What platform are you on? What version are you running?

**Comment by crufter** [comment]
The fix should be in latest master micro now.

**Comment by mfahrul** [comment]
> The fix should be in latest master micro now. Pull the code and `go install` as the installer is pinned to a tag.
Thank you @crufter, 
Confirmed its work for new service generated with "micro new" command. my existing project using earlier version is not working. (still "No entrypoint found")

I will try to copy it into latest master's generated service to see if it work.

**Comment by jdxj** [comment]
The same error appeared when I ran `micro run .`. After I deleted the `./.git` directory, the service was running normally, but I don't know why this is happening.

**Comment by torniker** [comment]
I have figured out how to fix this problem but not sure if this is the right solution.

I've made added this snippet of code 
```
if strings.Contains(file, "/.git") {
	return nil
}
```

in service/runtime/server/util.go 
func compress(src string, buf io.Writer) error inside filepath.Walk

If this is right solution, let me know and I can make a pull request.

**Comment by crufter** [comment]
Going to have an other look go at this now, sorry for not cracking this entirely on the first try :P

**Comment by torniker** [comment]
@crufter 

to reproduce run following commands:
```
micro new foo
cd foo
make proto
git init
micro run .
micro status
```

**Comment by crufter** [comment]
Thanks for all the input. I can confirm this still exists in latest master.
Fixing this in #1381 very soon.

**Comment by crufter** [comment]
Update: this part of the codedbase is actually being rewritten by @ben-toogood right now so I put off fixing this as his rewrite will fix.
