### ISSUE TITLE
micro api cann't run

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/micro#1322]
micro  api --handler=api --namespace=com.abc.api
Error querying registry for service api: {"Id":"go.micro.client","Code":500,"Detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused\"","Status":"Internal Server Error"}

micro env 
* local      127.0.0.1:8081
  platform   proxy.m3o.com:443

I try to remove local but fail
use micro env del local 127.0.0.1:8081 can't delete that neither micro env del local

**Comment by asim** [comment]
`micro api` is not a command in v3. Please use `micro service api` if you want to start it independently.
