### ISSUE TITLE
Does api gateway support stream?

### ISSUE THREAD

**Issue by leon-github** [micro/micro#133]
Hi,
When I trace down to API gateway code, I found that eventually it invokes client.Call() to the target micro service. But there is no place to support client/server stream mode, by invoking client.Stream().  Does the API gateway support it?

Thanks
Leon

**Comment by asim** [comment]
The API gateway does not currently support stream. I welcome a discussion on how to include this in the api. Potentially by looking at the service endpoint metadata to see if it supports streaming.

**Comment by alexppxela** [comment]
Hi,
I've submit the PR #132 to allow websocket forwarding.
@asim What do you think?

**Comment by leon-github** [comment]
Hi Asim,
I assume you are saying that on API gateway, by looking at the service endpoint metadata to know if the method to be invoked has client-side/server-side streaming or not? Correct me if I'm wrong.  With this, the external caller doesn't need to pass such information as part of metadata in HTTP headers.

**Comment by asim** [comment]
Yes exactly. So if you run [micro/examples/stream/server](https://github.com/micro/examples/blob/master/stream/server/main.go) then do `micro get service go.micro.srv.stream` you'll see:

```
Endpoint: Streamer.ServerStream
Metadata: stream=true
```

Endpoint metadata specifies whether an endpoint is a stream. So the api should be able to use this to determine whether to stream the connection or not. I haven't looked at all the details but I think this would be the appropriate way.

**Comment by leon-github** [comment]
Hi Asim,
Based on your suggestion, I managed to add server-side streaming. I do have a question regarding the type of streaming to determine. The rpc/api proxy needs to know if this is client-side streaming, or server-side streaming or both sides, so that the code can loop the request or response as per the streaming type. However, looking at go-micro/server/extractor code, the reflect type of all those streaming method are the same. I dumped the endpoint req/resp type as below. As you can see, they are the same, and we can only tell that there is streaming at least in one direction. 

BothSideStream
NumIn 3, reqType Context (context.Context), rspType Streamer (server.Streamer)

ServerStream
NumIn 3, reqType Context (context.Context), rspType Streamer (server.Streamer)

Is there a good way to differentiate them?

**Comment by asim** [comment]
I have not looked at the code in a long time but my current assumption is there's no good way to differentiate without refactoring the code. You then have to realise that this is one server implementation of which there could be many. We have a grpc server implementation in go-plugins as well so anything we do needs to really work across them all or it needs a rethink as to how to approach it.

**Comment by asim** [comment]
@leon-github coming back to this issue. How do you think this should behave from the client side? Is the client using web sockets? If so, when we see this header we can upgrade to a stream and just send/recv what ever is received from the client and server.

**Comment by leon-github** [comment]
Hi Asim,
Yes my eventual solution is 1) using grpc client/server in go-plugins; 2) wrapping the client.Dial with websocket, and go-api do the ssl termination as well as upgrade to websocket server; 3) eventually go-api establish new connection to grpc server back go-api. So the whole flow is this:
grpc-cilent (websocket conn) -------ssl -----> |go-api(websocket server)==tcp==>grpc-server|

**Comment by asim** [comment]
Did you have to write any custom code for this that can be contributed back?

**Comment by leon-github** [comment]
Not very faimilar with github commit process. But here is code snippet in proxy.go which does websocket proxy and forwarding. It shows the main idea. 

`

type proxy struct {
	r  router.Router
	s  *api.Service
	ws bool
	ns string
}

type webSockProxyConn struct {
	conn *websocket.Conn
	buf  []byte
	cn   *net.TCPConn
}

func (pr *webSockProxyConn) Write(p []byte) (n int, err error) {

	err = pr.conn.WriteMessage(websocket.BinaryMessage, p)
	if err != nil {
		return
	}
	// WriteMessage always writes full data
	n = len(p)
	return
}

func (pr *webSockProxyConn) Read(p []byte) (n int, err error) {
	// if no buffer, get some
	if pr.buf == nil {
		msgType, buf, err := pr.conn.ReadMessage()

		if err != nil {
			// Make sure server knows, so will close
			// client side
			pr.cn.CloseWrite()
			return 0, err
		}
		if msgType != websocket.BinaryMessage {
			// Make sure server knows, so will close
			// client side
			pr.cn.CloseWrite()
			buflen := len(buf)
			if len(buf) > 10 {
				buf = buf[0:10]
			}
			return 0, fmt.Errorf("got non-binary message, len(%v): %v\n",
				buflen, buf)
		}
		pr.buf = buf
	}
	n = copy(p, pr.buf)
	if n == len(pr.buf) {
		pr.buf = nil
	} else {
		pr.buf = pr.buf[n:]
	}
	return
}

func (p *proxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	service, err := p.getService(r)
	if err != nil {
		w.WriteHeader(500)
		return
	} 
	if len(service) == 0 {
		w.WriteHeader(404)
		return
	}

	if isWebSocket(r) && p.ws {
		p.serveWebSocket(service, w, r)
		return
	}

	rp, err := url.Parse(service)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	httputil.NewSingleHostReverseProxy(rp).ServeHTTP(w, r)
}

// getService returns the service for this request from the selector
func (p *proxy) getService(r *http.Request) (string, error) {
	var service *api.Service

	if p.r != nil {
		// try get service from router
		s, err := p.r.Route(r)
		if err != nil {
			return "", err
		}
		service = s
	} else if p.s != nil {
		// we were given the service
		service = p.s
	} else {
		// we have no way of routing the request
		return p.ns, errors.New("no route found")
	}

	// create a random selector
	next := selector.Random(service.Services)

	// get the next node
	s, err := next()
	if err != nil {
		return "", nil
	}

	if p.ws == true {
		return fmt.Sprintf("%s:%d", s.Address, s.Port), nil
	} else {
		return fmt.Sprintf("http://%s:%d", s.Address, s.Port), nil
	}
}

// serveWebSocket used to serve a web socket proxied connection
func (p *proxy) serveWebSocket(host string, w http.ResponseWriter, r *http.Request) {
	req := new(http.Request)
	*req = *r

	if len(host) == 0 {
		http.Error(w, "invalid host", 500)
		return
	}

	// connect to the backend host
	addr, err := net.ResolveTCPAddr("tcp", host)
	if err != nil {

		http.Error(w, fmt.Sprintf("err: failed to resolve %s", host),
			http.StatusInternalServerError)
		return
	}
	cn, err := net.DialTCP(addr.Network(), nil, addr)
	if err != nil {

		http.Error(w, fmt.Sprintf("dialTCP failed: %v", err),
			http.StatusInternalServerError)
		return
	}
	defer cn.Close()

	var upgrader = websocket.Upgrader{}
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {

		http.Error(w, http.StatusText(http.StatusInternalServerError),
			http.StatusInternalServerError)
		return
	}
	defer c.Close()

	var sp webSockProxyConn
	sp.conn = c
	sp.cn = cn

	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		// client->server
		defer wg.Done()
		// copy data from websocket to proxied tcp destination
		l, err := io.Copy(cn, &sp)
		deadline := time.Now().Add(10 * time.Second)
		msg := "closed"
		if err == io.EOF || err == io.ErrUnexpectedEOF {
			// send close message to peer
			sp.conn.WriteControl(
				websocket.CloseMessage,
				websocket.FormatCloseMessage(
					websocket.CloseNormalClosure,
					""),
				deadline)
		} else {
			// send close message to peer
			sp.conn.WriteControl(
				websocket.CloseMessage,
				websocket.FormatCloseMessage(
					websocket.CloseAbnormalClosure,
					fmt.Sprintf("%v", err)),
				deadline)

			msg = "timed out"
		}

		return
	}()
	wg.Add(1)
	go func() {
		// server->client
		defer wg.Done()
		// copy data from tcp socket to websocket
		io.Copy(&sp, cn)
		msg := "closed"
		return
	}()
	wg.Wait()
	sp.conn.Close()

}

func isWebSocket(r *http.Request) bool {
	contains := func(key, val string) bool {
		vv := strings.Split(r.Header.Get(key), ",")
		for _, v := range vv {
			if val == strings.ToLower(strings.TrimSpace(v)) {
				return true
			}
		}
		return false
	}

	if contains("Connection", "upgrade") && contains("Upgrade", "websocket") {
		return true
	}

	return false
}

// Proxy is a reverse proxy used by the micro web and api
func Proxy(r router.Router, s *api.Service, ws bool, ns string) http.Handler {
	return &proxy{
		r:  r,
		s:  s,
		ws: ws,
		ns: ns,
	}
}
`

**Comment by pennkao** [comment]
github.com/micro/cli/helpers.go:13:2: use of internal package not allowed

**Comment by asim** [comment]
Only just had the chance to read the above code. Unfortunately I was assuming it was doing some sort of internal rpc streaming but this is just websocket forwarding which we already have. You can specify the websocket handler with `--handler=web`. It will give you the functionality you're looking for.
