### ISSUE TITLE
runs inside docker containers sidecar not connect services

### ISSUE THREAD

**Issue by scholar-ink** [micro/micro#135]
`docker run --name goods udian/goods `
the micro server use etcd
and run the command：
`micro --registry=etcd --broker=nsq --enable_stats sidecar`
trying 
`curl -H 'Content-Type: application/json' -d '{"name": "John2","barcoe":"2222"}' http://127.0.0.1:8081/v1/goods/detail`
get response:
`{"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"}`
The reason is that the docker port is not mapped so that the sidecar link is not up to the server I wrote
 But the port of micro server is randomly generated

**Comment by asim** [comment]
You can set the address for your micro service using `--server_address`.

**Comment by scholar-ink** [comment]
thanks，i have a new issues

`docker run -p 8081:8081 -e  MICRO_REGISTRY=etcd microhq/micro sidecar`
`Registry etcd not found`

How should I solve this problem?

plugin？

In this case, do I want to re-edit this image?

**Comment by asim** [comment]
The default image does not include etcd. You must add this plugin yourself. The readme explains how to add and rebuild a binary https://github.com/micro/micro#plugins

**Comment by scholar-ink** [comment]
Thank you. I've solved the problem. 
 I'd like to ask, however, how to communicate with each other in docker, I try to use --link, but it's still ineffective, for example 

`docker run --link=etcd -p 8081:8081 -e MICRO_REGISTRY=etcd ttouch/micro sidecar`
`Error listing endpoints client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:2379: connect: connection refused`

**Comment by scholar-ink** [comment]
hi~ I want to use mirco in kubernetes, and then use etcd as a Registry, what should I do ？ I wrote this in docker
`micro.Registry(etcd.NewRegistry(registry.Addrs("http://etcd:2379")))`

**Comment by asim** [comment]
This is no longer an issue but usage related. Please join the slack for support. You can run in kubernetes with registry like that just fine. You should be running etcd at the address specified.
