### ISSUE TITLE
Can't run Micro for WSL

### ISSUE THREAD

**Issue by srickopp** [micro/micro#1356]
I have a problem when start 
`micro server`

2020-09-14 08:54:40  file=grpc/grpc.go:728 level=info Registry [mdns] Registering node: server-6c0ffb76-e68b-422c-a165-6ee677a84c7a
2020-09-14 08:54:43  file=grpc/grpc.go:954 level=error Server register error: Failed to join multicast group on all interfaces!

and when i've try to run command micro status or micro login the response is:

{"Id":"go.micro.client","Code":500,"Detail":"Error creating stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused\"","Status":"Internal Server Error"}

anyone has same case before? or already success to run micro at WSL.

**Comment by genewoo** [comment]
Please use WSL2, this mdns issue is a known issue with WSL1

**Comment by ZjKing93** [comment]
> Please use WSL2, this mdns issue is a known issue with WSL1

the problem alse happen in WSL2

**Comment by ZjKing93** [comment]
> I have a problem when start
> `micro server`
> 
> 2020-09-14 08:54:40 file=grpc/grpc.go:728 level=info Registry [mdns] Registering node: server-6c0ffb76-e68b-422c-a165-6ee677a84c7a
> 2020-09-14 08:54:43 file=grpc/grpc.go:954 level=error Server register error: Failed to join multicast group on all interfaces!
> 
> and when i've try to run command micro status or micro login the response is:
> 
> {"Id":"go.micro.client","Code":500,"Detail":"Error creating stream: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused"","Status":"Internal Server Error"}
> 
> anyone has same case before? or already success to run micro at WSL.

Hi,I have the same question， do you reslove?

**Comment by vtolstov** [comment]
don't use mdns registry, multicast not works in wsl, try to install insider build https://docs.microsoft.com/ru-ru/windows/wsl/release-notes#build-16176 from 16176 it supports multicast
