### ISSUE TITLE
Install micro error

### ISSUE THREAD

**Issue by taadis** [micro/micro#1357]
just

```
go version
go version go1.15 windows/amd64
```

and

```
go get github.com/micro/micro/v3@latest
go: github.com/micro/micro/v3 latest => v3.0.0-beta.3
# github.com/coreos/etcd/clientv3/balancer/picker
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
```

**Comment by zhsssy** [comment]
I ran into the same problem.
You can try to replace google.golang.org/grpc => google.golang.org/grpc v1.26.0 to solve it.

**Comment by taadis** [comment]
@zhsssy how to replace grpc version?
I just run `go get github.com/micro/micro/v3@latest` .

**Comment by zhsssy** [comment]
> @zhsssy how to replace grpc version?
> I just run `go get github.com/micro/micro/v3@latest` .

you can use go mod download or go get google.golang.org/grpc@v1.26.0 to solve it.

**Comment by taadis** [comment]
@zhsssy error again? how do it more detail.

```
C:\Users\Administrator>go get google.golang.org/grpc@v1.26.0
go: downloading golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
```
and
```
C:\Users\Administrator>go get github.com/micro/micro/v3@latest
go: github.com/micro/micro/v3 latest => v3.0.0-beta.3
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```

**Comment by zhsssy** [comment]
> @zhsssy error again? how do it more detail.
> 
> ```
> C:\Users\Administrator>go get google.golang.org/grpc@v1.26.0
> go: downloading golang.org/x/net v0.0.0-20190311183353-d8887717615a
> go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
> go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
> ```
> 
> and
> 
> ```
> C:\Users\Administrator>go get github.com/micro/micro/v3@latest
> go: github.com/micro/micro/v3 latest => v3.0.0-beta.3
> # github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
> go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
> # github.com/coreos/etcd/clientv3/balancer/picker
> go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
> go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
> ```

You can create a go.mod file and add`
replace google.golang.org/grpc => google.golang.org/grpc v1.26.0`
`require github.com/micro/micro/v3 v3.0.0-beta.3`   then use go mod download and go get github.com/micro/micro/v3

**Comment by illegaluid** [comment]
> > @zhsssy error again? how do it more detail.
> > ```
> > C:\Users\Administrator>go get google.golang.org/grpc@v1.26.0
> > go: downloading golang.org/x/net v0.0.0-20190311183353-d8887717615a
> > go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
> > go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
> > ```
> > 
> > 
> > and
> > ```
> > C:\Users\Administrator>go get github.com/micro/micro/v3@latest
> > go: github.com/micro/micro/v3 latest => v3.0.0-beta.3
> > # github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
> > go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:114:78: undefined: resolver.BuildOption
> > go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\resolver\endpoint\endpoint.go:182:31: undefined: resolver.ResolveNowOption
> > # github.com/coreos/etcd/clientv3/balancer/picker
> > go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\err.go:37:44: undefined: balancer.PickOptions
> > go\pkg\mod\github.com\coreos\etcd@v3.3.18+incompatible\clientv3\balancer\picker\roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
> > ```
> 
> You can create a go.mod file and add` replace google.golang.org/grpc => google.golang.org/grpc v1.26.0`
> `require github.com/micro/micro/v3 v3.0.0-beta.3` then use go mod download and go get github.com/micro/micro/v3
'replace google.golang.org/grpc => google.golang.org/grpc v1.26.0'. this is exist  
in v3@v3.0.0-beta.3 folder/go.mod

**Comment by illegaluid** [comment]
it seems fixed .
try again

**Comment by asim** [comment]
We have stripped etcd from our dependency list to make this work. Note if you use it as a plugin then the replace line will be needed.
