### ISSUE TITLE
How to change registry when run `micro sidecar`

### ISSUE THREAD

**Issue by CikeyPlanet** [micro/micro#136]
I've tried to run sidecar follow this [doc](https://github.com/micro/examples/tree/master/sidecar#run-discovery)  as `micro sidecar --registry=mdns`.
But the feedback said there's no such `--registry` flag.

How can I change registry when running `micro sidecar`?

**Comment by asim** [comment]
```micro --registry=mdns sidecar```

Please do `micro --help` for usage help
