### ISSUE TITLE
micro run error: "An account is required"

### ISSUE THREAD

**Issue by gogoods** [micro/micro#1362]
![image](https://user-images.githubusercontent.com/3422759/93166200-9061e300-f750-11ea-85f9-c1e0f6a283c3.png)

what's wrong?

**Comment by asim** [comment]
```
# user: admin pass: micro
micro login
```

**Comment by lin1520050767** [comment]
I run 'micro server' in docker container, another container execute go service. Some issue. How can I fixed it.
