### ISSUE TITLE
service at github.com/micro/services@master not found

### ISSUE THREAD

**Issue by gogoods** [micro/micro#1363]
![image](https://user-images.githubusercontent.com/3422759/93167426-31ea3400-f753-11ea-8383-a80dd1864c6e.png)

help！

I pulled github.com/micro/services already, but it still fails.

**Comment by taadis** [comment]
@gogoods 
You can run `micro status` get the status of services,
Or run `micro logs helloworld` get the logs of helloworld service.

**Comment by taadis** [comment]
Oops! the error message `service at github.com/micro/services@master not found` look like network problem. you can try agin.
