### ISSUE TITLE
go.dev link broken

### ISSUE THREAD

**Issue by quentinmit** [micro/micro#1373]
`README.md` has a link to https://pkg.go.dev/github.com/micro/micro/v3?tab=overview but go.dev doesn't actually have any information because it can't parse the `LICENSE` file.

**Comment by crazybber** [comment]
you need to ask pkg.go.dev (https://github.com/golang/go/labels/pkgsite) they did not support `Polyform Shield.`

**Comment by asim** [comment]
Back to Apache 2.0
