### ISSUE TITLE
Run failed  on windows.

### ISSUE THREAD

**Issue by vannnnish** [micro/micro#1383]
System:  Win10  18362.1082

Run micro server is fine.  

Than run micro login got this : Enter username: admin
open C:\Users\50319\.micro\config.json: The process cannot access the file because it is being used by another process.

run micro servies got this: {"Id":"go.micro.client","Code":500,"Detail":"{\"Id\":\"go.micro.client\",\"Code\":500,\"Detail\":\"service registry: route not found\",\"Status\":\"Internal Server Error\"}","Status":"Internal Server Error"}

Run same thing on my macOS is fine.

**Comment by CedrusZhao** [comment]
I also meet this errot

**Comment by CedrusZhao** [comment]
I also meet this error

**Comment by xujiangze** [comment]
use

**Comment by crazybber** [comment]
run  micro server as admin in windows shell.

**Comment by Qalifah** [comment]
I'm also having a similar problem.

**Comment by crazybber** [comment]
check this https://github.com/micro/micro/pull/1558
