### ISSUE TITLE
micro v2: Registry consul not found

### ISSUE THREAD

**Issue by gogoods** [micro/micro#1388]
![image](https://user-images.githubusercontent.com/3422759/94140824-6b7f1580-fe9e-11ea-9405-ca638de5c9ea.png)
![image](https://user-images.githubusercontent.com/3422759/94140860-7df94f00-fe9e-11ea-99a3-d67cdc2e78d9.png)

I started a consul and registered a service to it successfully.

but I cannt use micro status/list/api based on consul:
![image](https://user-images.githubusercontent.com/3422759/94141044-c1ec5400-fe9e-11ea-8dde-6c65a11f8860.png)

with this error: "Registry consul not found"

micro version latest, v2?

**Comment by gogoods** [comment]
maybe the micro I compiled not support consul?

**Comment by gogoods** [comment]
mdns is ok

**Comment by asim** [comment]
v2 does not include consul, please see go-plugins

**Comment by gogoods** [comment]
> v2 does not include consul, please see go-plugins

I can use consul in my go-micro service, but i wanna use micro cli tools (api, call, list, etc.) with consul also, how to do this?

**Comment by asim** [comment]
Include the consul plugin and compile micro

**Comment by gogoods** [comment]
> Include the consul plugin and compile micro

deal, thanks

**Comment by wlstony** [comment]
> > Include the consul plugin and compile micro
> 
> deal, thanks

how did you include consul plugin when compile micro?

**Comment by wlstony** [comment]
1、git clone https://github.com/micro/micro.git
2、cd micro
3、create file consul.go
`package main

import (
    _ "github.com/micro/go-plugins/registry/consul/v2"
)
`
4、go build -o micro main.go consul.go

After do the four steps, I run "micro --registry=consul --registry_address=127.0.0.1:8500 api  --handler=rpc " successfully.
It took me so much time. Afterall it solved
