### ISSUE TITLE
question about running multiple toolkits in docker container via proper setups

### ISSUE THREAD

**Issue by mooncaker816** [micro/micro#139]
Hi, first thanks a lot for your whole great micro project, this is really a nice framework with many flexibilities. But i have a question below,
is it possible to run multiple toolkits like API & Web within startup of the micro container by proper setups of Dockerfile and Docker-compose only? I tried Entrypoint & CMD in many ways and also tried make an entrypoint.sh to kick off the micro command, but only the first command ran successfully. So right now I have to login to container then run the failed one manually, pls let me know in case of any hints and any example will be greater. Thanks again.

**Comment by asim** [comment]
Hi, thanks for using micro. Your question is docker specific so I would suggest looking at the docker documentation or seeking out docker support for this. It's entirely possible to run them in the same container but not a recommended best practice. Each application should be run separately in a container.
