### ISSUE TITLE
micro run helloworld  error message is An account is required

### ISSUE THREAD

**Issue by c2498168786** [micro/micro#1428]
micro new helloworld
cd helloworld/
make proto
make build

**Here's the point**
./helloworld 
2020-10-07 15:11:03  file=cmd/cmd.go:533 level=fatal Error setting up auth: {"Id":"go.micro.client","Code":500,"Detail":"{\"Id\":\"go.micro.client\",\"Code\":500,\"Detail\":\"error getting next auth node: failed getting services: {\\\"Id\\\":\\\"registry.Registry.GetService\\\",\\\"Code\\\":401,\\\"Detail\\\":\\\"An account is required\\\",\\\"Status\\\":\\\"Unauthorized\\\"}\",\"Status\":\"Internal Server Error\"}","Status":"Internal Server Error"}

**Comment by asim** [comment]
Login using the default credentials admin/micro. They are in the readme.

**Comment by crufter** [comment]
I think the problem is also that you are running the binary?
It should be a `micro run .` in the folder etc.

**Comment by DQFSN** [comment]
befor exec **micro run helloworld**，exec **micro login**，username：admin，password：micro

**Comment by DQFSN** [comment]
> befor exec **micro run helloworld**，exec **micro login**，username：admin，password：micro

read this ---> https://github.com/micro/micro/blob/master/README.md

**Comment by c2498168786** [comment]
![Uploading thanks.jpeg…]()

**Comment by aawadall** [comment]
issue still there 
![image](https://user-images.githubusercontent.com/18039552/96142033-9c67ce80-0ecf-11eb-8385-7698df089312.png)

**Comment by crazybber** [comment]
> issue still there
> ![image](https://user-images.githubusercontent.com/18039552/96142033-9c67ce80-0ecf-11eb-8385-7698df089312.png)

it looks a windows situation @asim @crufter

**Comment by benjiro** [comment]
Also hitting the same issue running v3 beta 7 on windows.
`OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042`

Steps to reproduce

1. `micro new test`
2. `cd test`
3.` make proto`
5. `micro login - admin/micro`
6. `micro run .`
![image](https://user-images.githubusercontent.com/2031163/97066151-670d6000-15f6-11eb-827f-31f6394b5f3d.png)

**Comment by Leadrive** [comment]
me too.
