### ISSUE TITLE
how to reset micro user data

### ISSUE THREAD

**Issue by xujiangze** [micro/micro#1474]
in local user admin/micro
I use follow to test auth
```
micro auth create rule  --access=granted --scope='*' --resource="*:*:*" onlyloggedin
micro auth delete rule default
```
now i can't use other  cmd like "micro status"

how to reset micro data?

**Comment by xujiangze** [comment]
prompt information
```
Unauthorized call made to runtime:Runtime.Read
```

**Comment by asim** [comment]
What version are you running?

```
micro --version
```

**Comment by asim** [comment]
If you'd done this locally simply shutdown micro and rm -rf /tmp/micro then start again

**Comment by xujiangze** [comment]
> What version are you running?
> 
> ```
> micro --version
> ```

micro version v3.0.0-beta.6

**Comment by xujiangze** [comment]
> If you'd done this locally simply shutdown micro and rm -rf /tmp/micro then start again

i stop micro, and use ``` micro logout; rm /tmp/micro ``` try to restart micro, login it also show  ```  Unauthorized call made to auth:Auth.Token ```

**Comment by CedrusZhao** [comment]
I stop micro server  ,  rm -rf /tmp/micro,then start agin.
the auth data will be reset.

**Comment by xujiangze** [comment]
> I stop micro server , rm -rf /tmp/micro,then start agin.
> the auth data will be reset.
> my micro version also is v3.0.0-beta.6.

**Comment by xujiangze** [comment]
> I stop micro server , rm -rf /tmp/micro,then start agin.
> the auth data will be reset.
> my micro version also is v3.0.0-beta.6.

thx

**Comment by CedrusZhao** [comment]
I am also learning micro V3.Would you have a wechat to talk about?

**Comment by xujiangze** [comment]
> If you'd done this locally simply shutdown micro and rm -rf /tmp/micro then start again

i try it, and restart my mac, and it work! thx!

**Comment by xujiangze** [comment]
> I am also learning micro V3.Would you have a wechat to talk about?

nanynln12,  I am also learning micro,  study it together :)
