### ISSUE TITLE
micro new don`t support windows. error 

### ISSUE THREAD

**Issue by clearcodecn** [micro/micro#150]
$ micro new github.com/micro/example
2018/04/11 11:36:56 CreateFile /var/run/secrets/kubernetes.io/serviceaccount: The system cannot find the path specified.

**Comment by asim** [comment]
Where are you running this? It's throwing a kubernetes error implying that its expecting to be running in a kubernetes environment. We have nothing that tries to generate this file and nothing that logs "CreateFile"

**Comment by asim** [comment]
No response. Closing.

**Comment by keyeMyria** [comment]
#### I have the same problem now, but I fixed it by  
```

rm -rf $GOPATH/src/github.com/micro $GOPATH/bin/micro
go get github.com/micro/go-micro
 go get github.com/micro/micro

```
