### ISSUE TITLE
Can't get client real address through websocket

### ISSUE THREAD

**Issue by LiPL2017** [micro/micro#151]
Hi all,

How to get real IP by connecting `micro web` through websocket？

I want to test if the client address is legal,but when i called  `Conn.RemoteAddr`, the result is wrong.I used to trace `micro/web/proxy.go   func (p *proxy) ServeHTTP(w http.ResponseWriter, r *http.Request)` , r.RemoteAddr was correct,after `req.Write(conn) `is called ,conn did not have this.

Thanks

**Comment by asim** [comment]
Now explicitly setting X-Forwarded-For header which you can use to get the remote ip
