### ISSUE TITLE
micro v3 config interface Too many changes ，unable to smooth upgrade from micro v2

### ISSUE THREAD

**Issue by crossgo** [micro/micro#1514]
I am very happy with the micro v3 release,but upgrading is too hard for develpoers from micro v2.
In my microv2 project, I use ctripcorp/apollo as my own project configuration  center.
So I Implement the micro v2 config and watcher interface，but i can't find these interface in micro v3
How can I nest my own configuration center in micro v3.

Hopefully, later versions will be smooth, and too many architectural changes will cause developers to lose enthusiasm

I'm sorry for my poor English

Thanks.

**Comment by starfork** [comment]
v3/v2 就是俩东西，平滑升级有点难。

**Comment by wanzirong** [comment]
A CRAZY JOB!!!

**Comment by crazybber** [comment]
this is a break change.
