### ISSUE TITLE
getting-started setup note for modules

### ISSUE THREAD

**Issue by eliben** [micro/micro#1520]
**Describe the bug**

**To Reproduce**
1. Read instructions at https://m3o.org/getting-started
2. Run `go get github.com/micro/micro/v3` outside a module
3. "cannot find package" errors

**Expected behavior**

With recent versions of Go, many folks won't have GOROOT/GOPATH set up at all, and would be all in on modules. `go get` commands for `micro` won't work outside an initialized module.

IMHO it'd be useful to rephrase the instructions of getting-started to work with modules, or to explicitly address this (if using modules do this, otherwise do that).

**Comment by asim** [comment]
What's the expectation solution here? Just to document? Is there a better fix?

**Comment by eliben** [comment]
I played with it a bit using different settings of `GOPATH` and it seems to do with modules. Other `go get`s work locally without GOPATH set (because it defaults to `$HOME/go`), but not the micro v3 paths, possibly due to the version tag.

It does work with `GO111MODULE=on` though, which makes me think that the clever version tagging is involved (v3 is not a real path on GitHub, but a release tag).

I'd recommend you or another team member to try to reproduce it locally and phrase the guide in a way that makes it unambiguous which environment users are expected to execute this in.
