### ISSUE TITLE
getting-started: running helloworld service

### ISSUE THREAD

**Issue by eliben** [micro/micro#1521]
The getting-started guide asks to run the `helloworld` microservice, but doesn't say how to do that. All it says is:

> If we go to github.com/micro/services, we see a bunch of services written by micro authors. One of them is the helloworld. Try our luck, shall we?
> 
> The command to run services is micro run.

It seems like this service can be launched with `micro run github.com/micro/services/helloworld` without cloning the services repo, but this is not clear from getting-started and should be specified explicitly.

**Comment by asim** [comment]
I've amended the guide. If satisfied please close the issue.
