### ISSUE TITLE
github.com/micro/cli/helpers.go:12:2: use of internal package not allowed

### ISSUE THREAD

**Issue by pennkao** [micro/micro#153]
env:  mac   go1.10
import cycle not allowed
package github.com/micro/micro
	imports github.com/micro/micro/cmd
	imports github.com/micro/cli
	imports github.com/micro/cli

centos7.0    go1.9  ok

**Comment by asim** [comment]
Have you run `go get -u github.com/micro/micro`. There are no import cycles. All tests pass fine.

**Comment by asim** [comment]
Not an actual issue. Code builds fine in Travis CI. Closing.
