### ISSUE TITLE
Call API return 500 code

### ISSUE THREAD

**Issue by shihp** [micro/micro#154]
In the example of the homepage, when using the Call API step, there is a problem with 
```
curl -XPOST -H 'Content-Type: application/json' -d '{"name": "John"}' http://localhost: 8080/example/call
```
return:
```
{"id":"go.micro.api","code":500,"detail":"not found","status":"Internal Server Error"}
```

**Comment by shihp** [comment]
I found a way to adjust the api startup command to
```
Micro api --namespace=go.micro.srv --handler=rpc
```
Can access

**Comment by hisea** [comment]
I'm still getting this error @shihp is there anything else you need to do?

**Comment by dncmn** [comment]
@hisea ,Do you remember how you solve this problem???
