### ISSUE TITLE
Micro install with fsnotify package

### ISSUE THREAD

**Issue by chenyangguang** [micro/micro#1540]
Install micro fail in two way . Both failed. 

1. Firstly with go get , failed.

`go get -u -v github.com/micro/micro/v3`

go: downloading github.com/micro/micro/v3 v3.0.0-beta.7
go: github.com/micro/micro/v3 upgrade => v3.0.0-beta.7
go: downloading github.com/urfave/cli v1.22.2
go: downloading github.com/hashicorp/go-version v1.2.1
go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381
go: downloading github.com/gobwas/pool v0.2.1
go: downloading github.com/juju/fslock v0.0.0-20160525022230-4d5c94c67b4b
go: downloading google.golang.org/grpc v1.27.0
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
go: downloading github.com/urfave/cli/v2 v2.2.0
go: downloading github.com/stretchr/testify v1.6.1
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/rhysd/go-github-selfupdate v1.2.2
go: downloading gopkg.in/square/go-jose.v2 v2.4.1
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading go.etcd.io/bbolt v1.3.5
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/google/go-github/v30 v30.1.0
go: downloading github.com/tcnksm/go-gitconfig v0.1.2
go: downloading github.com/xanzy/go-gitlab v0.35.1
go: downloading github.com/ulikunitz/xz v0.5.5
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading google.golang.org/appengine v1.6.1
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/hashicorp/go-retryablehttp v0.6.4
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: github.com/golang/protobuf upgrade => v1.4.3
go: golang.org/x/oauth2 upgrade => v0.0.0-20200902213428-5d25da1a8d43
go: google.golang.org/grpc upgrade => v1.33.1
go: golang.org/x/sys upgrade => v0.0.0-20201026173827-119d4633e4d1
go: github.com/xanzy/go-gitlab upgrade => v0.38.2
go: google.golang.org/genproto upgrade => v0.0.0-20201026171402-d4b8fe4fd877
go: gopkg.in/yaml.v3 upgrade => v3.0.0-20200615113413-eeeca48fe776
go: github.com/miekg/dns upgrade => v1.1.35
go: github.com/evanphx/json-patch/v5 upgrade => v5.1.0
go: github.com/cloudflare/cloudflare-go upgrade => v0.13.4
go: github.com/go-acme/lego/v3 upgrade => v3.9.0
go: golang.org/x/text upgrade => v0.3.3
go: github.com/cenkalti/backoff/v4 upgrade => v4.1.0
go: golang.org/x/crypto upgrade => v0.0.0-20201016220609-9e8e0b390897
go: github.com/google/uuid upgrade => v1.1.2
go: github.com/stretchr/testify upgrade => v1.6.1
go: golang.org/x/net upgrade => v0.0.0-20201026091529-146b70c837a4
go: golang.org/x/time upgrade => v0.0.0-20200630173020-3af7569d3a1e
go: github.com/mattn/go-runewidth upgrade => v0.0.9
go: github.com/olekukonko/tablewriter upgrade => v0.0.4
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: github.com/gobwas/httphead upgrade => v0.0.0-20200921212729-da3d93bc3c58
go: google.golang.org/appengine upgrade => v1.6.7
go: github.com/klauspost/cpuid upgrade => v1.3.1
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/gorilla/handlers upgrade => v1.5.1
go: google.golang.org/protobuf upgrade => v1.25.0
go: github.com/xlab/treeprint upgrade => v1.0.0
go: github.com/ulikunitz/xz upgrade => v0.5.8
go: gopkg.in/square/go-jose.v2 upgrade => v2.5.1
go: github.com/caddyserver/certmagic upgrade => v0.12.0
go: github.com/gorilla/mux upgrade => v1.8.0
go: github.com/hashicorp/go-retryablehttp upgrade => v0.6.7
go: github.com/gobwas/ws upgrade => v1.0.4
go: github.com/cpuguy83/go-md2man/v2 upgrade => v2.0.0
get "gopkg.in/fsnotify.v1": found meta tag get.metaImport{Prefix:"gopkg.in/fsnotify.v1", VCS:"git", RepoRoot:"https://gopkg.in/fsnotify.v1"} at //gopkg.in/fsnotify.v1?go-get=1
go get: upgrading gopkg.in/fsnotify.v1@v1.4.7: gopkg.in/fsnotify.v1@v1.4.9: invalid version: go.mod has non-....v1 module path "github.com/fsnotify/fsnotify" at revision v1.4.9

2. Secondly, With Linux command: 

`wget -q  https://raw.githubusercontent.com/micro/micro/master/scripts/install.sh -O - | /bin/bash`

Getting system information
Your machine is running linux on amd64 CPU architecture
Checking machine system support
Checking HTTP client
Getting the latest micro release
Failed to install micro

System info

Centos. 
Linux localhost 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by crazybber** [comment]
remove  “-u”

**Comment by chenyangguang** [comment]
> remove “-u”

Got it!  I had forgot  add 

> export PATH=$PATH:/$GOPATH/bin

 to my `~/.zshrc` file and `source ~/.zshrc`
