### ISSUE TITLE
getting error when I run the 'micro server' command

### ISSUE THREAD

**Issue by Qalifah** [micro/micro#1542]
![Screenshot (26)](https://user-images.githubusercontent.com/44738020/97278493-256cf700-183a-11eb-84d9-ee1310e7f13f.png)
![Screenshot (27)](https://user-images.githubusercontent.com/44738020/97278500-2736ba80-183a-11eb-8896-7dfd9ccc8173.png)

i tried running the `micro server` command on my pc but it panics. what am i doing wrong?

**Comment by shumintao** [comment]
感觉Micro v3 一堆坑 , 更新到最新一版本 吧

**Comment by Qalifah** [comment]
Okay, I will

**Comment by crazybber** [comment]
windows 上的目前还存在一些问题，

**Comment by Qalifah** [comment]
Any ideas when there will be a v3 stable version ?

**Comment by Qalifah** [comment]
Upgrading to the latest version (v3.0.0) solved this problem for me.
