### ISSUE TITLE
How can I build services with micro v3 on k8s or docker

### ISSUE THREAD

**Issue by AWaterColorPen** [micro/micro#1549]
Is it prossible to build services with micro v3 on k8s or docker?

For my understand, micro v3 should work with m3o or `micro server`. But how can I make it work on k8s or something just like micro v2 `MICRO_REGISTRY` balabala.

**Comment by crazybber** [comment]
of course, its work just like your local way.

**Comment by AWaterColorPen** [comment]
is there any example?

**Comment by ctrysbita** [comment]
micro v3 can't run without its own runtime `micro server`. That's a really BAD design

**Comment by asim** [comment]
> micro v3 can't run without its own runtime `micro server`. That's a really BAD design

Micro is no longer just a framework. If you believe it's a bad design please go use a different piece of software. It's an abstraction for infrastructure and now requires a runtime component for that. This is a vastly simpler longer term experience but may not conform to people's requirements of a standalone framework.

If you want a non approved hack simply specify MICRO_PROFILE=local to any service.

**Comment by asim** [comment]
Helm install is otherwise in the docs.
