### ISSUE TITLE
micro api produces "unsupported content type"

### ISSUE THREAD

**Issue by sysradium** [micro/micro#156]
Tried to use fresh micro api and micro web versions (`micro -client=grpc -server=grpc api` for example) with my go-micro grpc service.
Both of them return:
```
{
    "code": 500,
    "detail": "Unsupported Content-Type: application/json",
    "id": "go.micro.client",
    "status": "Internal Server Error"
}
```
After some investigation I figured out that grpc plugin does not register a "application/json" codec, so I modified https://github.com/micro/micro/blob/master/internal/handler/rpc.go#L105 by setting content type to "application/grpc+json" and it worked.

Am I doing something wrong or that's a bug? Seems to be a recent change.

**Comment by asim** [comment]
The issue has been resolved. There was indeed a problem with no codecs being registered for that content-type due to another change.
