### ISSUE TITLE
Instructions on how to update micro (Docker images) properly without breaking user's credentials or anything else

### ISSUE THREAD

**Issue by lambdaR** [micro/micro#1566]
I've been playing with micro v3.0.0-beta7 lately where i signed up for a new user under `dev` environment.
Today, after the announcement of new release micro v3.0.0 i searched the docs on how to update micro in general    :(

so, I've decided to delete the image and its container(s), then pull a fresh micro image.

I ended up with a **stale** user, i can't login / signup again using the same credentials / email with a `Account not found with this ID` / `Customer with this email address already exists` message resp.

**Comment by crazybber** [comment]
i think "without breaking"  need to be paid much more attension to. as i knew ,v2-to-v3  had caused huge complaint in china developers ,which obviously effected their choice and action.

@asim @ben-toogood @crufter
