### ISSUE TITLE
panic: qtls.ConnectionState not compatible with tls.ConnectionState

### ISSUE THREAD

**Issue by forging2012** [micro/micro#1574]
curl -fsSL https://install.m3o.com/micro | /bin/bash

➜  ~ micro -v
panic: qtls.ConnectionState not compatible with tls.ConnectionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.1()
	/Users/admin/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.13.1/internal/handshake/unsafe.go:17 +0x12e
➜  ~ go version
go version go1.15.4 darwin/amd64

**Comment by jingshanccc** [comment]
用低于1.15的go就行了

**Comment by DingJohn** [comment]
go get github.com/micro/micro/v3

**Comment by Geoisnow** [comment]
![image](https://user-images.githubusercontent.com/39164400/146736458-fee896a3-bcf7-4e6f-8da2-2e4c0913497e.png)
same panic,how to solve it

**Comment by Sofar1994** [comment]
> same panic,how to solve it

go version 1.15

**Comment by caihuahang8** [comment]
Try the lower version
go version lower than 1.5

**Comment by JoyCood** [comment]
same panic,
go version go1.19.13 darwin/amd64
micro version v3.12.3
