### ISSUE TITLE
Default branch `master` not found

### ISSUE THREAD

**Issue by heldrida** [micro/micro#1576]
**Describe the bug**
The cli throws a `service github.com/xxx/yy@master not found` as it expects `master` to exist.
Given recent conventions, the default branch name is `main` instead of `master` at least on GitHub and such.

**To Reproduce**
1. Create a Github repository and keep the default settings
2. Run the cmd micro run <repository-url>

**Expected behavior**
Should not assume that the default branch name is `master`, so not throw `Service at github.com/xxxx/yyy@master not found`

**Comment by asim** [comment]
Thanks for letting us know. You can specify micro run url@branch to short circuit this bug but we'll also take a look. Its unclear how we fix since many things are still defaulted to master and new things are main.

**Comment by domwong** [comment]
We've addressed this in https://github.com/micro/micro/pull/1578
