### ISSUE TITLE
Question: Is this project targetted exclusively at Go?

### ISSUE THREAD

**Issue by acobster** [micro/micro#1577]
This might be a very obvious question to someone coming from the Go ecosystem with prior knowledge of go-micro etc., but for someone like me just hearing about this, it's not very clear. :)

For context let me just briefly describe where my confusion comes from. The [introduction](https://micro.mu/introduction) mentions Go by name and calls Micro "Android for Cloud," implying that you need to work within a specific ecosystem. But it's not clear how specific the meaning is, since it could mean that it's a unifying platform more generally, even if it's polyglot. And the [blog post](https://micro.mu/blog/2020/11/05/micro-v3-aka-m3o.html) just recently up on Lobste.rs compares Micro to the Heroku/PaaS experience, also implying polyglot, but at other times heavily implying Go-specific (e.g. "single-purpose").

So, can I write a containerized app and run it on Micro using something akin to a buildpack, or must all my services be written in Go? It would be worth being explicit about this in the intro and/or the FAQ.

**Comment by asim** [comment]
Thanks for the question. Right now we're entirely focused on Go and it's become this is the best way for us to provide a truly great development experience. The generic PaaS is a thing that's re-emerging but I think it's just another layer of abstraction on compute. Micro provides primitives for Auth, config, events, storage, etc that you actually get guided to use through a built in framework. Like every platform before they were singe language dominant, Android being the prime case. Cloud is as complex as Mobile was and we need to be super focused on making that a better experience. I also think service standardisation, performance, security, etc work better when it's single language focused. We are developing multi language clients to access those services but we only have support to run Go Micro services. Hope that helps.
