### ISSUE TITLE
Getting a "connection closed" error after running the server and trying to login

### ISSUE THREAD

**Issue by rochinworks** [micro/micro#1583]
**Describe the bug**
I get a "connection closed" error after trying to login.

**To Reproduce**
1. run `micro server`
2. in another terminal run `micro login`
3. "connection closed"
4. same error for all commands afterwards

**Expected behavior**
I would expect a more detailed error so I can figure out what to do next.

**Desktop (please complete the following information):**
 - OS: mac osx
 - version: 3.0.0-beta

**Additional context**
Just updated to go 1.15 because I was having trouble running micro on go 1.13.

**Comment by rochinworks** [comment]
I found the log message in memory.go in the internal/network/transport folder. From there I realized my kubernetes for docker had never started up: related docker issue https://github.com/docker/for-mac/issues/3327.
I'm now encountering the following error:
```
$ micro login
Enter username: admin
Enter password:
Error authorizing request: {"Id":"go.micro.client","Code":500,"Detail":"{\"Id\":\"go.micro.client\",\"Code\":500,\"Detail\":\"service auth: route not found\",\"Status\":\"Internal Server Error\"}","Status":"Internal Server Error"}
```
which is a duplicate of this issue: https://github.com/micro/micro/issues/1544#issuecomment-719858646, so I am closing.

**Comment by 1400720231** [comment]
i have the same question with U. I use "go install github.com/micro/micro/v3@latest" to run runtime server. first it works when i use "micro login "or other command but it did not work when sometime, i tried google and read my note, but nothing to get why. i just restart mysql computer  then i login successfuly......

**Comment by HANCHIE** [comment]
i guess this is because of network policy, when you allow the window of confirmation, restart your computer.

**Comment by pablos44** [comment]
Same here. I'm new in micro. Tried runing local on windows. Almost every command printed "connection closed"  
```
>micro login
Enter username: admin
Enter password:
Connection closed
>
```

**Comment by pablos44** [comment]
> Same here. I'm new in micro. Tried runing local on windows. Almost every command printed "connection closed"
> 
> ```
> >micro login
> Enter username: admin
> Enter password:
> Connection closed
> >
> ```

The 8081 port was allocated with another process.
