### ISSUE TITLE
HELP: Getting  invalid memory address or nil pointer dereference in config

### ISSUE THREAD

**Issue by hm0** [micro/micro#1589]
**Describe the bug**
Testing micro 3 config feature I've created a small example. However from within the code when running it I'm getting 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xccbcfe]

goroutine 1 [running]:
github.com/micro/micro/v3/service/config.Get(...)
        /tmp/blob-697923440/vendor/github.com/micro/micro/v3/service/config/config.go:64
main.main()
        /tmp/blob-697923440/main.go:12 +0x3e
exit status 2

**To Reproduce**
1. create 2 variables for config. dbtype and dburl 
  micro config set dbtype mysql
  micro config set --secret dburl "test:test@tcp(127.0.0.1:3306)/test?parseTime=true"

2. Check if present
hmo@aura: ~/pro/q micro config get dbtype
mysql
hmo@aura: ~/pro/q micro config get --secret dburl
test:test@tcp(127.0.0.1:3306)/test?parseTime=true

3. Small code to test it. And place the main.go in a specific folder for instance test
package main
import (
	"fmt"
	"github.com/micro/micro/v3/service"
	"github.com/micro/micro/v3/service/config"
)
func main() {
	dbtype, err1 := config.Get("dbtype")
	fmt.Println("Value of dbtype: ", dbtype.String(""), err1)
	dburl, err2 := config.Get("dburl", config.Secret(true))
	fmt.Println("Value of dburl: ", dburl.String(""), err2)
	// run the service
	service.Run()
}

4. Run micro server and micro login
5. From within folder test run the example

**Expected behavior**
It should show / print the values. However is showing the following
hmo@aura: ~/pro/q micro logs q
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xccbcfe]

goroutine 1 [running]:
github.com/micro/micro/v3/service/config.Get(...)
        /tmp/blob-697923440/vendor/github.com/micro/micro/v3/service/config/config.go:64
main.main()
        /tmp/blob-697923440/main.go:12 +0x3e
exit status 2

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Version micro 3 (compiled from source)

**Comment by asim** [comment]
Are you running the service using micro?

**Comment by hm0** [comment]
Tested with:
go run main.go and micro run .
Same error...

**Comment by asim** [comment]
OK thanks, please ping us on slack in the am GMT and we'll have a look

**Comment by crazybber** [comment]
this is current way:

```go
srv := service.New() 

//get your config here
a,b := config.Get("xxxx")

```

below config is not working

```go
//get your config here
a,b := config.Get("xxxx")

srv := service.New() 

```

**Comment by hm0** [comment]
Thanks that worked.
