### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by adamfaliq42** [micro/micro#159]
Is it possible to add contributions guideline in the README.md section?

**Comment by asim** [comment]
What would you want the contributions guideline to include?

**Comment by adamfaliq42** [comment]
I'd like to know, any particular process of submitting a pull request? And is there any particular issues/ tasks that you'd like to add in the future? If yes, maybe make a list of that as well. 

Hope this is relevant.

**Comment by asim** [comment]
Thanks. I'll take these notes on board and look to add something. For the moment join the slack to discuss and see the project board https://github.com/micro/micro/projects/1
