### ISSUE TITLE
micro run helloworld:  Not authorized to perform this request

### ISSUE THREAD

**Issue by younglifestyle** [micro/micro#1590]
micro v3.0.1
micro run or status，will prompt Not authorized to perform this request

**Comment by crazybber** [comment]
follow the starter guide

**Comment by younglifestyle** [comment]
tks，is my problem

**Comment by yiippee** [comment]
> tks，is my problem

On windows 10，I follow the [https://micro.mu/getting-started](https://micro.mu/getting-started) ，micro login, but still  prompt Not authorized to perform this request. Do I miss something, thanks a lot.

**Comment by SummerJune30** [comment]
On windows 10，I follow the https://micro.mu/getting-started ，micro login, but still prompt Not authorized to perform this request. Do I miss something, thanks a lot.

**Comment by lanyuechuan** [comment]
Does micro3 add certification, but how can I authenticate？
