### ISSUE TITLE
go get -u  go get github.com/micro/micro/v3 -- compile error 

### ISSUE THREAD

**Issue by it512** [micro/micro#1614]
MikeWang@MikeWang-Air app % go get github.com/micro/micro/v3
# github.com/micro/micro/v3/internal/api/server/acme/certmagic
../../go/pkg/mod/github.com/micro/micro/v3@v3.0.1/internal/api/server/acme/certmagic/certmagic.go:40:24: certmagic.DefaultACME.DNSProvider undefined (type certmagic.ACMEManager has no field or method DNSProvider)
../../go/pkg/mod/github.com/micro/micro/v3@v3.0.1/internal/api/server/acme/certmagic/storage.go:159:9: cannot use &storage literal (type *storage) as type certmagic.Storage in return argument:
	*storage does not implement certmagic.Storage (wrong type for Lock method)
		have Lock(string) error
		want Lock(context.Context, string) error

-----------------
OS mac os

golang version : 1.15.4

micro version: 3.0.1

**Comment by asim** [comment]
Don't do `-u`

**Comment by it512** [comment]
MikeWang@MikeWang-Air app % go get github.com/micro/micro/v3 
# github.com/micro/micro/v3/internal/api/server/acme/certmagic
../../go/pkg/mod/github.com/micro/micro/v3@v3.0.2/internal/api/server/acme/certmagic/certmagic.go:40:24: certmagic.DefaultACME.DNSProvider undefined (type certmagic.ACMEManager has no field or method DNSProvider)
../../go/pkg/mod/github.com/micro/micro/v3@v3.0.2/internal/api/server/acme/certmagic/storage.go:159:9: cannot use &storage literal (type *storage) as type certmagic.Storage in return argument:
	*storage does not implement certmagic.Storage (wrong type for Lock method)
		have Lock(string) error
		want Lock(context.Context, string) error
MikeWang@MikeWang-Air app % 


--------------

ver ：3.0.2

**Comment by yongliu1992** [comment]
> MikeWang@MikeWang-Air app % go get github.com/micro/micro/v3
> 
> # github.com/micro/micro/v3/internal/api/server/acme/certmagic
> ../../go/pkg/mod/github.com/micro/micro/v3@v3.0.2/internal/api/server/acme/certmagic/certmagic.go:40:24: certmagic.DefaultACME.DNSProvider undefined (type certmagic.ACMEManager has no field or method DNSProvider)
> ../../go/pkg/mod/github.com/micro/micro/v3@v3.0.2/internal/api/server/acme/certmagic/storage.go:159:9: cannot use &storage literal (type *storage) as type certmagic.Storage in return argument:
> *storage does not implement certmagic.Storage (wrong type for Lock method)
> have Lock(string) error
> want Lock(context.Context, string) error
> MikeWang@MikeWang-Air app %
> 
> ver ：3.0.2

删除你本地版本库里面的那些，然后重新build， 或者你直接去下载一个 二进制包，可以直接运行micro的那种。

**Comment by it512** [comment]
@yongliu1992 兄弟， 我都删的干干净净了， 我查过代码确定没有实现那2个方法

**Comment by yongliu1992** [comment]
> @yongliu1992 兄弟， 我都删的干干净净了， 我查过代码确定没有实现那2个方法

是你那个包里面的缓存($GOPATH/src/github.com/micro)，另外别用go get -u ,直接go get github.com/micro/micro/v3
