### ISSUE TITLE
run demo error (mac os), need help

### ISSUE THREAD

**Issue by yongliu1992** [micro/micro#1621]
micro version v3.0.2

![image](https://user-images.githubusercontent.com/15151715/101018193-1b12eb00-35a6-11eb-967a-5a0bf5e23163.png)
![image](https://user-images.githubusercontent.com/15151715/101018241-2a923400-35a6-11eb-854f-bd300f68e3eb.png)

May I trouble you to tell me where I was wrong?

**Comment by lambdaR** [comment]
take a look at this [tutorial](https://docs.m3o.com/tutorials/building-a-blog/the-post-service)

**Comment by yongliu1992** [comment]
> tutorial

Thank you. I'll try

**Comment by yongliu1992** [comment]
First use micro env set local, then use micro server, It's all right
