### ISSUE TITLE
Can I use micro on the non-profit project in the company？

### ISSUE THREAD

**Issue by SgtDaJim** [micro/micro#1625]
We have our own k8s clusters, and I world like to develop some microservices with micro and deploy them on k8s. Will I break the license because of that?
And specially speaking, What do I do would break the license？

**Comment by asim** [comment]
You can use micro for anything as long as you don't sell micro as a service. So yes you can use it for non profit.

**Comment by SgtDaJim** [comment]
@asim Understood. Thanks.
