### ISSUE TITLE
package xxx is not in GOROOT

### ISSUE THREAD

**Issue by lxyz123** [micro/micro#1629]
I write an example with microv2 , however occurs a problem which is when i go run main.go , package xxx is not in GOROOT？

![image](https://user-images.githubusercontent.com/52751169/101451255-ccc76880-3966-11eb-9188-38ad45973c6c.png)

![image](https://user-images.githubusercontent.com/52751169/101451397-0b5d2300-3967-11eb-935a-995fcc7a08b6.png)

![image](https://user-images.githubusercontent.com/52751169/101451359-fa141680-3966-11eb-8c0e-e4c72fda3240.png)

sincerely ask for a solution

**Comment by arbarlow** [comment]
I don't think it's picking up your go mod properly and therefor not using Go modules. Please can you try to `go mod init` in the directory your project is?

I can see a go.mod and not a go.sum which would suggest some issue

**Comment by Randix6644** [comment]
I have the same problem and don't know how to fix it.

**Comment by xxmNIe** [comment]
1.run  make proro
generate two file in your proto
2. go mod tidy or run xxx
