### ISSUE TITLE
How do I run the cluster use micro with seperated services?

### ISSUE THREAD

**Issue by xzzh999** [micro/micro#1645]
Hi~ 
greate work!

When i run the `micro server` command, it's start 12 micro component services as 12 processes, i wonder how can i only run one or sub of them? I need seperate the api gateway and other services in different nodes.

thank you~

**Comment by asim** [comment]
`micro service [X]`

They all require significant configuration and it's recommended you use helm install which can be found in github.com/micro/services

**Comment by xzzh999** [comment]
@asim thank you very much, i'll try that~
