### ISSUE TITLE
how to setup micro server cluster

### ISSUE THREAD

**Issue by wanhex** [micro/micro#1661]
In [https://micro.mu/getting-started](https://micro.mu/getting-started) document, micro server is running as a Monolith arch，both micro server and business service (micro run helloworld) are running in a signle OS instance，then micro server expose http api through HTTP GW. In fact, in MicroService arch, there will be many micro server and business service are running in different OS instance, they use the same Registry center, but I am not find any document  which describing how to setup this. 

Is there some document  which describing how to setup this?

**Comment by vtolstov** [comment]
this is not goal of the micro team, use PaaS or ... nothing

**Comment by abogushov** [comment]
@wanhex I think you need to set up your Kubernetes cluster and deploy services to it. Use Micro helm (https://github.com/micro/helm) chart to deploy it in the Kubernetes cluster. There is also a tutorial(https://itnext.io/go-micro-on-kubernetes-getting-started-2959dd6c2d4f).
