### ISSUE TITLE
Model issues / todo

### ISSUE THREAD

**Issue by asim** [micro/micro#1669]
Issues related to the model that's blocking us from using it. Things for @crufter to look at.

- `For query type 'eq', field 'ID' does not match any indexes`
- Can't query by more than one field (https://github.com/micro/services/pull/39/files#diff-ee566e1f089e0b8a51129c392b7b15aa73253d44df2ba768d300373415a9ac15R69)
- `For query type '', field '' does not match any indexes` when using model.Query{}
- Need for; Listing, Updates, Transactions
- Batch reading multiple ids

**Comment by crufter** [comment]
> For query type 'eq', field 'ID' does not match any indexes

Can I get a repro for this as this is expected when the query does not match the index.
The default ID index is unordered, but the default queries are ordered, so

```
q := model.Equals("ID", s.ID)
q.Order.Type = model.OrderTypeUnordered
d.db.Delete(q);
```

**Comment by crufter** [comment]
> Need for; Listing, Updates, Transactions
Listing and update should exist from day 1.
I would not tackle transactions yet as it's basically a close to impossible problem to solve and we did fine without it at Hailo for years of production usage.
