### ISSUE TITLE
Account not found with this ID

### ISSUE THREAD

**Issue by jun3372** [micro/micro#1671]
**Describe the bug**
I registered an account elsewhere, and then I cannot log in on the new server. The prompt: "Account not found with this ID"

**To Reproduce**
```shell
micro env set platform

micro signup
Enter email address: xxx@xxx.com
Customer with this email address already exists

micro login
Enter username: xxx@xxx.com
Enter password: 
Account not found with this ID
```

**Expected behavior**
```shell
micro login
Enter username: xxx@xxx.com
Enter password: 
Successfully logged in.
```

**Comment by asim** [comment]
You must set the same namespace on the command line as exists in other config. 

micro signup recover --email xxx@xxx.com

Will send you your namespace. Then set with

micro user set namespace xxx

**Comment by jun3372** [comment]
Can I retrieve the namespace by email

**Comment by asim** [comment]
https://docs.m3o.com/faq#account-recovery

**Comment by jun3372** [comment]
Thank you for your help
