### ISSUE TITLE
kill micro srv service didn't deregister from consul

### ISSUE THREAD

**Issue by zjn1234** [micro/micro#168]
when i run a go-micro service 
use kill -9 kill make progress terminated but didn't deregister from consul
signal.Notify(ch, syscall.SIGTERM, syscall.SIGINT, syscall.SIGKILL)  in Run function didn't work

but ctrl-c works

**Comment by asim** [comment]
Kill -9 is a forceful kill and the signal cannot be caught by any program

**Comment by asim** [comment]
use the command line `micro deregister service` with the service definition
