### ISSUE TITLE
unknown field "max" in vessel.Vessel

### ISSUE THREAD

**Issue by tullo** [micro/micro#1703]
When running with micro release Release v3.0.4 I can interact with the vessel service like this:

```
micro shippy.service.vessel vesselService create \
	--name 'vessel01' --capacity 300 --max_weight 500 --available true
```
But when running with current head version (micro/v3@v3.0.5-0.20210202220323-c0f344d21cc6)

I get `unknown field "max" in vessel.Vessel` for the exact same proto.

```
message Vessel {
  string id = 1;
  int32 capacity = 2;
  int32 max_weight = 3;
  string name = 4;
  bool available = 5;
  string owner_id = 6;
}
```
https://github.com/tullo/shippy/blob/master/shippy-service-vessel/proto/vessel.proto

Having field names with [underscores](https://developers.google.com/protocol-buffers/docs/style) should not be a problem.

How can I resolve this without renaming fields?

**Comment by asim** [comment]
Use the JSON representation maxWeight

**Comment by tullo** [comment]
`micro> shippy.service.vessel vesselService create --name 'vessel01' --capacity 300 --maxWeight 500 --available true`
Unknown flag: maxWeight
