### ISSUE TITLE
upload file via micro api issue

### ISSUE THREAD

**Issue by jinbanglin** [micro/micro#171]
i start micro api and need to upload file to micro api ,then rpc to my file service.is it no file codec?

**Comment by asim** [comment]
There is no file codec. You'll to deal with this yourself. I would advise using the http handler which would proxy the request and chunk the upload.

**Comment by jinbanglin** [comment]
i have used it with micro web now.it work.  thanks .

**Comment by asim** [comment]
Don't do that. The micro web proxy is essentially deprecated. Use micro with the http or web handlers.
