### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by pootz** [micro/micro#1712]
Describe the bug

Running go get github.com/micro/micro/v3/cmd/protoc-gen-micro results in an error

To Reproduce

Run go get github.com/micro/micro/v3/cmd/protoc-gen-micro

Expected behavior

No output is expected. The package should just be installed with no errors.

Actual result
`
cannot find package "github.com/micro/micro/v3/cmd/protoc-gen-micro" in any of: 
/usr/local/go/src/github.com/micro/micro/v3/cmd/protoc-gen-micro (from $GOROOT)
/home/bernardo/work/src/github.com/micro/micro/v3/cmd/protoc-gen-micro (from $GOPATH)
`

Here is the link to the docs: [https://micro.mu/getting-started#dependencies](https://micro.mu/getting-started#dependencies)

**Comment by asim** [comment]
Please ensure you are using go modules
