### ISSUE TITLE
How to set timeout when HTTP requests to call grpc through micro API

### ISSUE THREAD

**Issue by fuemoshi** [micro/micro#1716]
i can call grpc like this:
```
curl -H 'Timeout: 600' -d 'service=workflow.srv.api.cloudSync' \
    -d 'method=CloudSync.Execute' \
    -d 'request={}' http://localhost:8088/rpc
```
and timeout set to 600s  

but when i call below:
```
curl -XPOST -H 'Content-Type: application/json' -H 'Timeout: 600'  -d '{}' http://localhost:8088/cloudSync/execute
```
timeout not working

How to set timeout when using the second method？

FYI, i use micro v2.6.0

**Comment by asim** [comment]
its a nanosecond value

**Comment by fuemoshi** [comment]
> its a nanosecond value

hi, thanks for your reply. i try large number still not work like below:
```
curl -XPOST -H 'Content-Type: application/json' -H 'Timeout: 60000000000' -d '{}' http://localhost:8088/cloudSync/execute
```
and try
```
time curl -H 'Timeout: 20' -d 'service=workflow.srv.api.cloudSync' \
    -d 'method=CloudSync.Execute' \
    -d 'request={}' http://localhost:8088/rpc
```
is fine, it looks like a second value

**Comment by fuemoshi** [comment]
the question is  i can't pass the timeout value to grpc client_request_timeout when use  "http://localhost:8088/{serviceName}/{method}", 
but i can do that through  "http://localhost:8088/rpc"
