### ISSUE TITLE
How do I specify the registration method when starting the server

### ISSUE THREAD

**Issue by cyrus-zhang** [micro/micro#1717]
micro V3:
How do I specify the registration method when starting the micro server

I did not see --registry like v2.

**Comment by asim** [comment]
We only now have profiles. You must set MICRO_PROFILE={local, kubernetes, ...} or define your own

**Comment by cyrus-zhang** [comment]
Thank you very much for responding to this question. Your answer is consistent with my guess. I have been able to use this feature correctly, but I am sorry for not being able to close the issue in time. Thanks again!
