### ISSUE TITLE
Is there any way to get global context value(commond line args...) in individual handler?

### ISSUE THREAD

**Issue by Aavon** [micro/micro#172]
I want to use the args to init some tool（not the implemented  plugins） in the handler.So, is there any effective way to achieve it?

**Comment by asim** [comment]
[cli.Context](https://godoc.org/github.com/micro/cli#Context) is passed to the [micro/plugin](https://godoc.org/github.com/micro/micro/plugin#Options) Init method. 

If you're talking about go-micro. This can be retrieved with [Action](https://godoc.org/github.com/micro/go-micro#Action) option.
