### ISSUE TITLE
Runtime class name not being passed on update (v3.1.0)

### ISSUE THREAD

**Issue by SebScoFr** [micro/micro#1720]
micro version used: **v3.1.0**

1. I create a new service called user on my local machine using: `micro new user`
2. I cd into the new service root folder: `cd user`
3. I deployed it to a remote Kubernetes cluster on GCP using: `micro run .`
4. I made some changes to my handlers
5. I tried to redeploy the service using: `micro update .`

The last step fails and the service never gets updated on Kubernetes.

The logs from the runtime (`micro logs -f runtime`) shows this:
```
2021-02-28 19:41:49  file=handler/handler.go:474 level=info service=runtime Updating service user version latest source source://user:latest
2021-02-28 19:41:49  file=manager/util.go:51 level=info service=runtime Preparing to build user:latest
2021-02-28 19:41:49  file=manager/util.go:100 level=info service=runtime Build starting user:latest
2021-02-28 19:42:23  file=manager/util.go:105 level=info service=runtime Build finished user:latest <nil>
2021-02-28 19:42:23  file=manager/util.go:115 level=info service=runtime Uploading build user:latest
2021-02-28 19:42:24  file=kubernetes/kubernetes.go:383 level=error service=runtime Runtime failed to update deployment: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Deployment.apps \"user-latest\" is invalid: spec.template.spec.runtimeClassName: Invalid value: \"\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"user-latest","group":"apps","kind":"Deployment","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"spec.template.spec.runtimeClassName"}]},"code":422}
```

Looks like an empty runtimeClassName on update.

**Comment by asim** [comment]
Where is your k8s cluster hosted?

**Comment by SebScoFr** [comment]
Kubernetes cluster is hosted on GKE (Google Kubernetes Engine) in location europe-west1-b.
I have deployed micro to Kubernetes using the helm chart 1.2.0, which corresponds to micro version 3.1.0.

On local I have added a new environment corresponding to my micro proxy on Kubernetes: `micro env add my-env x.x.x.x:8081`. Then I made sure to select this environment and login to it.

Note that `micro run` and `micro kill` works, only `micro update` doesn't.

**Comment by asim** [comment]
What is the output of `kubectl get runtimeclasses`

**Comment by SebScoFr** [comment]
```
seb@macbookpro ~/$ kubectl get runtimeclasses
NAME     HANDLER   AGE
gvisor   gvisor    5d6h
```

**Comment by asim** [comment]
Have you enabled gvisor or is this the default?

**Comment by SebScoFr** [comment]
I believe it must be the default since I have not done anything special to enable it

**Comment by asim** [comment]
My assumption is that when we read back the deployment to update the runtime class is not present or we're basically overwriting it. Can you do `kubectl describe deployment [name]` for your deployment to see if it present.

**Comment by SebScoFr** [comment]
It doesn't seem to be there indeed
```
seb@macbookpro ~/$ kubectl describe deployment user-latest -n micro
Name:                   user-latest
Namespace:              micro
CreationTimestamp:      Thu, 25 Feb 2021 20:54:36 +0000
Labels:                 micro=
                        name=user
                        version=latest
Annotations:            deployment.kubernetes.io/revision: 1
                        group: micro
                        name: user
                        owner: admin
                        source: /srv/user
                        started: 2021-02-25T20:54:02Z
                        status: unknown
                        version: latest
Selector:               micro=,name=user,version=latest
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       micro=
                name=user
                version=latest
  Annotations:  group: micro
                name: user
                owner: admin
                source: /srv/user
                started: 2021-02-25T20:54:02Z
                status: unknown
                version: latest
  Containers:
   user:
    Image:      micro/cells:v3
    Port:       8080/TCP
    Host Port:  0/TCP
    Readiness:  tcp-socket :8080 delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MICRO_PROFILE:
      MICRO_SERVICE_NAME:     user
      MICRO_SERVICE_VERSION:  latest
      MICRO_PROXY:            network.micro.svc.cluster.local:8443
      MICRO_SERVICE_ADDRESS:  :8080
      MICRO_NAMESPACE:        micro
      MICRO_AUTH_ID:          <set to the key 'MICRO_AUTH_ID' in secret 'user-latest'>      Optional: false
      MICRO_AUTH_SECRET:      <set to the key 'MICRO_AUTH_SECRET' in secret 'user-latest'>  Optional: false
    Mounts:                   <none>
  Volumes:                    <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   user-latest-6f5c4bd78c (1/1 replicas created)
Events:          <none>
```

**Comment by asim** [comment]
I think I have a fix. I have a feeling the helm chart hasn't been tested since runtime class support was added. I believe we have to omit runtime class in the API call which should resolve the issue. I'll do a minor release in a few hours and update the helm chart.

**Comment by SebScoFr** [comment]
Thanks @asim

**Comment by SebScoFr** [comment]
Any update on the release @asim ?

**Comment by asim** [comment]
Tagged a release 3.1.1 with the proposed fix. You should see helm chart version micro-1.2.1 soon.

**Comment by SebScoFr** [comment]
Thanks @asim, minor thing but after deploying this new version, calling this API root endpoint yields `"version": "v3.0.4"` rather than `"version": "v3.1.1"`

**Comment by asim** [comment]
I think it implies you're not running the latest version. Not sure if this is because the helm chart is not updating it or because there's some other issue. It should report the latest version if it changed.

**Comment by SebScoFr** [comment]
That's odd, I juts did a fresh install of it using `helm upgrade --install micro micro/micro`
And still getting `"version": "v3.0.4"`

**Comment by SebScoFr** [comment]
FYI, I simply `kubectl apply` the deployment file: https://github.com/micro/helm/blob/main/charts/micro/templates/deployment.yaml
And then v3.1.1 gets deployed successfully on k8s. Must be something to do with helm somehow

**Comment by asim** [comment]
Let me know if there's any change in behaviour to the `micro update` command

**Comment by SebScoFr** [comment]
@asim I'm not sure if this is because of the fix you did, but since I am using 3.1.1, I can use `micro run` or `micro update` at all when deploying services to k8s. It systematically fails with 
`Rpc error: code = Canceled desc = grpc: the client connection is closing`
I have a feeling that 3.1.1 has introduced a breaking change there.

**Comment by SebScoFr** [comment]
Getting this in the runtime logs
```
2021-03-03 13:07:52  file=grpc/grpc.go:236 level=error service=runtime grpc handler got error: rpc error: code = Internal desc = {"Id":"runtime.Source.Upload","Code":500,"Detail":"rpc error: code = Canceled desc = context canceled","Status":"Internal Server Error"}
```

**Comment by asim** [comment]
If what you're saying is that your previous version was 3.0.4 then there's a number of changes since then https://github.com/micro/micro/compare/v3.0.4...master but not sure what the issue would be. Can you look at proxy and runtime logs. I feel like maybe the deployment is broken.

**Comment by SebScoFr** [comment]
@asim 

Proxy logs:
`2021-03-03 14:09:28  file=grpc/grpc.go:236 level=error service=proxy grpc handler got error: rpc error: code = Canceled desc = context canceled`

Runtime logs:
`2021-03-03 14:09:28  file=grpc/grpc.go:236 level=error service=runtime grpc handler got error: rpc error: code = Internal desc = {"Id":"runtime.Source.Upload","Code":500,"Detail":"rpc error: code = Canceled desc = context canceled","Status":"Internal Server Error"}`

**Comment by asim** [comment]
Can you also look at store and network logs.

Has anything changed in the code you're running? Is it larger than previous versions?

**Comment by SebScoFr** [comment]
@asim 

No error on store

Error on network:
`2021-03-03 14:51:13  file=grpc/grpc.go:236 level=error service=server grpc handler got error: rpc error: code = Canceled desc = context canceled`

**Comment by asim** [comment]
Has the IP of the api/proxy changed with the redeploy? Have you checked against `micro env` to make sure its pointing to the right place?

**Comment by asim** [comment]
Can you also relogin as the tokens may have changed because of the complete redeploy

**Comment by SebScoFr** [comment]
Yep I made sure of all of that. Also I'm just trying to deploy the default service create by `micro new` so nothing fancy.
Can you deploy successfully to k8 using 3.1.1?

**Comment by SebScoFr** [comment]
@asim I apologize, the issue apparently came from the wifi connection at the place I have been working today... I tried again just now from home and it works. Also update now works on k8s. Thanks a for that
