### ISSUE TITLE
All going well on Linux，but on windows...

### ISSUE THREAD

**Issue by xieyicai** [micro/micro#1732]
![windows](https://user-images.githubusercontent.com/18302242/111023385-bc1a0900-8413-11eb-9fd1-26be89f79988.png)

**Comment by asim** [comment]
Probably down to how were doing filepath join to read the token off disk. You can find this somewhere in internal/user or internal/config if you want to contribute fixes.

**Comment by xieyicai** [comment]
**I found the problem, but I don't know how to solve it**

![token](https://user-images.githubusercontent.com/18302242/111025916-4cf7e100-8422-11eb-9d9e-19c46862e3d0.png)

**Comment by HuynhBrian** [comment]
I am experiencing the same problem, platform is Windows 10

**Comment by zenghao306** [comment]
> ![windows](https://user-images.githubusercontent.com/18302242/111023385-bc1a0900-8413-11eb-9fd1-26be89f79988.png)

你要以管理员身份启动cmd然后运行micro server
