### ISSUE TITLE
Create profiles for aws, gcp and azure

### ISSUE THREAD

**Issue by asim** [micro/micro#1733]
Given we're looking at cloud platforms as hardware the way Linux did with CPUs we need to support the most common platforms by creating profiles which leverage the managed services of those providers. This creates true portability.

Create profiles for aws, gcp and azure which plugin the various components of the underlying platforms and make it drastically simple to start on them by just specifying MICRO_PROFILE=aws

**Comment by lambdaR** [comment]
It would be better **imo** if you keep micro agnostic and instead focus on showing how to achieve that by providing detailed and well explained tutorials for these cloud providers.
Knowing how to do that properly (micro idiomatic way) would give developers the knowledge to squeeze the last bit of micro not only for these common cloud providers but every cloud provider. 
 
On the other hand, I think micro could play a central role in the Machine Learning pipeline - new audience.

**Comment by asim** [comment]
Not sure about the ML point but otherwise I think there's enough demand for native use on AWS and other cloud providers that we could crowdsource the work if we laid out how it should be done.
