### ISSUE TITLE
Error generation .proto

### ISSUE THREAD

**Issue by Simbalala** [micro/micro#1741]
Hello,
If you execute `micro new service` and execute `make proto`

![image](https://user-images.githubusercontent.com/35727366/112219330-20637680-8c25-11eb-9278-9829c5179907.png)

He have a mistake un generation of .proto It's missing `./` before `"proto;hello"`

![image](https://user-images.githubusercontent.com/35727366/112219537-6c162000-8c25-11eb-9666-6974aeb6b807.png)

 `"./proto;hello"`

**Comment by xxlest** [comment]
thanks very much

> Hello,
> If you execute `micro new service` and execute `make proto`
> 
> ![image](https://user-images.githubusercontent.com/35727366/112219330-20637680-8c25-11eb-9278-9829c5179907.png)
> 
> He have a mistake un generation of .proto It's missing `./` before `"proto;hello"`
> 
> ![image](https://user-images.githubusercontent.com/35727366/112219537-6c162000-8c25-11eb-9666-6974aeb6b807.png)
> 
> `"./proto;hello"`

thanks very much, this isse took my whole day to fix,  i was in mistake for conflict protobuf with protoc-gen-go
