### ISSUE TITLE
darwin-arm64 not supported

### ISSUE THREAD

**Issue by m0essy** [micro/micro#1742]
**Describe the bug**
When executing `curl -fsSL https://raw.githubusercontent.com/micro/micro/master/scripts/install.sh | /bin/bash` on Mac OS I get the following error:
```
Getting system information
Your machine is running darwin on arm64 CPU architecture
Checking machine system support
No prebuilt binary for darwin-arm64
Failed to install micro
```

I think the Macbooks with the M1 CPU are not supported yet

**Comment by asim** [comment]
Thanks for the note. I think the M1 CPU has only just gotten support in Go. It might be a little while before we have a prebuilt binary for it.

**Comment by korman** [comment]
> Thanks for the note. I think the M1 CPU has only just gotten support in Go. It might be a little while before we have a prebuilt binary for it.

thank godness!

I'm going to buy M1 next week!

can you solve the problem?

**Comment by crashdump** [comment]
@korman using `go get` with Go 1.16+ works like a charm.

`go get github.com/micro/micro/v3`

**Comment by asim** [comment]
Latest release contains the binary required https://github.com/micro/micro/releases/tag/v3.2.1

**Comment by crashdump** [comment]
Thank you Asim, I tested the prebuilt binary on M1 and it's randomly being killed.

`./micro-v3.2.1-darwin-arm64/micro --version`
`[1]    69553 killed     ./micro --version`

Which is curious, since the following works just fine:

`go get github.com/micro/micro/v3`
`go: downloading github.com/micro/micro/v3 v3.2.1`

`~/Go/bin/micro --version
`micro version v3.0.0`

It could very well be my setup and I'll try to investigate this further, it's very odd.

**Comment by asim** [comment]
That's very strange. The binaries are built using Go 1.16 and GoReleaser. It's unclear why it would happen. We do disable CGO in the build...

**Comment by crashdump** [comment]
It seems to be something to do with code signing.

`Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)`
`Exception Codes:       0x0000000000000032, 0x0000000102500000`
`Exception Note:        EXC_CORPSE_NOTIFY`

`Termination Reason:    Namespace CODESIGNING, Code 0x2`

Which could be related to [the following announcement in Apple's Big Sur release notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes).

> New in macOS 11 on Apple silicon Mac computers, and starting in the next macOS Big Sur 11 beta, **the operating system will enforce that any executable must be signed with a valid signature before it’s allowed to run**. There isn’t a specific identity requirement for this signature: a simple ad-hoc signature issued locally is sufficient, which includes signatures which are now generated automatically by the linker. **This new policy doesn’t apply to translated x86 binaries running under Rosetta, nor does it apply to macOS 11 running on Intel platforms**.

**Comment by crashdump** [comment]
The issue had nothing to do with Micro, the build works perfectly fine.

The problem I had was Apple's quarantine file attribute not working as expected, clearing it manually solved it (see below).

`$ xattr -v micro`
`micro: com.apple.quarantine`

`$ xattr -d com.apple.quarantine micro`

`$ micro --version`
`micro version v3.2.1`

**Comment by asim** [comment]
That's great. Thanks for the help.
