### ISSUE TITLE
Not authorized to perform this request On Win10

### ISSUE THREAD

**Issue by yangyanqing** [micro/micro#1745]
**Describe the bug**
On windows 10，I follow the https://micro.mu/getting-started 

**To Reproduce**
1. Install micro 
```bash
go get github.com/micro/micro/v3
go get github.com/golang/protobuf/protoc-gen-go
go get github.com/micro/micro/v3/cmd/protoc-gen-micro
```
2. Start server by `micro server`
3. Login by ` micro login --username admin --password micro` and success
4. Call `micro service` got Not authorized to perform this request

**Screenshots**
![image](https://user-images.githubusercontent.com/7357939/112744917-b6f1b800-8fd6-11eb-8354-c78d4dce3aa3.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 Professional Edition（19042.867）
 - Browser N/A
 - Version N/A

**Additional context**
There are some guys with the same problem.
#1590 
#1603

**Comment by yangyanqing** [comment]
When starting micro server on ubuntu 20.04, JWT and rsa were printed more than on win10.
```bash
$ micro server
2021-03-28 15:18:14  file=user/user.go:99 level=info Setting up keys for JWT at /home/frank/.micro/id_rsa and /home/frank/.micro/id_rsa.pub
2021-03-28 15:18:18  file=server/server.go:86 level=info Starting server
2021-03-28 15:18:18  file=server/server.go:114 level=info Registering network
```

**Comment by lambdaR** [comment]
make sure the `env` is local.
`micro env set local`

**Comment by yangyanqing** [comment]
> make sure the `env` is local.
> `micro env set local`

I'm sure the `env` was `local`. @lambdaR 

```
PS C:\Users\WS> micro login --username admin --password micro
Successfully logged in.
PS C:\Users\WS> micro services
Not authorized to perform this request
PS C:\Users\WS> micro env
* local      127.0.0.1:8081    Local running Micro Server
  platform   proxy.m3o.com     Cloud hosted Micro Platform
PS C:\Users\WS>
```

**Comment by lambdaR** [comment]
let's work on Ubuntu, what is `micro --version`? am using micro v3.2.0 on Ubuntu 20 LTS
after you logged in as admin and micro, what is `micro logs runtime | grep err` then the same for `network`, `proxy` and `auth`

**Comment by yangyanqing** [comment]
I got the micro v3.2.0 by the two command:
- `go get github.com/micro/micro/v3`
- `go get github.com/micro/micro/v3@v3.2.0`

But I can't reproduce the bug on Ubuntu now :(
1. `rm -rf ${GOPATH}/bin/micro; ~/.micro`
2. `go get github.com/micro/micro/v3`
3. `micro server`
4. `micro login --username admin --password micro`
5. `micro services` it works normally

```bash
# frank @ ubuntu in ~ [21:03:19]
$  micro login --username admin --password micro
Successfully logged in.

# frank @ ubuntu in ~ [21:03:21]
$ micro services
api
auth
broker
config
events
network
proxy
registry
runtime
server
store
```

**Comment by yangyanqing** [comment]
The micro on Win10 was still abnormal @lambdaR 

![image](https://user-images.githubusercontent.com/7357939/112753308-ac044b00-9009-11eb-91c0-a9cbf722a1ba.png)

**Comment by lambdaR** [comment]
on win10 you are still using micro v3.0.0. update to v3.2.0 and try again

**Comment by yangyanqing** [comment]
On Win10, `go get` can only download v3.0.0
```
PS D:\go\bin> go get github.com/micro/micro/v3@v3.2.0
PS D:\go\bin> micro -v
micro version v3.0.0
```

**Comment by lambdaR** [comment]
get it from here where all micro binaries --> https://github.com/micro/micro/releases/tag/v3.2.0

**Comment by yangyanqing** [comment]
> get it from here where all micro binaries --> https://github.com/micro/micro/releases/tag/v3.2.0

After replacing the micro.exe with [micro-v3.2.0-windows-amd64.zip](https://github.com/micro/micro/releases/download/v3.2.0/micro-v3.2.0-windows-amd64.zip), the problem is still there.

![image](https://user-images.githubusercontent.com/7357939/112754473-d73d6900-900e-11eb-86c6-4c4cbd32ccba.png)

**Comment by lambdaR** [comment]
did u delete the old micro folder where micro store token and other stuff? i.e. the same steps you did on Ubuntu.

**Comment by yangyanqing** [comment]
> did u delete the old micro folder where micro store token and other stuff? i.e. the same steps you did on Ubuntu.

Yes, I do. Just forgot list on the prior reply.
The first line would not be printed if `$HOME\.micro` was exist.
```
PS D:\go\bin> micro server
2021-03-28 21:43:27  file=user/user.go:99 level=info Setting up keys for JWT at C:\Users\WS\.micro\id_rsa and C:\Users\WS\.micro\id_rsa.pub
```

**Comment by lambdaR** [comment]
@asim or @crufter can provides guidance from here. this was or maybe still a known issue on Win.
@yangyanqing at least you have micro running on Ubuntu

**Comment by asim** [comment]
There are known issues with windows. We don't have the bandwidth to fix them. We welcome contributions. It's simply related to using the right package to create the filepath so it works on Linux and windows.

**Comment by yangyanqing** [comment]
Can you give me some tips for the filepath ? @asim 
I'll try to fix it.
Thanks !
