### ISSUE TITLE
Not authorized to perform this request

### ISSUE THREAD

**Issue by sssergei** [micro/micro#1749]
**Describe the bug**
I start to look Getting Started with microservice
I have message Not authorized to perform this request

**To Reproduce**

D:\go-work>micro login
Enter username: admin
Enter password:
Successfully logged in.

D:\go-work>micro services
Not authorized to perform this request

**Expected behavior**
api
auth
broker
config
events
network
proxy
registry
runtime
server
store

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [Version 89.0.4389.90 (Official Build) (64-bit)]

**Comment by xxmNIe** [comment]
I've been in a similar situation,Turn off the terminal and wait for a while 
it might work
