### ISSUE TITLE
No private IP address found, and explicit IP not provided

### ISSUE THREAD

**Issue by lovelly** [micro/micro#175]
micro won't start on our machines (that by default only have a public ip assigned, they are firewalled) since it won't bind to non-private ip's by default.

**Comment by asim** [comment]
Micro currently expects binding to a private ip. The only way around this is to explicitly specify the server address:port with --server_address flag.

**Comment by lovelly** [comment]
thanks

**Comment by ofavor** [comment]
@asim Would you please explain why add the private IP limitation?

**Comment by asim** [comment]
It's for security to avoid accidentally binding to a public address. If you want to bind to a public address explicitly set the server address.
