### ISSUE TITLE
Micro New project cant gen proto

### ISSUE THREAD

**Issue by korman** [micro/micro#1752]
**Describe the bug**

go version go1.16.3 darwin/amd64
micro version v3.2.0

**To Reproduce**
1. Exec 'Micro new someproj'
2. cd someproj
3. Exec 'make proto'
4. error

```
protoc-gen-go: invalid Go import path "proto" for "proto/microreader.proto"

The import path must contain at least one forward slash ('/') character.
```

**Desktop (please complete the following information):**
 - OS: Mac osx 

**Additional context**

I Changed 'someproj.proto' file from

```
option go_package = "proto;someproj";
```

to

```
option go_package = "./proto";
```

Build succeeded！

And then another error occurred.but that should be in another report.

**Comment by asim** [comment]
There's a fix in master for this but we'll point release soon

**Comment by korman** [comment]
> There's a fix in master for this but we'll point release soon

thx, I look forward to receiving your update
