### ISSUE TITLE
How do I connect plugins?

### ISSUE THREAD

**Issue by xshytikx** [micro/micro#1764]
I want to connect the etcd registry.
Is there an actual example of how I can connect plugins?

**Comment by crashdump** [comment]
You can find an example here [github.com/m3o/platform/profile](https://github.com/m3o/platform/blob/master/profile/platform/platform.go).

**Comment by xshytikx** [comment]
> You can find an example here [github.com/m3o/platform/profile](https://github.com/m3o/platform/blob/master/profile/platform/platform.go).
Thank you.
