### ISSUE TITLE
protoc-gen-micro: add support for proto3 optional fields

### ISSUE THREAD

**Issue by wespen** [micro/micro#1766]
protoc v3.12.0 added support for the optional annotation to proto3 (see RC: https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0-rc1)

Trying optional fields generation now errors out with:
```proto3 file that contains optional fields, but code generator protoc-gen-micro hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--micro_out```

**Comment by Lwxiang** [comment]
is there any plan to support this?

**Comment by senyast4745** [comment]
Hi guys! There are plans to resolve this issue?

**Comment by asim** [comment]
Unfortunately we don't have time to look but welcome the contribution
