### ISSUE TITLE
Vendor wont let us include the latest version of micro

### ISSUE THREAD

**Issue by clanstyles** [micro/micro#177]
Since the newer version of micro isn't tagged, we can't include it. We are only able to add in ```d8d176e6381b012ceb2c8121decd7e4e1fffee7f``` which is tagged as ```v0.11.1```

**Comment by asim** [comment]
New release 0.12.0 pushed. We need to maintain a slower release cadence, likely one release a month. So there will be times where latest source codes not match releases.
