### ISSUE TITLE
request service code 500

### ISSUE THREAD

**Issue by ganganlee** [micro/micro#1774]
http://m2.topgoer.com/%E5%BC%80%E5%A7%8B/HelloWorld.html

Refer to the case and respond to the error report

{"id":"go.micro.client","code":500,"detail":"service greeter: not found","status":"Internal Server Error"}

**Comment by 4rcherry** [comment]
First, **HelloWorld** is the Service, not the HTML file.
Second, **go-micro** is running by gRPC and API Request.

Note: For the specific problem, can u show the code and the result of error on terminal?
