### ISSUE TITLE
mkdir C:\Windows\blob-xxxxxxxxx: Access is denied.

### ISSUE THREAD

**Issue by iweixubin** [micro/micro#1775]
OS: Windows

I cannot change the permissions of the  **C:\Windows**  folder

How to change the configuration let generate files in specified folder

eg. 
C:\Windows\blob-xxxxxxxxx   →  E:\micro\blob-xxxxxxxxx
...\micro\store\blob.db           →  E:\...\micro\store\blob.db

**Comment by StoneHao** [comment]
hey,bro, How did you solve this problem? I met it, too。

**Comment by shtrih** [comment]
Same

**Comment by RNKG** [comment]
Same, any solution for this, pls help

**Comment by zenghao306** [comment]
> 

you must run the micro cmd by administrator first
