### ISSUE TITLE
micro api 500

### ISSUE THREAD

**Issue by dncmn** [micro/micro#179]
MICRO_API_HANDLER=rpc MICRO_API_NAMESPACE=go.micro.srv micro api
exec:
        http://localhost:8080/manan/user/login

{
    "id": "go.micro.client",
    "code": 500,
    "detail": "connection error: dial tcp XX.XX.X.XX:51912: connect: connection refused",
    "status": "Internal Server Error"
}

**Comment by asim** [comment]
There's not much I can help you with here's. It's stating the connection is refused. So whatever is on the other side of this thing is not allowing a connection. The assumption is thats the service with name `go.micro.srv.manan`
