### ISSUE TITLE
how to debug using vscode ?

### ISSUE THREAD

**Issue by dili-world** [micro/micro#1792]
how to debug using vscode?

**Comment by iweixubin** [comment]
i want to know too, 
if you found out,
please tell me~
thx~

**Comment by dili-world** [comment]
> i want to know too,
> if you found out,
> please tell me~
> thx~
这破框架各种问题，各种不兼容 go micro，难怪人这么少

**Comment by 4rcherry** [comment]
> how to debug using vscode?

Debug for what? Gimme a specific example?

**Comment by mettasoftgit** [comment]
go to launch.json file
and add this line

`"args":["--proxy_address=127.0.0.1:8081","--auth_id","admin" ,"--auth_secret","micro"]`

**Comment by zenghao306** [comment]
> "args":["--proxy_address=127.0.0.1:8081","--auth_id","admin" ,"--auth_secret","micro"]

where is the  launch.json?

**Comment by zenghao306** [comment]
> > i want to know too,
> > if you found out,
> > please tell me~
> > thx~
> > 这破框架各种问题，各种不兼容 go micro，难怪人这么少

确实垃圾，都不能debug，谁用谁傻逼

**Comment by zenghao306** [comment]
I found a way to debug ，you can run your service by this： go run main.go   service [yourservicename],the flag [service] and [service_name] must be，then you can debug your program.
