### ISSUE TITLE
run helloworld is bad

### ISSUE THREAD

**Issue by ZRothschild** [micro/micro#1798]
[
![1621417335(1)](https://user-images.githubusercontent.com/19706618/118792020-d667db80-b8c9-11eb-8c43-fc7fea1429e2.jpg)
](url)

**Comment by 4rcherry** [comment]
Bro, u can't run the project in GoLand by this step. Try to open **helloworld** folder in another window. And there's u can solve code problems.

Steps:
1. In the first terminal. Start **go-micro** server
`micro server`
2. In the second terminal. Login **go-micro** server
`micro login`
> Enter username: **admin**
> Enter password: **micro**
3. Generate Protocol Buffer file
`make proto`
4. Run **helloworld** service
`micro run .`
5. Check Services status
`micro status`
If the **STATUS** field on the **helloworld** service show **running**, the project/service is running and successful. If the service show an **error**, may u have got the problem by your code?. Check your code again, solve, and then run `micro update .`
6. Check on http API on port **:8080** so you can just curl / put on browser address bar your service like so
`curl "http://localhost:8080/helloworld?name=YourName"`
