### ISSUE TITLE
micro: command not found

### ISSUE THREAD

**Issue by Alewex** [micro/micro#182]
I tried installing the micro CLI tool with `go get -u github.com/micro/micro` and after it finishes downloading and do `micro` in the terminal it just returns with `-bash: micro: command not found`.

I'm on Mac.

**Comment by asim** [comment]
This is a go setup issue. Your $GOPATH/bin directory need to be in the PATH.

**Comment by mobintmu** [comment]
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)
