### ISSUE TITLE
can you provide some example of using etcd in micro/v3

### ISSUE THREAD

**Issue by lawler61** [micro/micro#1823]
hi, i looked through the docs and did not found the usage of etcd

and could you please provide some usage for this

i am new for the micro services and go lang, thanks

**Comment by asim** [comment]
See https://github.com/m3o/platform/blob/master/profile/platform/platform.go

There is otherwise no support for this project

**Comment by lawler61** [comment]
> See https://github.com/m3o/platform/blob/master/profile/platform/platform.go
> 
> There is otherwise no support for this project

got it, thanks
