### ISSUE TITLE
[Question] Kubernetes ARM support?

### ISSUE THREAD

**Issue by AuditeMarlow** [micro/micro#1825]
First of all, huge thanks to the Micro team for the incredible work has done and the amazing effort they put in maintaining the Micro project along with all of the issue support they offer. I personally think Micro is a fanstastic idea and I hope it will get some much deserved recognition in the cloud native community.

Currently the Micro v3 binary release supports ARM and ARM64 builds for macOS, Linux and Windows. Will there be support for ARM and ARM64 for the Micro v3 Docker images as well? I'd really enjoy running Micro on my ARM64 k3s cluster. If there are no plans for this, perhaps you can point me in the right direction in order for me to contribute?

**Comment by asim** [comment]
There's no current plans to create one but happy to accept a PR. See .github/workflows/docker.yml and the top level Dockefile/Makefile

**Comment by AuditeMarlow** [comment]
Thanks! I'm looking into it as we speak, this can be tracked [here](https://github.com/micro/micro/pull/1826). I was able to get multiarch Docker image builds going in the `Makefile` using `docker buildx` pretty easily so far.

I see the project uses [elgohr/Publish-Docker-Github-Action](https://github.com/elgohr/Publish-Docker-Github-Action) to publish new Docker images through the CI. This Action does not yet support multiarch options, as tracked [here](https://github.com/elgohr/Publish-Docker-Github-Action/issues/106). Would it be a viable option to migrate to [docker/build-push-action](https://github.com/docker/build-push-action)?

**Comment by asim** [comment]
Yea it's fine to move to that if it works

**Comment by AuditeMarlow** [comment]
Alright, I'll look at migrating the Action this week. The `micro/cell` Docker image will also have to be built for ARM64, I'll look into that soon as well.

**Comment by asim** [comment]
The issue there will actually be when and how the service is run using the cell image. Some form of arch detection will be needed

**Comment by AuditeMarlow** [comment]
I think that could easily be solved by also building a multiarch Docker image for the `micro/cell` image.

**Comment by asim** [comment]
Yea you might be right. I need to see it in action

**Comment by AuditeMarlow** [comment]
I'm using the same approach to building a multiarch `micro/cells` Docker image as I've used before with the `micro/micro` Docker image, as seen [here](https://github.com/micro/micro/pull/1826/commits/604c11705e8c524e8005cd5cdcbbf31b6e8c3a99).

In order to migrate the GitHub Action from [elgohr/Publish-Docker-Github-Action](https://github.com/elgohr/Publish-Docker-Github-Action) to [docker/build-push-action](https://github.com/docker/build-push-action) I need to understand what the current Action does. Is it just pushing a new `micro/micro:latest` Docker image, or does it also push other tags? I'm having difficulty figuring this out myself as I'm not familiar with this CI approach.

**Comment by AuditeMarlow** [comment]
Example and working multiarch images can be found here:

- [micro](https://hub.docker.com/r/auditemarlow/micro)
- [cells](https://hub.docker.com/r/auditemarlow/cells)

**Comment by AuditeMarlow** [comment]
I've migrated the Docker GitHub Actions workflow as per 6383d0d479eae6f935d5e06d0758d1a7bc958b39. I've also fixed the "Push cells" GitHub Actions workflow as it was broken before. I've been building and testing my own `micro` and `cells` images, as mentioned above, and seem to be working fine. I think #1826 is now ready for review.

**Comment by asim** [comment]
The team is back on Monday so we'll review then. Thanks for the contribution.
