### ISSUE TITLE
Random request failures - code: 500 connect: connection refused

### ISSUE THREAD

**Issue by abhilash-wasphi** [micro/micro#183]
This is strange, because the error doesn't happen in all requests. I have written a simple service go.micro.srv.books. When calling this service from web ui (the one that is present at localhost:8082), I see failures randomly. Every other or so request fails with the error above. Just to be sure I wasn't doing anything wrong, I also cloned the booking example here - https://github.com/micro/examples/tree/master/booking, deployed locally on docker following the guide, and tested as mentioned using curl. The same problem. Every alternate or so request fails with this error
```javascript
{
  "id": "go.micro.client",
  "code": 500,
  "detail": "connection error: dial tcp 172.17.0.7:44255: connect: connection refused",
  "status": "Internal Server Error"
}
```

Not sure what's wrong, but seems the registry loses track what services are currently available and where. Would be happy to provide any more info needed on the issue. Thanks for the awesome library.

**Comment by asim** [comment]
If a service does not deregister cleanly then it remains in service discovery, this causes request failures. To eliminate this issue you need to set register ttl and interval on your services so the entries expire after a period of time. You should also look to implement request retries so it cycles through to another node.
