### ISSUE TITLE
micro new GOPATH splitting in windows 

### ISSUE THREAD

**Issue by raafat5200** [micro/micro#185]
Hi,
      I'm using windows and have two paths in GOPATH separated with ";".  Command "micro new {MyPath}" adds {MyPath} to entire GOPATH which leads to failure. After some research in your code, I found out this condition in "new/new.go",

        // attempt to split path if not windows
	if runtime.GOOS != "windows" {
		goPath = strings.Split(goPath, ":")[0]
	}

By adding a handling for windows case, the condition became as following,

// attempt to split path if not windows
	if runtime.GOOS != "windows" {
		goPath = strings.Split(goPath, ":")[0]
	} else {
		goPath = strings.Split(goPath, ";")[0]
	}

This resolves my problem. 

What do you think?

Regards

**Comment by asim** [comment]
Is this the case for all windows GOPATHS? Are they semi-colon separated rather than colon?

**Comment by raafat5200** [comment]
Yes. I used to for long time. Please refer to this thread for confirmation.
https://stackoverflow.com/questions/36017724/can-i-have-multiple-gopath-directories

**Comment by asim** [comment]
Ok well feel free to PR a fix

**Comment by asim** [comment]
Ok change made. Closing issue.
