### ISSUE TITLE
RPC method was execute two times

### ISSUE THREAD

**Issue by saisiyun** [micro/micro#186]
RPC method was executes two times using Micro Api

`
func (tc *TestRpc) Test(ctx context.Context, in *proto.ApiIn, out *proto.ApiOut) error {
    fmt.Println("********** api ************")
    ...
 }
`

call http://localhost:8080/testRpc/test
`********** api ************
`
`********** api ************
`

**Comment by asim** [comment]
Are you accessing it in a browser? Because chrome is known to duplicate requests.

**Comment by asim** [comment]
Why is it returning an error? The client is configured to retry in the event of an error.

**Comment by saisiyun** [comment]
do you mean this code will be retried?

`return errors.BadRequest("go.micro.api.greeter", "Name cannot be blank")`

**Comment by saisiyun** [comment]
Can I configure something to avoid this?

**Comment by saisiyun** [comment]
But this method will be called only one time if I tested by RPC client. Is it a issue about Micro Api?

**Comment by asim** [comment]
Yes this will be retried which is really a flaw in the retry mechanism. We need to change from having retry always to checking for errors https://github.com/micro/go-micro/blob/master/client/retry.go#L11. This highlights a wider requirement to make the default function public and add a new function RetryOnError or something similar

**Comment by saisiyun** [comment]
Thanks for quick feedback. Have a way to resolve my question now? It's very urgent for me.

**Comment by asim** [comment]
I've merged a fix in the go-micro codebase which will stop this now. It will only retry on timeout or internal server error which is codes 408 and 500.
