### ISSUE TITLE
when have more api.service (>1) ,the micro api will can not find the api.service

### ISSUE THREAD

**Issue by super-organism** [micro/micro#189]
I have three api.service "go.micro.api.A, go.micro.api.B, go.micro.api.C,"
When I went to proxy then by "micro api --handler==http",I get some error, the http code is 404,the micro api will can not find these api.services.
so i find in the source and i find the code in the picture;
![image](https://user-images.githubusercontent.com/29723072/43523458-051d1218-95cf-11e8-85ac-161b3ffb9cee.png)
I find the code  in "micro/go-api/router/router.go"  , the method  "Route" 
I think  the code in the picture is the bug's  reason  
I have delete the code ,and i fixed it, I went to know that is there a better way to do it？

**Comment by asim** [comment]
Please provide a repeatable test case rather than a picture of code.

**Comment by super-organism** [comment]
this is a repeatable test case  ====>   https://github.com/super-organism/restapitest.git
you can test it

**Comment by asim** [comment]
This is a bug related to this change https://github.com/micro/go-web/commit/6851189894814f1bb1d4d4f328c58d42a25225f1 in go-web. Go-web services register an endpoint but this endpoint is not unique, it's "/" which basically ends up randomly reconfiguring the micro api to route to any of the services. We need to remove this automatic association for go-web.

**Comment by asim** [comment]
Now fixed. Thanks for reporting. `go get -u github.com/micro/go-web`
