### ISSUE TITLE
 C:\WINDOWS\micro\store\blob.db

### ISSUE THREAD

**Issue by zenghao306** [micro/micro#1893]
when i run the common [micro run .] to run a service at the windows platform,a problem like this:
Rpc error: code = Unknown desc = Error writing source to blob store: open C:\WINDOWS\micro\store\blob.db: The system cannot find the path specified. 
can you tell me how to solve this problem？

**Comment by cz321** [comment]
me too

**Comment by olderyi** [comment]
me too
