### ISSUE TITLE
how can call a repeated request message 

### ISSUE THREAD

**Issue by zenghao306** [micro/micro#1894]
When i have a rpc method just like this:
rpc GetAllAccount(Request) returns (Response) {}

message Request {
	repeated int64 id = 1;
}

I call this method like this:
micro call micro_v3 GetAllAccount --id=[100,101]

the response message is:
Error creating request invalid character '-' in numeric literal

can you tell me how to call this method by micro command?

**Comment by goldsky** [comment]
try
```
message Request {
    string ids = 1;
}
```

then call `micro micro_v3 GetAllAccount --ids=100,101`, then split the string inside your method.
