### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [micro/micro#190]
Greeting, Micro team.  I am a graphic designer and an open source enthusiast. I am interested in designing a logo for this project, and also i've designed a logo. 
![micro](https://user-images.githubusercontent.com/36124339/43632659-fe19b7f6-9730-11e8-8934-2dcca4244f9b.png)
If you need anything change pls let me know. Thank you.
Best Regard, Mirza Zulfan

**Comment by asim** [comment]
Hey. Very cool! Thanks very much for doing this. I want to take the time to think about it before getting back to you. I want to do the branding/design for everything in one go rather than just update the logo.

**Comment by mirzazulfan** [comment]
Thanks for your response sir. :) ,, if you need to change, i'll fix it. Or if you have an idea please share with me, it would be better for me. Thank you @as

**Comment by asim** [comment]
Thanks. I think we're going to hold off for the moment. I will reach back out when ready to update.
