### ISSUE TITLE
Can we use http requests to get responses from server without setting `mirco api handler`  or running a http gateway?

### ISSUE THREAD

**Issue by zuiaiqun** [micro/micro#191]
In the example below, we have to set the api handler to receive http requests:
`
MICRO_API_HANDLER=rpc \
MICRO_API_NAMESPACE=go.micro.srv \ 
micro api
Some info:

MICRO_API_HANDLER sets the http handler
MICRO_API_NAMESPACE sets the service namespace

curl -XPOST -H 'Content-Type: application/json' -d '{"name": "John"}' http://localhost:8080/example/call
Output
{"msg":"Hello John"}
`
And in the `greeter` example, we have to start a  `go.micro.api.greeter ` service.
I'm wondering if there is a way to start only the backend server to receive rpc calls and http calls?

**Comment by asim** [comment]
This might be the example you're looking for https://github.com/micro/examples/tree/master/api/rpc

**Comment by asim** [comment]
You can specify this in code with go-api https://github.com/micro/go-api
