### ISSUE TITLE
Authentication and Authorization?

### ISSUE THREAD

**Issue by agus7fauzi** [micro/micro#1913]
#ask can someone give me an idea to implement authentication and authorization in micro?

**Comment by asim** [comment]
https://micro.dev/reference#auth

**Comment by agus7fauzi** [comment]
hi thanks for the answer. but I still don't understand how to integrate the auth service with existing users in my mongodb database, is there an existing example? thank you

**Comment by asim** [comment]
Not sure that will work. Micro has its own Auth and account system. If you need Auth for your users you have to build that yourself

**Comment by agus7fauzi** [comment]
ok looks like i need to modify auth service and api service,

**Comment by agus7fauzi** [comment]
and can i contribute by adding a micro feature for authentication and authorization which is integrated with my own database for example mongodb?

**Comment by asim** [comment]
I'm not really sure what that means so you'll have to explain what that integration would be. It would have to be some sort of plugin as opposed to direct dependency.

**Comment by agus7fauzi** [comment]
I think we need to implement some kind of plugin in the auth service section, can we do that?

**Comment by asim** [comment]
You can replace the Auth implementation in your plugin, see other plugins for examples
