### ISSUE TITLE
the header "X-Requested-With" not in the "Access-Control-Allow-Headers"

### ISSUE THREAD

**Issue by super-organism** [micro/micro#192]
i have a api.service want to sand some data to service ,but the header "X-Requested-With" not in the "Access-Control-Allow-Headers" 
i add the header to the source and rebuild the micro,but i have a question?
why not  have a api cmd can set the headers ?

**Comment by asim** [comment]
We haven't provided a way to set it because we want to make the api extensible and allow users to define any extra functionality themselves. You can use the cors plugin to do this https://github.com/micro/go-plugins/tree/master/micro/cors
