### ISSUE TITLE
I feel so sad for no api-gateway in v3!

### ISSUE THREAD

**Issue by cgcodeboy** [micro/micro#1923]
Just as the title, can the gateway be added to the v3 version?

**Comment by asim** [comment]
I'm not sure what you mean, Micro v3 does contain an api. Run `micro server` and its present on `localhost:8080`. If you're referring to https://github.com/asim/go-micro, then yes, Go Micro is solely a framework. Given the fact that people have adopted gRPC tooling and there is a gRPC gateway, it probably fits better with Go Micro.
