### ISSUE TITLE
How to create Custom API Gateway in Micro V3?

### ISSUE THREAD

**Issue by agus7fauzi** [micro/micro#1925]
### Discussed in https://github.com/micro/micro/discussions/1924

<div type='discussions-op-text'>

<sup>Originally posted by **agus7fauzi** March 21, 2022</sup>
Please help me,
I'm having trouble creating a custom api gateway using a plugin based on that article https://developpaper.com/go-micro-service-go-micro-16-custom-micro-api-gateway-middleware-micro-plug-in-learning/ as I expected for my application, but the problem is the code really doesn't work on my Micro V3, does anyone know how to use a plugin in Micro V3 especially for API Gateway?</div>

**Comment by asim** [comment]
The article mentions V2 not V3. You cannot customise in V3.

**Comment by agus7fauzi** [comment]
thanks for the answer sir, but is there any solution for that sir?

**Comment by asim** [comment]
Use V2 as the article said or use something else. We're not supporting customisation in V3.

**Comment by agus7fauzi** [comment]
for all services using V2 or for the api gateway only, sir?

**Comment by asim** [comment]
Everything. Micro V3 does not support Go Micro. V3 diverges from V2. So my advice is to use V2 or something like Kratos or Go Zero.

**Comment by agus7fauzi** [comment]
ok sir thanks for the suggestion i decided to use your code micro v2.9.3 and customized it for me to upload on my company github organization.

**Comment by agus7fauzi** [comment]
hi sir i'm currently using micro version 2 which I modified at https://github.com/ebelanja/go-micro, my main purpose of modifying is to fix bugs/dependencies and optimize the source code so that it can use the latest golang. is this ok sir?

**Comment by asim** [comment]
It's Apache 2.0 licensed, you can do whatever you want

**Comment by asim** [comment]
The original project still exists at https://github.com/asim/go-micro. It still exists as a standalone project. If you want to contribute an api gateway to it you can. There's a cli and dashboard in the cmd directory. You can add it there.

**Comment by agus7fauzi** [comment]
> It's Apache 2.0 licensed, you can do whatever you want

does that include free to rename framework and and change license pack?

**Comment by asim** [comment]
Please read the terms of the Apache 2.0 license. You must continue to attribute credit to the original author and project in your license and project. You cannot take the years of work of someone and then completely rename without attribution to the original author.

**Comment by agus7fauzi** [comment]
ok sir, in conclusion you can change the name of the framework, as long as it includes information about the original author?

**Comment by asim** [comment]
Yes
