### ISSUE TITLE
github.com/micro/go-plugins/broker/kafka requires wants /micro/go-micro which is not available

### ISSUE THREAD

**Issue by umishra21** [micro/micro#1929]
```
go: github.com/micro/go-plugins/broker/kafka@v0.0.0-20200119172437-4fe21aa238fd requires
	github.com/micro/go-micro@v1.18.0 requires
	github.com/micro/protoc-gen-micro@v1.0.0: reading github.com/micro/protoc-gen-micro/go.mod at revision v1.0.0: unknown revision v1.0.0
make: *** [local] Error 1
```

I am upgrading go-micro to v4 but getting error for go-plugins as this also requires the older version. 
How can I resolve this? Would be great if you can help me with this.

Thanks

**Comment by andthereitgoes** [comment]
github.com/micro/go-plugins has disappeared. Does anyone know why?

**Comment by umishra21** [comment]
The repository has been deleted. Either upgrade it to  asim/go-micro or try
to use the cached data if you have. FYI - we tried upgrading but there have
been some breaking changes the we couldn’t identify.
