### ISSUE TITLE
Micro Not Starting properly on windows

### ISSUE THREAD

**Issue by a0v0** [micro/micro#1930]
![image](https://user-images.githubusercontent.com/62926341/167878245-f9847cef-8029-4c13-a295-530d744028ab.png)
![image](https://user-images.githubusercontent.com/62926341/167878238-95111464-5312-449b-a173-6f265c28c4fb.png)

**Comment by a0v0** [comment]
@asim please help

**Comment by a0v0** [comment]
will you check it out tomorror?

**Comment by asim** [comment]
Nope

**Comment by a0v0** [comment]
Any updates?

**Comment by asim** [comment]
As mentioned I do not have the time to fix this issue. If you are unable to fix it yourself please don't use the project.

**Comment by a0v0** [comment]
More logs

![ezgif-3-04bc5ff9cb](https://user-images.githubusercontent.com/62926341/168572204-73a78252-a86a-471c-87ac-6b3bd54834b1.gif)

**Comment by mefloresz** [comment]
try using the Windows subsystem for Linux and install everything here

**Comment by a0v0** [comment]
fixed by using latest version of micro
