### ISSUE TITLE
[BUG] Account not found with this ID

### ISSUE THREAD

**Issue by mefloresz** [micro/micro#1936]
Hi Guys i have a problem when i try to conect with micro using the admin credentials

micro login
Enter username: admin
Enter password:
Account not found with this ID

i try to create another account with Admin profile but the Micro server needs an account for this ...

micro login
Enter username: admin
Enter password:
Account not found with this ID

micro auth create account --scopes=admin mario
Error creating account: {"id":"auth.Auth.Generate","code":401,"detail":"an account is required","status":"Unauthorized"}

Go version : v1.17.10
Micro version v3.5.0

SO: WSL ( windows subsystem Linux) V 20.04

**Comment by asim** [comment]
Windows support is lacking. It's not clear whether it works on this system.

**Comment by mefloresz** [comment]
My solution was Open the Cmd as Admin and the Jwt tokens are setting
![image](https://user-images.githubusercontent.com/77681202/169412135-c7a7ca4b-551f-4fef-ad26-f06a916a4c14.png)
![image](https://user-images.githubusercontent.com/77681202/169412163-38723701-b6fe-4a0b-b544-15e8ec025eb7.png)
