### ISSUE TITLE
Unable to find example of writing Java/Python service on Micro platform

### ISSUE THREAD

**Issue by roynilanjan** [micro/micro#1938]
All the examples I find is in Golang. Can you share examples/docs for writing services in Java/Python on Micro platform?

**Comment by roynilanjan** [comment]
Thanks Asim. Do you have any future plan for supporting  languages other than Go ?

**Comment by asim** [comment]
Only as clients, not for service development

**Comment by roynilanjan** [comment]
ok...however just curious to know about your thought process behind keeping Micro platform confined to Go only

**Comment by asim** [comment]
I believe Go is the most appropriate language for microservices and cloud based development. That's based on my personal experience and what I'm also seeing in the industry. Multi-language is difficult to support and it creates different performance characteristics across services. I think Python and Java serve their place but not in the same place as a microsevices or API driven architecture. So it's better than Python has its frameworks and Java has its. Multi-language clients are one potential option, but we would not support the running of services written in those languages aka this is not just a PaaS. To be a PaaS for multiple languages would require a lot of rearchitecture and would not fit the purpose of Micro. Micro is like Android. An operating system with a single language framework. We may support running webassembly in future and that might open the door to other things.

**Comment by roynilanjan** [comment]
Thanks Asim
