### ISSUE TITLE
Example of how to get micro api working on Kubernetes 

### ISSUE THREAD

**Issue by mgyong** [micro/micro#194]
Hi,
I was hoping if there is a proper example showing how to deploy micro api on Kubernetes and acting as API gateway for go-micro service on Kubernetes?

**Comment by asim** [comment]
Look at the kubernetes repo

**Comment by mgyong** [comment]
The kubernetes repo is using kubernetes as service registry. I am trying to use consul as service registry and the deployment file settings for using external consul for service registry is unclear to me. Was hoping to get example using external consul as service registry and how it affects deployment files

**Comment by asim** [comment]
Set the `--registry_address` flag or `MICRO_REGISTRY_ADDRESS` env var to the location of consul for any of your micro apps.
