### ISSUE TITLE
micro api getting error  'rpc call: unable to send response: write tcp ... write: broken pipe' when benchmarking

### ISSUE THREAD

**Issue by ahmadnurus** [micro/micro#195]
i have proxy api using net/http that routes to rpc service. when benchmarking, i am getting error 'rpc call: unable to send response: write tcp ... write: broken pipe' on my rpc service.

**Comment by asim** [comment]
I'm sorry I can't help you with net/http usage, we have our own micro api for proxying http requests.

**Comment by ahmadnurus** [comment]
i will try this, thanks for your response
