### ISSUE TITLE
install v3 command error micro: not a directory

### ISSUE THREAD

**Issue by yb19890724** [micro/micro#1951]
```
> micro -h

 file=user/user.go:31 level=fatal mkdir /Users/ice/.micro: not a directory
```

**Comment by asim** [comment]
Assuming you have some other tool called micro installed that creates a dot micro file. So you have to remove that.

**Comment by yb19890724** [comment]
@asim 
no relaition micro file 
![image](https://user-images.githubusercontent.com/21005459/176858721-b09e305c-d786-4d0d-8f65-91344fbc3f0c.png)

**Comment by asim** [comment]
What platform is it running on?

If the .micro file already exists then we can't create the directory. If /Users/ice is not a directory again we can't create the directory.

**Comment by yb19890724** [comment]
macOS m1
