### ISSUE TITLE
What's the relationship of micro and go-micro

### ISSUE THREAD

**Issue by kuchaguangjie** [micro/micro#1957]
What's the relationship of this project and https://github.com/asim/go-micro?
Which should I use, if I start a new project?

**Comment by kuchaguangjie** [comment]
I remember https://github.com/asim/go-micro was achived, but seems it's active again, so a bit confused abou the situation.

**Comment by asim** [comment]
go-micro is a standalone Go framework, its pluggable, you can write services with it. Micro is a platform (PaaS)

**Comment by kuchaguangjie** [comment]
Thanks, but that's a bit abstract. Is there a article or doc for this specific question?

**Comment by asim** [comment]
https://micro.dev/faq#whats-the-difference-between-micro-and-go-micro
