### ISSUE TITLE
undefined: client.Streamer

### ISSUE THREAD

**Issue by wangzhen625** [micro/micro#197]
I use `micro new` command to generate an example template as the blog said, everything is ok until i execute `go run main.go`. It occurs a error of  `proto/example/example.micro.go:103:9: undefined: client.Streamer`, and the source code in github.com/micro/go-micro/client only defined Stream interface. So i change client.Streamer to client.Stream in generate code by hand, then the program can run. Is something wrong with my protobuf version or is micro new command's bug?

**Comment by asim** [comment]
go get -u github.com/micro/protoc-gen-micro

Ensure you are using this tool rather than the deprecated protobuf repo.
