### ISSUE TITLE
Rpc error: code = Unknown desc = Error writing source to blob store: open C:\Windows\micro\store\blob.db: Access is denied.

### ISSUE THREAD

**Issue by Rubyg1602** [micro/micro#1971]
**Describe the bug**
Getting Rpc error: code = Unknown desc = Error writing source to blob store: open C:\Windows\micro\store\blob.db: Access is denied. 

OS: Windows 10

I have installed micro v3
Executed following commands
>micro server
>micro login
with admin & micro credentials

logged in successfully

created sample application using
>micro new helloworld
>make init
>go mod vendor
>make proto
>micro run .

 Getting the error as mentioned in the title.
 
 Please help me in that,
 Thanks!

**Comment by asim** [comment]
run in powershell as root
