### ISSUE TITLE
How can I scale out micro api to multiple instances in Docker Swarm?

### ISSUE THREAD

**Issue by TechMaster** [micro/micro#198]
Our team have been using go micro in a complex web app. I put micro api in front of many microservices.

Front end web app is Vue.js - NUXT that makes REST request to micro api. Micro api then translate to GRPC and forward to target microservice.

I am very worried when number of concurrent requests increases, there will be bottle neck at micro api.

Question: How can I scale out micro api to multiple instances in Docker Swarm?

**Comment by asim** [comment]
Well you'd need to run multiple instances of the micro api and load balance it in some way. Docker swarm has the concept of a service which is load balanced. You can make the micro api a docker swarm service, run multiple replicas and then use it as the entry point for your requests.
