### ISSUE TITLE
micro new helloworld,but this error occurs，I don't know how to solve it

### ISSUE THREAD

**Issue by guolianyu** [micro/micro#1980]
2022-11-03 23:55:02  file=cmd/cmd.go:625 level=fatal Error setting up auth: {"id":"go.micro.client","code":500,"detail":"{\"id\":\"go.micro.client\",\"code\":500,\"detail\":\"service 
auth: route not found\",\"status\":\"Internal Server Error\"}","status":"Internal Server Error"}

**Comment by asim** [comment]
When does the error occur?

**Comment by asim** [comment]
English please

**Comment by LouieGuo** [comment]
windows 10，go 1.19，micro v3

**Comment by LouieGuo** [comment]
micro server ok，micro login ok，but helloworld can't run，why？，I think it's hard to use

**Comment by LouieGuo** [comment]
You should not have tested the framework in the windows environment，I guess your computer is mac,or OS is linux

**Comment by asim** [comment]
I'm not a windows user. If you'd like to contribute fixes for Windows please PR them

**Comment by dawesi** [comment]
FYI : You can test with dev environment releases of windows (for free) for testings on VM engines :  vmware/hyper-v/virtualbox/parallels here : https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

These are fully featured enterprise evaluation versions then just use choco to install any apps/packages ( https://chocolatey.org/install )

**Comment by guolianyu** [comment]
已经收到您的来信，我会尽快回复。

**Comment by guolianyu** [comment]
已经收到您的来信，我会尽快回复。
