### ISSUE TITLE
Request failures: Code 500 connect: no route to host

### ISSUE THREAD

**Issue by minhthuy30197** [micro/micro#200]
I have got an error when using go micro. Every request failed with this error. How can I fix it?

`{
    "id": "go.micro.client",
    "code": 500,
    "detail": "connection error: dial tcp 10.0.0.39:40541: connect: no route to host",
    "status": "Internal Server Error"
}`

**Comment by asim** [comment]
This seems related to your networking setup. 10.0.0.39 is not a routable ip by the underlying host.
