### ISSUE TITLE
Can I combine service layer and api layer in micro api?

### ISSUE THREAD

**Issue by xbox1994** [micro/micro#202]
Link: https://github.com/micro/micro/tree/master/api

The picture shows a request from `micro api` to `api layer` to `service layer` in the README. Can I put `service layer` logic into `api layer`? I want `api layer` can support rest(for frontend call) and grpc(for internal call) so I can avoid to create and manage almost twice the server node.

**Comment by asim** [comment]
The micro api supports multiple request handlers. If you want to query rpc from the api you can do that. See the examples repo. https://github.com/micro/examples/tree/master/api

**Comment by xbox1994** [comment]
Maybe I my question is not clear. I want to put it another way.

I want to remove order service and customer service because I want to implement all the core functionality in corresponding api layer. Then I can call order api in customer api. Is it possible?

**Comment by asim** [comment]
It's programming. You can do whatever you want. The necessary tools are there to create whatever orchestration flow you want.

**Comment by xbox1994** [comment]
Thanks for your reply! It helps me a lot.
