### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by GhostWalkers** [micro/micro#2029]
I saw an already closed topic, but I have the same error, the server cannot connect and leaves a timeout, when I try to login, it gives Context deadline exceeded
![image](https://user-images.githubusercontent.com/100309290/229152375-fb6360d1-c1f5-4390-a8fa-ee67753a7ddd.png)
![image](https://user-images.githubusercontent.com/100309290/229152416-def5fd6a-3263-47af-8628-5d40ce2c2101.png)
I don't think it's a problem with the firewall because it's disabled
who knows the solution to the problem, please help :)

version: v3.16.0
platform: windows

**Comment by asim** [comment]
Run powershell as admin

**Comment by asim** [comment]
Sorry I don't have access to a windows machine to fix
