### ISSUE TITLE
Can I use go1.11.1 mod compile micro？

### ISSUE THREAD

**Issue by luanhailiang** [micro/micro#203]
**I use go 1.11.1**

git clone https://github.com/micro/micro.git
cd micro
go mod init
go mod tidy
go build

**and it throw this error**

PS D:\gopath\micro> go build
github.com/micro/go-bot/input/slack
C:\Users\luan\go\pkg\mod\github.com\micro\go-bot@v0.0.0-20181008074751-2a941fc0fbe4\input\slack\slack.go:112:28: undefined: slack.OptionDebug
github.com/micro/micro/internal/handler
internal\handler\meta.go:35:7: undefined: web.Handler
internal\handler\meta.go:38:16: undefined: "github.com/micro/go-api/handler/http".Handler
internal\handler\meta.go:41:7: undefined: rpc.Handler
internal\handler\meta.go:44:7: undefined: event.Handler
internal\handler\meta.go:50:7: undefined: "github.com/micro/go-api/handler/api".Handler

**Comment by asim** [comment]
Have you updated your dependencies?

**Comment by luanhailiang** [comment]
I use go get -v throw the same error
![7f dg8 esim28v_o1dm_ we](https://user-images.githubusercontent.com/1848784/46776923-455b1c00-cd40-11e8-89ce-1acc35a98dc4.png)

**Comment by luanhailiang** [comment]
go mod use github.com/nlopes/slack  0.4.0 
at this version function OptionDebug  not exist

**Comment by luanhailiang** [comment]
I update to master branch it build success
`go get github.com/nlopes/slack@master`

**Comment by luanhailiang** [comment]
go mod will use the latest tags version as default if not exist tags then use master branch as default

**Comment by andrearagao** [comment]
I'm getting the same error - has anyone figured out how to fix this?
