### ISSUE TITLE
server.NewServer use http2 some bug

### ISSUE THREAD

**Issue by doraHope** [micro/micro#2030]
**Describe the bug**
i use http2 protocol start a server. but i meet some wrong.
#1 response miss content-length
#2 server conn will close before reply response when get a data frame with end flag. 
#3 some bad code. 
example:
func: server.rpcServer.ServeConn:
/**
go func(id string, psock *socket.Socket) {
    wg.Add(1)
    // add to the waitgroup
    ......
}
*/

**To Reproduce**
Server Start Code:
/**
func main() {
	cert, err := tls.LoadX509KeyPair(`<pub>`, `<key>`)
	if err != nil {
		log.Printf(`key pair failed, error %v`, err)
		return
	}
	srv := server.NewServer(server.Name(`testABC`), server.Transport(transport.NewTransport(transport.TLSConfig(&tls.Config{
		InsecureSkipVerify: true,
		Certificates:       []tls.Certificate{cert},
		NextProtos: []string{`h2`, `http/1.1`},
	}), transport.Secure(true))))
	srv.Init(server.Wait(nil))
	err = srv.Handle(srv.NewHandler(&HelloServer{}))
	if err != nil {
		log.Printf("new handler failed, error %v", err)
		return
	}
	err = srv.Start()
	if err != nil {
		log.Printf("go-micro start failed")
	}

	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)

	select {
	// wait on kill signal
	case <-ch:
	// wait on context cancel
	case <-srv.Options().Context.Done():

	}

	srv.Stop()
}
*/

request server example:

curl request:
 curl --http2 --keepalive-time 60 --cacert <ca> -iv -H 'Content-Type: application/json' \
-H 'Micro-Service: HelloServer' \
-H 'Micro-Method: Call' \
-H 'Micro-Endpoint: HelloServer.Call' \
--data-raw '{}' \
-H 'Connection: keep-alive' \
https://addr/

curl response:
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
HTTP/2 200 
< content-type: application/json
content-type: application/json
< date: Sun, 02 Apr 2023 08:47:55 GMT
date: Sun, 02 Apr 2023 08:47:55 GMT

< 
{"A":"hello world"}
* Connection #0 to host dc.com left intact

**Expected behavior**
#1 when receive frame data with end flag, close conn after reply response.
#2 bad code, may cause response can not reply.
#3 http2 response header should have 'Content-Length'.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser curl/7.84.0
 - Version 13.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by asim** [comment]
This a very unorthodox usage, sorry closing
