### ISSUE TITLE
'micro' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by FarhangAmaji** [micro/micro#2032]
I have tried to install go micro with first `go install github.com/micro/micro/v3@latest` then with `powershell -Command "iwr -useb https://raw.githubusercontent.com/micro/micro/master/scripts/install.ps1 | iex"` and it seems they have worked successfully but I get `'micro' is not recognized as an internal or external command, operable program or batch file.` when I do `micro server` or `micro new helloworld`.
the go is installed in `C:\Program Files\Go` and this path is `environmental variables`. also I should say there is no `micro` file in that location.

**Comment by asim** [comment]
Sorry windows is not supported at this time
