### ISSUE TITLE
Problems connecting with Windows

### ISSUE THREAD

**Issue by lonnietc** [micro/micro#2037]
Hello All,

I am very new to Micro, but think that it may hold promise for use in a highly scalable P2P application that I am working on since I really like what I have read so far although not sure what the difference between the "Micro" and "Go-Micro" repositories are at this moment.

Currently, I tried to follow a blog post "Building a global services network using Go, QUIC and Micro" (https://blog.gopheracademy.com/advent-2019/building-a-microservices-network/) [Dated 2019] to initial get up and running after compiling with Golang v1.19.3 on a Windows 10 (x64) which produced the micro.exe.

The blog said to connect with "micro.exe --peer" but there is no "peer" option and I do not know how to register and connect with micro.exe at this point?

Also, I am interested to know how well the micro network scales in addition to wanting to learn how to set up a private micro network for some development and testing purposes initially.

PS) I did find the Micro Discord Channel but there does not seem to be much activity.

Any help on these would be truly appreciated.
Best Regards and have a good day.

**Comment by asim** [comment]
Apologies for the delay here. Everything you're reading now is quite outdated. Go Micro and Micro split at v3. I'm working on combining them but it will be some time. The most up to date docs is likely https://micro.dev/docs and you can look at services in https://github.com/micro/services. Sorry I don't have more info than that.
