### ISSUE TITLE
How to write KV to a table.

### ISSUE THREAD

**Issue by jaijainayaka** [micro/micro#2043]
records, err := store.Read("mykey", func(r *store.ReadOptions) {
		r.Table = "example"
	})

How to do the same, write, with a table name ? 

CLI, command does the work. 
But, unable to perform the same programmatically.

----------------------------------------------------------------
store/store.go:

// Store is a data storage interface
type Store interface {
      // Read records
      func Read(key string, opts ...ReadOption) ([]*Record, error) {
	      // execute the query
	      return DefaultStore.Read(key, opts...)
      }
      // Write writes a record to the store, and returns an error if the record was not written.
	      Write(r *Record, opts ...WriteOption) error
}

// Read records
func Read(key string, opts ...ReadOption) ([]*Record, error) {
	// execute the query
	return DefaultStore.Read(key, opts...)
}
// Write a record to the store
func Write(r *Record) error {
	return DefaultStore.Write(r)
}

missing - opts ...WriteOption, on Write func. 

and,
----------------------------------------------------------------
store/options.go

// WriteTo the database and table
func WriteTo(database, table string) WriteOption {
	return func(w *WriteOptions) {
		w.Database = database
		w.Table = table
	}
}

There is a WriteTo func in options.go, how to make use of it in this process ? 

---
Can anyone help on how to write KV to a table ? please

----------------------------------------------------------------

**Comment by asim** [comment]
```
store.Write(
    store.NewRecord("key", value),
    store.WriteTo("micro", "example"),
)
```

**Comment by jaijainayaka** [comment]
Thanks for the quick response, Asim.

Please, have a look at the following code: 
____________________________________________

package main

import (
	"fmt"

	"github.com/micro/micro/v3/service"
	"github.com/micro/micro/v3/service/store"
)

func main() {
	srv := service.New(service.Name("example"))
	srv.Init()

	err := store.Write(
		store.NewRecord("key", []byte("value")),
		store.WriteTo("micro", "example"),
	)
	if err != nil {
		fmt.Println("error writing", err)
	}

}

Error:
.\store-write.go:16:3: too many arguments in call to store.Write
        have (*"github.com/micro/micro/v3/service/store".Record, "github.com/micro/micro/v3/service/store".WriteOption)
        want (*"github.com/micro/micro/v3/service/store".Record)

**Comment by asim** [comment]
`store.DefaultStore.Write(...)`

The public Write function in the package does not accept the options, I'll amend that in a future release.

**Comment by jaijainayaka** [comment]
that's enough.  it works! thanks, Asim.
