### ISSUE TITLE
How to update and delete - tables/databases

### ISSUE THREAD

**Issue by jaijainayaka** [micro/micro#2044]
Is there a way to update the name of table/database and, delete them ? 

and, how to List all tables in the specified database.

CLI, speaks of: 
micro store -h
   tables          List all tables in the specified database known to the store service

but, looks like  irrespective of database queried. it's listing all the tables known to the store service.

.micro\server\store 
     has the clear distinction of folder for databases, and corresponding tables in those.

______________________________________________________________

The latest documentation says: 

**Tables Usage**
   Micro services only have access to one Store table. This means all keys live in the same namespace and can collide.

When we store KV pairs in tables, they seems to be scoped specific to the tables. 
i.e., when keys are queried with **micro store list**
Only global namespace KV's are listed and specific to the table are not. 
Is my understanding is right? @asim

**Comment by asim** [comment]
If you want to query by table its `micro store list --table=xxx`. Currently there's no way to update/delete databases or tables. If you need some specific features please list exactly what they are as the commands required. I can then point you to where you can contribute that or I can look at it depending on the scope of work.
