### ISSUE TITLE
Postgres Database Connectivity 

### ISSUE THREAD

**Issue by jaijainayaka** [micro/micro#2046]
While running example service - db, we are getting an error message saying: 
{"id":"go.micro.client","code":500,"detail":"missing account from context","status":"Internal Server Error"}

var dbAddress = "postgresql://username:password@localhost:5432/database?sslmode=disable"

Printing account in auth.go gives,
           Account:  nil  ok:  false

@asim, what are we missing here in setting up the account details ? 
please, help.

PS: regular go program connection to the postgres is working perfectly. i.e., postgres side is all right.

**Comment by asim** [comment]
No idea. Sorry can't help with that. Looks like there's no auth token coming through in the request meaning you've got an unauthed endpoint.

**Comment by jaijainayaka** [comment]
Thanks again. @asim
