### ISSUE TITLE
Calibre server opent niet met http://127.0.0.1:8081

### ISSUE THREAD

**Issue by Huisman14** [micro/micro#2073]
**Describe the bug
Calibre content server opent niet met ip nr http://127.0.0.1:8081

**To Reproduce**

**Expected behavior**
It have to open the calibre library on a ipad pro

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. Ipad Pro]
 - OS: [e.g. IPadOS 17.5.1]
 - Browser [e.g. safari]

**Additional context**

**Comment by Huisman14** [comment]
Weet nog niet of ik het hier in github kan oplossen

**Comment by asim** [comment]
Might be the wrong project
