### ISSUE TITLE
how to config the TLS for etcd

### ISSUE THREAD

**Issue by fmyxyz** [micro/micro#210]
micro --registry_address=192.168.1.19:2379 --registry=etcdv3  web
2018-11-08 15:43:22.642160 I | Listening on [::]:8082
2018-11-08 15:43:22.642914 I | Listening on [::]:58277
2018-11-08 15:43:22.643140 I | Broker Listening on [::]:58278
2018-11-08 15:43:22.643637 I | Registering node: go.micro.web-f7dc5cc4-e329-11e8-b03d-f40f24325df3
2018-11-08 15:43:23.645135 I | rpc error: code = Unavailable desc = transport is closing

when I use option ` --registry=etcdv3` ,got an error:`code = Unavailable desc = transport is closing`,because etcd nead TLS config.  how to config the TLS for etcd?

**Comment by asim** [comment]
You can manually initialise the registry to provide the options https://github.com/micro/go-micro/blob/master/registry/options.go#L50L61. It's currently not supported by flags.

**Comment by fmyxyz** [comment]
Thanks.

**Comment by isabel030maria** [comment]
> micro --dirección_registerio = 192.168.1.19: 2379 --register = etcdv3 web
> 2018-11-08 15: 43: 22.642160 I | Escuchando en [::]: 8082
> 2018-11-08 15: 43: 22.642914 I | Escuchando en [::]: 58277
> 2018-11-08 15: 43: 22.643140 I | Broker Escuchando en [::]: 58278
> 2018-11-08 15: 43: 22.643637 I | Nodo de registro: go.micro.web-f7dc5cc4-e329-11e8-b03d-f40f24325df3
> 2018-11-08 15: 43: 23.645135 I | error de rpc: código = No disponible desc = el transporte se está cerrando
> 
> cuando uso la opción ` --registry=etcdv3`, `code = Unavailable desc = transport is closing`aparece un error: porque etcd nead TLS config. ¿Cómo configurar el TLS para etcd?
tLs.confín initialize?
