### ISSUE TITLE
Give ability to create new project with micro new outside of $GOPATH

### ISSUE THREAD

**Issue by Troush** [micro/micro#215]
Hey,

As GO 1.11 give ability to create projects outside of GOPATH it would be super nice to have ability to create a new project with `micro new` outside of go path and maybe with optional support of `go.mod`

**Comment by Troush** [comment]
For example:
Make an flag `--in-gopath' and currently make it default to true, so `micro` won't lose backward compatibility. But if `--in-gopath=false` we just create folder in current dir.

`micro new --in-gopath=false {{.ModuleName}}`

**Comment by asim** [comment]
Do you think we should opt for the other way around? Are most people setting a gopath now? It feels like it's being eliminated.

**Comment by asim** [comment]
To be honest how does this affect our generation of import statements and things?

**Comment by Troush** [comment]
> Do you think we should opt for the other way around? Are most people setting a gopath now? It feels like it's being eliminated.

Until the `GO111MODULE=on` will be default, I think this is should be an opt-in in micro as well. And I don't know how many devs adopting modules in general

> To be honest how does this affect our generation of import statements and things?
We just need to base all import on {{.ModuleName}} from cli

**Comment by asim** [comment]
https://github.com/micro/micro/pull/216. How's that for disabling gopath? How would we support go.mod?

**Comment by Troush** [comment]
For go.mod support, I think the best way is to check if GO111MODULE is `on` or `auto` and add go.mod  with content
```
module {{.ModuleName}}
```

**Comment by asim** [comment]
I will look at this later as I don't have time right now but feel free to PR.

**Comment by asim** [comment]
Ok done https://github.com/micro/micro/commit/b4b92c8c839b27db0f01597927196767eecc70cc

If GO111MODULE is `on` or `auto` we will create the go.mod file.

**Comment by Troush** [comment]
Awesome 👍
