### ISSUE TITLE
{"id":"go.micro.client","code":500,"detail":"error selecting go.micro.srv.user node: none available","status":"Internal Server Error"}

### ISSUE THREAD

**Issue by mmeliani** [micro/micro#219]
I'm building a cli for my service and got the following error : 
{"id":"go.micro.client","code":500,"detail":"error selecting go.micro.srv.user node: none available","status":"Internal Server Error"}

cli.go : 
```
func main() {

	srv := micro.NewService(

		micro.Name("go.micro.srv.user-cli"),
		micro.Version("latest"),
	)

	// Init will parse the command line flags.
	srv.Init()

	client := pb.NewUserServiceClient("go.micro.srv.user", microclient.DefaultClient)

	name := "Ewan Valentine"
	email := "ewan.valentine89@gmail.com"
	password := "test123"
	company := "BBC"

	r, err := client.Create(context.TODO(), &pb.User{
		Name:     name,
		Email:    email,
		Password: password,
		Company:  company,
	})
	if err != nil {
		log.Fatalf("Could not create: %v", err)
	}
        log.Printf("Created: %s", r.User.Id)

}
```

Dockerfile: 
```
build:
        CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .
        docker build -t user-cli . --no-cache
run:
        docker run --net="host" \
        -e MICRO_REGISTRY=mdns user-cli

```
below my service 
[root@localhost user-service]# make run
```
docker run --net="host" -p 50051 \
-e DB_HOST=localhost \
-e MICRO_SERVER_ADDRESS=:50051 \
-e MICRO_REGISTRY=mdns \
-e DB_USER=postgres \
-e DB_PASS=password  user-service
2018/12/09 20:27:27 Listening on [::]:50051
2018/12/09 20:27:27 Broker Listening on [::]:44783
2018/12/09 20:27:27 Registering node: go.micro.srv.user-60b9ad8a-f720-4ba6-8e49-9e58c5b39b64

```
@asim  could you please help ? 
thanks & Regards,

**Comment by asim** [comment]
Does docker allow the use of multicast DNS?

**Comment by mmeliani** [comment]
yes and it's weird the cli for another service worked very well and failed with this one,

**Comment by mmeliani** [comment]
Actually when i removed --net=host it worked but i need this for my service to connect to postgres database 
any leads where am I going wrong ? 
Regards,

**Comment by asim** [comment]
Its unclear to me what's happening here. Multicast dns binds to 224.0.0.0/24 range and expects that to be available. I have a feeling something is failing with that in the container. I would probably use consul as a dependency or try the the gossip registry which is zero dependency also but uses udp and swim protocol.

**Comment by asim** [comment]
No response.  Closing.

**Comment by 1911937806** [comment]
Whether the parameters are written wrong?
