### ISSUE TITLE
cannot run micro on windows.

### ISSUE THREAD

**Issue by cnisky** [micro/micro#223]
I ran the example by steps as follows:
**1, start consul:**

> ./consul.exe agent -dev

**2, start server.go** 

> go run server.go

### the server part code:

> package main
> 
> import (
> 	"fmt"
> 	"gomicrotest-master/server/service/test/handler"
> 
> 	"github.com/micro/go-micro"
> )
> 
> func main() {
> 	fmt.Println("Hello")
> 
> 	service := micro.NewService(
> 		micro.Name("mymicro"),
> 		micro.Version("last"),
> 		micro.Metadata(map[string]string{
> 			"type": "helloworld",
> 		}),
> 	)
> 	service.Init()
> 
> 	server := service.Server()
> 	server.Handle(server.NewHandler(&handler.TestUser{}))
> 
> 	err := service.Run()
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> 
> }

the server is running well.
![image](https://user-images.githubusercontent.com/13595791/51068987-2df23e80-1661-11e9-9d8b-04a78be3ad52.png)

**3, start client.go**

> go run client.go

### the client part code:

> package main
> 
> import (
> 	"fmt"
> 	"gomicrotest-master/server/proto/test"
> 
> 	"github.com/micro/go-micro"
> 	"golang.org/x/net/context"
> )
> 
> func runClient(service micro.Service) {
> 	testmymicro := test.NewTestUserClient("mymicro", service.Client())
> 	rsp, err := testmymicro.GetUser(context.TODO(), &test.User{Id: 123, UserName: "test232"})
> 	if err != nil {
> 		fmt.Println(err)
> 		return
> 	}
> 	// Print response
> 	fmt.Println("username", rsp.Id)
> }
> func main() {
> 	service := micro.NewService()
> 	service.Init()
> 	runClient(service)
> 
> }

run client result is bad.
![image](https://user-images.githubusercontent.com/13595791/51068990-3e0a1e00-1661-11e9-8d84-b3320bb5f0b3.png)

but I can see the service is working in consul:
![image](https://user-images.githubusercontent.com/13595791/51068996-609c3700-1661-11e9-8afc-14e9e74dd88d.png)

**4, start micro web:**

> micro web

sent rpc call is also bad:
![image](https://user-images.githubusercontent.com/13595791/51069008-7dd10580-1661-11e9-9cf1-d1f65776fbe1.png)

can anyone tell me why the rpc cannot be accessed.? 

thanks in advance.

**Comment by asim** [comment]
Please update all dependencies and try again

**Comment by cnisky** [comment]
> Please update all dependencies and try again

I have tried.  but it doesn't work.

I still get :

```
 {
  "id": "go.micro.client",
  "code": 408,
  "detail": "call timeout: context deadline exceeded",
  "status": "Request Timeout"
}

```

**Comment by asim** [comment]
Have you updated micro itself? The dashboard should display Endpoint instead of Method.

**Comment by cnisky** [comment]
> Have you updated micro itself? The dashboard should display Endpoint instead of Method.

Yes, I rebuild the micro command.


![image](https://user-images.githubusercontent.com/13595791/51116195-65b9db80-1845-11e9-9598-5f9e8d6af3f9.png)

**Comment by cnisky** [comment]
This is my consul start info. Seems OK.
![image](https://user-images.githubusercontent.com/13595791/51116403-01e3e280-1846-11e9-864a-5f9e97ffe5cd.png)

**Comment by asim** [comment]
Try running the greeter example. I can't really tell from this what the issue is. Its implying that its not receiving a response from your app. Likely related to versions your running. If everything is updated to latest master it all should work.
