### ISSUE TITLE
micro api with error:invalid duration

### ISSUE THREAD

**Issue by zhong-shizeng** [micro/micro#228]
![image](https://user-images.githubusercontent.com/5043745/51809900-6ccdf880-22df-11e9-8e17-740928ee20f1.png)

**Comment by vtolstov** [comment]
As i know, you need to downgrade consul..
Se the slack messages archive

пн, 28 янв. 2019 г., 4:31 zhong-shizeng notifications@github.com:

**Comment by asim** [comment]
As per comment, its a consul related bug introduced by hashicorp. Please downgrade and make an issue with them.

**Comment by zhong-shizeng** [comment]
how to downgrade consul?
