### ISSUE TITLE
rpc tests failing

### ISSUE THREAD

**Issue by mier85** [micro/micro#229]
```?   	github.com/micro/micro/internal/command/cli	[no test files]
2019/01/28 09:01:30 Starting server test id 9e4494b8-d664-4575-8df8-85f69b4657c3
2019/01/28 09:01:30 Transport [http] Listening on [::]:34345
2019/01/28 09:01:30 Broker [http] Listening on [::]:36833
2019/01/28 09:01:30 Stopping server
--- FAIL: TestRPCHandler (0.00s)
    rpc_test.go:96: Expected 200 response got 500 {"id":"go.micro.client","code":500,"detail":"error selecting test node: not found","status":"Internal Server Error"}
FAIL
FAIL	github.com/micro/micro/internal/handler	0.004s
``` 

I checked out the latest commit ( 1b36c30b2db02bf5af5203c56546d95fe6499b81 ( fix rpc test ) ) but the test is failing. Did dependencies change? 

As a side note, since there is neither a go.mod file, nor a vendor directory nor any other means of dependency management, it is really hard to get reproducible tests and builds.

**Comment by asim** [comment]
Are you running the latest master of go-micro?

**Comment by mier85** [comment]
yes

**Comment by asim** [comment]
This test works locally and on our travis-ci build server. Are you sure go-micro is up to date?

**Comment by mier85** [comment]
I was using the latest release and not the latest commit. Thanks. 

go.mod would have prevented that issue.

**Comment by asim** [comment]
We're waiting on `go mod` to be supported by default in 2 release versions before adopting it.

**Comment by mier85** [comment]
Then what about a vendor directory? That is supported by default since many release versions

**Comment by asim** [comment]
Vendor is a very heavy handed solution. With go mod now becoming the standard solution, it is easier to wait for a short period of time to include that.

**Comment by mier85** [comment]
It is indeed heavy, and has disadvantages, but for reproducible builds in a certain revision it does a good job.
