### ISSUE TITLE
rpc connection error

### ISSUE THREAD

**Issue by jiyeyuran** [micro/micro#236]
Micro shows the error occasionally when deploying pod on the kubernetes.

```
{"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 10.41.0.9:38157: connect: no route to host","status":"Internal Server Error"}
```
The registry is consul. if deleting the pod first and deploying it again, Micro will work normally. I think the problem is that Kubernetes is using rolling update strategy. The old pod will not deleted until the new pod is working. Somehow, the consul does not notify Micro the new pod's `ip:port` and Micro still using the old pod's `ip:port`.

**Comment by asim** [comment]
I'm not really sure what the appropriate response is to this. Do you have a method for solving this issue?

**Comment by jiyeyuran** [comment]
The problem is gone if I removes `rcache` and using the registry directly in `go-api/router/router.go`. In Micro, the router and the selector are using `go-rcache`. There are too many watcher connecting to the registry. Each service will open two watcher, one for `{"type": "services"}`, the other for `{"type": "service"}`. Micro will open 4*N (N is the number of micro services) tcp connections to the registry.

**Comment by asim** [comment]
This is an issue relating to scaling consul watchers. There's unfortunately no better approach due to the way the consul api works. If you have a better approach or a fix please let me know. I'm currently scaling back my time on this project.

**Comment by jiyeyuran** [comment]
Since Micro is using hacked strategy, the rcache in the default selector is not useful. Maybe Micro should use a custom selector like:
```
func (s *nullSelector) Select(service string, opts ...selector.SelectOption) (selector.Next, error) {
	sopts := selector.SelectOptions{
		Strategy: s.opts.Strategy,
	}

	for _, opt := range opts {
		opt(&sopts)
	}

	return sopts.Strategy(nil), nil
}
```
The hacked strategy in `go-api/rpc/rpc.go`:
```
// strategy is a hack for selection
func strategy(services []*registry.Service) selector.Strategy {
	return func(_ []*registry.Service) selector.Next {
		// ignore input to this function, use services above
		return selector.Random(services)
	}
}
```

**Comment by asim** [comment]
We'll look to change this in the coming weeks as we restructure go-api but for now its an outstanding edge case.
