### ISSUE TITLE
Question - sharding

### ISSUE THREAD

**Issue by damianoneill** [micro/micro#238]
Hi @asim this is more a question of design using micro than an issue or feature request.  Could you clarify if there is any support for data sharding across microservice replicas within micro. 

What I mean by data sharding is that I have a SVC microservice A, I want to spin up multiple replicas of A and have each replica manage a subset of data so that when a request is sent to Microservice A that a selector routes the request to the appropriate replica based on which one is managing the relevant subset of data.  

When replicas come and go the solution needs to rebalance the dataset across the remaining replica's and the selector be notified that the specific data instance may now be on a different replica.

Is there any specific support in Micro for this?  

Thanks,
Damian.

**Comment by asim** [comment]
We have a load balancing abstraction call the selector which allows filtering and selection strategies. There are two ways to approach this. One is to use a wrapper which shards based on some metadata key value https://github.com/micro/go-plugins/tree/master/wrapper/select/shard. The other is to specify the selection strategy at the time of the call using this https://github.com/micro/go-plugins/tree/master/selector/shard.

**Comment by asim** [comment]
Out of curiosity, where are you using micro?

**Comment by damianoneill** [comment]
@asim thanks for the quick response, I will get some time later to review the code.   We are currently not using micro, I'm in the process of reviewing a number of toolkits, trying to understand how our use cases would be supported.  Thanks again.  Damian.
