### ISSUE TITLE
How do I get the API gateway to select the latest version of the service?

### ISSUE THREAD

**Issue by v1990** [micro/micro#239]
For example: two versions of the same service (v1,v2) are online at the same time, how to make the API gateway request to v2?

By the way, I would like to start v2 and then close v1, but that would result in a short period of time where both v1 and v2 are online

**Comment by asim** [comment]
There's no built in method for this filtering. If you add new versions a percentage of traffic will be sent to them but not all. You can create a select filter that could explicitly make use of the new version. This sort of explicit route mapping is something we'll address separately. It's a non trivial requirement.
