### ISSUE TITLE
micro new --type=api generating faulty import

### ISSUE THREAD

**Issue by rokf** [micro/micro#245]
The code generated by `make proto` in a service created from a API template `micro new --type=api ...` seems to have a broken import.

The code in the file `proto/example/example.micro.go` uses `go_api` in multiple places, but `go_api` does not exist.

If the import line `import _ "github.com/micro/go-api/proto"` is changed to `import go_api "github.com/micro/go-api/proto"` then the service compiles.

Not sure if the issue is in the bundled `example.proto` file itself or in the generator that creates the code out of it.

**Comment by weiwolves** [comment]
i got the same issue,and think it's protoc-gen-micro problem, report issue there
https://github.com/micro/protoc-gen-micro/issues/36

**Comment by asim** [comment]
The change that caused this has been reverted. The issue should be fixed.

**Comment by rokf** [comment]
Can confirm, after updating `protoc-gen-micro` with `go get -u github.com/micro/protoc-gen-micro` it generates the correct code. Thanks!
