### ISSUE TITLE
Could not compile

### ISSUE THREAD

**Issue by xleyba** [micro/micro#249]
When doing go build I am getting the error:

../go-micro/registry/consul/watcher.go:8:2: cannot find package "github.com/hashicorp/consul/watch" in any of:
	/usr/local/go/src/github.com/hashicorp/consul/watch (from $GOROOT)
	/Users/jleyba/go/src/github.com/hashicorp/consul/watch (from $GOPATH)

How could I fix it?

**Comment by xleyba** [comment]
Hi

It is related with this ticket I have created for hashicorp team.
They have provided a workaround but I am wondering if it could be fixed here or at leat mention the solution in the documentation...

https://github.com/hashicorp/consul/issues/5604

Thanks in advance
J

**Comment by asim** [comment]
What's the TLDR?
