### ISSUE TITLE
Micro web is not working properly (tested with greeter example)

### ISSUE THREAD

**Issue by swarvanusg** [micro/micro#25]
![inval](https://cloud.githubusercontent.com/assets/7374058/13703875/dde39b6a-e7be-11e5-9938-b86530e4e513.png)

The error is the data value is being passed as null, and the below is coming. I'm not sure about the below error. 

```
2016/03/11 19:24:44 [WARN] Service tag "e={\"name\":\"Say.Hello\",\"request\":{\"name\":\"Request\",\"type\":\"Request\",\"values\":[{\"name\":\"Name\",\"type\":\"string\",\"values\":null}]},\"response\":{\"name\":\"Response\",\"type\":\"Response\",\"values\":[{\"name\":\"Msg\",\"type\":\"string\",\"values\":null}]},\"metadata\":{\"stream\":\"false\"}}" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
```

Though Micro query is working fine:

```
swarvanu@swarvanu-ThinkPad-L440 ~/ $ micro query go.micro.srv.greeter Say.Hello '{"name": "Swarvanu"}'
{
	"msg": "Hello Swarvanu"
}

```

I followed the below steps:
1> `go get github.com/micro/micro`
2> `consul agent -dev -advertise=127.0.0.1`
3> `micro --enable_stats --web_address 127.0.0.1:8585 web`
4> `swarvanu@swarvanu-ThinkPad-L440 ~/goprojects/src/github.com/micro/micro/examples/greeter/server $ go run main.go` 

Is there anything wrong, in what I'm doing ?

**Comment by asim** [comment]
Hi. The warning is just that, a warning. It's occurring within consul as it attempts to map tag data as txt records for DNS but obviously that's not possible with the format. This means DNS resolution doesn't work for anything registered via micro. Consul doesn't actually support base64 encoding for DNS txt records which makes it difficult to format it in anyway that would make it valid. We use tags as a hacked method to store metadata about the the services.

It's not an issue and everything functions correctly from a micro perspective. We could potentially address this in go-micro/registry to resolve the warnings but require an elegant solution. PRs welcome.

**Comment by asim** [comment]
Sorry to add. Missed the thing about values not seeming to be passed through. Will have a look in a few minutes.

**Comment by asim** [comment]
PR was made https://github.com/micro/micro/pull/24 which actually fixes the RPC issue and improves the implementation slightly. That's merged.

**Comment by asim** [comment]
Fixed version pushed to the demo along with the greeter server for testing http://web.micro.pm/query

**Comment by swarvanusg** [comment]
verified with the latest changes. The issue is fixed now. 

![issue 25 fixed](https://cloud.githubusercontent.com/assets/7374058/13720648/4e247b40-e834-11e5-81e9-696f0a25ff3a.png)

**Closing the issue**
