### ISSUE TITLE
I can't run "micro sidecar"

### ISSUE THREAD

**Issue by BraveAlan** [micro/micro#252]
when I run "micro sidecar", the console shows as follow:

############################
NAME:
   micro - A microservice toolkit

USAGE:
   micro [global options] command [command options] [arguments...]
   
VERSION:
   1.1.1
   
COMMANDS:
    api		Run the api gateway
    bot		Run the chatops bot
    cli		Run the interactive CLI
    registry	Query registry
    call	Call a service
    stream	Create a service stream
    publish	Publish a message to a topic
    health	Query the health of a service
    stats	Query the stats of a service
    list	List items in registry
    register	Register an item in the registry
    deregister	Deregister an item in the registry
    get		Get item from registry
    proxy	Run the service proxy
    service	Run a micro service
    new		Create a service template
    web		Run the web dashboard

...........
############################

how can I use "sidecar"? I try to run example greeter (https://github.com/micro/examples/tree/master/greeter/srv/ruby), but not work

**Comment by asim** [comment]
There is no micro sidecar, it was replaced by micro proxy.

**Comment by BraveAlan** [comment]
thank you very much.
when I use "micro proxy" in win10, it work ! But there are some strange tings happen as follow:
####################################

Step1 : run "micro proxy"

C:\Users\xxx>micro proxy
2019/04/12 13:13:21 Registering Registry handler at /registry
2019/04/12 13:13:21 Registering RPC handler at /rpc
2019/04/12 13:13:21 Registering Broker handler at /broker
2019/04/12 13:13:21 HTTP API Listening on [::]:8081
2019/04/12 13:13:21 Transport [http] Listening on [::]:49360
2019/04/12 13:13:21 Broker [http] Connected to [::]:49361
2019/04/12 13:13:21 Registry [mdns] Registering node: go.micro.proxy-16e2964d-3229-4958-9730-3f43b4ce7dda

Step 2: run "python sidecar_server.py"
 * Running on http://localhost:4001/ (Press CTRL+C to quit)

Step 3: run "python sidecar_client.py"
hello John

Step 4: : aften 10 seconds, run "python sidecar_client.py" **again**
{'id': 'go.micro.client.transport', 'code': 500, 'detail': 'readfrom tcp 127.0.0.1:49463->127.0.0.1:4001: write tcp 127.0.0.1:49463->127.0.0.1:4001: wsasend: An established connection was aborted by the software in your host machine.', 'status': 'Internal Server Error'}

Step 5 : aften 10 seconds, run "python sidecar_client.py" again
hello John

Step 6: : aften 10 seconds, run "python sidecar_client.py" **again**
{'id': 'go.micro.client.transport', 'code': 500, 'detail': 'readfrom tcp 127.0.0.1:49463->127.0.0.1:4001: write tcp 127.0.0.1:49463->127.0.0.1:4001: wsasend: An established connection was aborted by the software in your host machine.', 'status': 'Internal Server Error'}

and step7、step8.....

This is a bug that is bound to happen. How to solve this bug?

thank you very much

**Comment by asim** [comment]
This example is currently outdated but please put your issue in examples rather than here since its related to the example.
