### ISSUE TITLE
How the Micro API implements logging and rate-limiting

### ISSUE THREAD

**Issue by curry7313** [micro/micro#255]
How can the Micro API be used to implement logging, rate-limiting, monitoring, etc. similar to the functions that Zuul and Kong can achieve?

**Comment by Allenxuxu** [comment]
> How can the Micro API be used to implement logging, rate-limiting, monitoring, etc. similar to the functions that Zuul and Kong can achieve?

`package main

import (
	"log"
	"net/http"

	"github.com/micro/micro/cmd"
	"github.com/micro/micro/plugin"
)

func init() {
	plugin.Register(plugin.NewPlugin(
		plugin.WithName("example"),
		plugin.WithHandler(func(h http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				log.Println("test plugin")
				return
			})
		}),
	))
}

func main() {
	cmd.Init()
}`
