### ISSUE TITLE
micro new --namespace=nm.micro --type=api microService/api/indexapi

### ISSUE THREAD

**Issue by shabbyboy** [micro/micro#258]
exec micro new --namespace=nm.micro --type=api microService/api/indexapi 
result :
cd /Users/tugame/go/src/microService/web/indexapi
protoc --proto_path=. --go_out=. --micro_out=. proto/example/example.proto

but i exec this command, report this :
github.com/micro/go-api/proto/api.proto: File not found.
proto/example/example.proto: Import "github.com/micro/go-api/proto/api.proto" was not found or had errors.
proto/example/example.proto:8:18: "go.api.Request" is not defined.
proto/example/example.proto:8:43: "go.api.Response" is not defined.

This command seems to be incorrect, so i'm modifying  this command as 
protoc --proto_path=. --proto_path=$GOPATH/src  --go_out=. --micro_out=. proto/example/example.proto ,it's correct!

**Comment by asim** [comment]
Yes you'll have to specify the gopath in proto_path for this to work. We'll update the templates to specify the right command.
