### ISSUE TITLE
selector return expire node service

### ISSUE THREAD

**Issue by wangjinbei** [micro/micro#261]
Hi,  I used Micro framework these days, I found a few questions confused me :
  
My API service which listening on 10000, my transport is **grpc** and I used connection pool.

> MICRO_REGISTRY=consul micro  --client=grpc --server=grpc --client_pool_size=10 --client_pool_ttl=10m  api  --handler=api

> MICRO_REGISTRY=consul go run greeter/api.go

When I restart my API service and I got the *deregister log*, but my gateway's selector will select the previous API service which listening on 10000.

The error is:

> all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:10000: connect: connection refused\

**Comment by chaffz** [comment]
I had the same problem, I hope @asim  can give a reply.

**Comment by leninhasda** [comment]
Can you try adding `RegisterTTL` and `RegisterInterval` while creating micro service? 
Something like this: 

```
service := micro.NewService(
    micro.Name("go.micro.api.greeter"),
    micro.RegisterTTL(5 * time.Second),
    micro.RegisterInterval(5 * time.Second),
)
```

**Comment by wangjinbei** [comment]
Adding RegisterTTL and RegisterInterval cannot fix this question.
When  new request in, Gateway got deregister service node  from cp ([https://github.com/micro/go-rcache/blob/master/rcache.go#L138](https://github.com/micro/go-rcache/blob/master/rcache.go#L138)) which return by [rcache.get()](https://github.com/micro/go-rcache/blob/master/rcache.go#L122)

**Comment by asim** [comment]
This will be removed after the ttl expires. Rcache watches the registry for changes.
