### ISSUE TITLE
https://github.com/micro/go-api/proto/api.proto Not Found

### ISSUE THREAD

**Issue by tegk** [micro/micro#262]
When generating an API with the new command the path in the generated example proto is not found.

This should be the url, right?

https://github.com/micro/go-api/blob/master/proto/api.proto

Further more the file there seems not be compatible:

proto/example/example.proto:6:18: "go.api.Request" is not defined.
proto/example/example.proto:6:43: "go.api.Response" is not defined.

**Comment by asim** [comment]
Can you provide the command used to generate the api?

**Comment by asim** [comment]
The reason its not found is likely because your app is being created outside of the gopath and we expect it to be there right now. 

You can run your protoc command like this

```
protoc --proto_path=.:$GOPATH/src --go_out=. --micro_out=. proto/example/example.proto
```

**Comment by boost2017** [comment]
How to do this on windows, as GOPATH has a ":" inside?
`protoc --proto_path=.:%GOPATH%/src --go_out=. --micro_out=. proto/example/example.proto`
