### ISSUE TITLE
microhq/micro:kubernetes error

### ISSUE THREAD

**Issue by bigrocs** [micro/micro#264]
![image](https://user-images.githubusercontent.com/15796287/57980645-85b21380-7a60-11e9-8ba7-a9f74d772cf0.png)
![image](https://user-images.githubusercontent.com/15796287/57980652-8f3b7b80-7a60-11e9-8253-4df287e830e2.png)

**Comment by asim** [comment]
Are you passing any command to it in your yaml file?

**Comment by bigrocs** [comment]
Update the latest version of error reporting

**Comment by bigrocs** [comment]
`# 负载均衡
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micro-ingress
  namespace: api
spec:
  rules:
  - host: xip.io
    http:
      paths:
        - backend:
            serviceName: micro-service
            servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: micro-service
  namespace: api
spec:
  selector:
    app: micro
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro
  namespace: api
  labels:
    app: micro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
        - name: micro
          image: microhq/micro:kubernetes
          args:
            - "srv"
            - "--handler=rpc"
          env:
          - name: PORT
            value: "8080"
          - name: ENV
            value: staging
          - name: MICRO_REGISTRY
            value: "kubernetes"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
`

**Comment by bigrocs** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro
  namespace: api
  labels:
    app: micro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
        - name: micro
          image: microhq/micro:kubernetes
          args:
            - "srv"
            - "--handler=rpc"
          env:
          - name: PORT
            value: "8080"
          - name: ENV
            value: staging
          - name: MICRO_REGISTRY
            value: "kubernetes"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
`

**Comment by bigrocs** [comment]
![image](https://user-images.githubusercontent.com/15796287/57980677-eb9e9b00-7a60-11e9-8dfa-390955c49671.png)

**Comment by bigrocs** [comment]
It used to be normal.

**Comment by bigrocs** [comment]
![image](https://user-images.githubusercontent.com/15796287/57980787-1b01d780-7a62-11e9-9d49-e9ab1fbef224.png)
It was normal three days ago. Updating this version, it starts reporting errors.

**Comment by asim** [comment]
Your args specifies "srv". Srv is not a command in the micro toolkit. You may have been meaning to reference "api".

**Comment by bigrocs** [comment]
#

> 你的args指定“srv”。Srv不是微工具箱中的命令。你可能想要引用“api”。

Thank you
