### ISSUE TITLE
bot/bot.go:25:2: unknown import path "github.com/micro/go-bot/input/discord": cannot find module providing package github.com/micro/go-bot/input/discord

### ISSUE THREAD

**Issue by pennkao** [micro/micro#266]

**Comment by pennkao** [comment]
go module  
go 1.11

git clone https://github.com/micro/micro.git
cd micro 

go get  


go build
go: finding github.com/micro/go-bot/input/discord latest
go: finding github.com/micro/go-bot/input/telegram latest
go: finding github.com/micro/go-bot/input latest
go: finding github.com/micro latest
go: finding github.com latest
bot/bot.go:25:2: unknown import path "github.com/micro/go-bot/input/discord": cannot find module providing package github.com/micro/go-bot/input/discord
bot/bot.go:28:2: unknown import path "github.com/micro/go-bot/input/telegram": cannot find module providing package github.com/micro/go-bot/input/telegram

**Comment by asim** [comment]
go get -u

**Comment by pennkao** [comment]
go get -u
go: finding github.com/DataDog/zstd v1.4.0
go: finding github.com/stretchr/objx v0.2.0
go: finding github.com/influxdata/influxdb v1.7.6
go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: finding k8s.io/kube-openapi v0.0.0-20190228160746-b3a7cee44a30
go: finding golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: finding golang.org/x/text v0.3.1-0.20181227161524-e6919f6577db
go: finding golang.org/x/build latest
go: finding google.golang.org/genproto v0.0.0-20190508193815-b515fa19cec8
go: finding github.com/armon/circbuf latest
go: finding gopkg.in/inf.v0 v0.9.0
go: finding github.com/evanphx/json-patch v0.0.0-20190203023257-5858425f7550
go: finding golang.org/x/net v0.0.0-20190206173232-65e2d4e15006
go: finding github.com/elazarl/goproxy v0.0.0-20170405201442-c4fc26588b6e
go: finding google.golang.org/genproto v0.0.0-20190404172233-64821d5d2107
go: finding github.com/mxk/go-flowrate v0.0.0-20140419014527-cca7078d478f
go: finding golang.org/x/tools v0.0.0-20190206041539-40960b6deb8e
go: finding golang.org/x/mobile v0.0.0-20190312151609-d3739f865fa6
go: finding github.com/onsi/gomega v0.0.0-20190113212917-5533ce8a0da3
go: finding golang.org/x/image v0.0.0-20190227222117-0694c2d4d067
go: finding github.com/micro/micro v1.1.1
go: finding k8s.io/klog v0.3.0
go: finding github.com/BurntSushi/xgb v0.0.0-20160522181843-27f122750802
go: finding golang.org/x/tools v0.0.0-20190425150028-36563e24a262
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding github.com/google/go-cmp v0.3.0
go: finding github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
go: finding github.com/shurcooL/events v0.0.0-20190403073608-99a35243dbf4
go: finding dmitri.shuralyov.com/state v0.0.0-20190403024436-2cf192113e66
go: finding github.com/go-ini/ini v1.42.0
go: finding golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e
go: finding github.com/gogo/protobuf v0.0.0-20171007142547-342cbe0a0415
go: finding gonum.org/v1/netlib v0.0.0-20190313105609-8cb42192e0e0
go: finding golang.org/x/tools v0.0.0-20190312151545-0bb0c0a6e846
go: finding github.com/linode/linodego v0.7.1
go: finding github.com/googleapis/gnostic v0.0.0-20170729233727-0c5108395e2d
go get: error loading module requirements
