### ISSUE TITLE
go module Cannot compile

### ISSUE THREAD

**Issue by pennkao** [micro/micro#267]

**Comment by pennkao** [comment]
I tried a lot of methods and still can't compile，Not just me, other colleagues can't compile

I am sure I am updated.

go version go1.12.4 windows/amd64

go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

or

go: github.com/micro/go-bot@v1.0.0: parsing go.mod: unexpected module path "github.com/micro/go-bot v1.0.0"


go.mod file

module github.com/micro/micro
require (
	cloud.google.com/go v0.37.2 // indirect
	contrib.go.opencensus.io/exporter/ocagent v0.4.9 // indirect
	github.com/Azure/azure-sdk-for-go v26.7.0+incompatible // indirect
	github.com/Azure/go-autorest v11.7.0+incompatible // indirect
	github.com/Jeffail/gabs v1.2.0 // indirect
	github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190329064014-6e358769c32a // indirect
	github.com/aws/aws-sdk-go v1.19.5 // indirect
	github.com/chzyer/logex v1.1.10 // indirect
	github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
	github.com/chzyer/test v0.0.0-20180213035817-a1ea475d72b1 // indirect
	github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e // indirect
	github.com/denverdino/aliyungo v0.0.0-20190325014556-e961d750c214 // indirect
	github.com/digitalocean/godo v1.10.0 // indirect
	github.com/golang/protobuf v1.3.1
	github.com/google/uuid v1.1.1
	github.com/gophercloud/gophercloud v0.0.0-20190328150603-33e54f40ffcf // indirect
	github.com/gopherjs/gopherjs v0.0.0-20190328170749-bb2674552d8f // indirect
	github.com/gorilla/mux v1.7.0
	github.com/gregjones/httpcache v0.0.0-20190212212710-3befbb6ad0cc // indirect
	github.com/hashicorp/mdns v1.0.1 // indirect
	github.com/jarcoal/httpmock v1.0.1 // indirect
	github.com/joyent/triton-go v0.0.0-20190112182421-51ffac552869 // indirect
	github.com/json-iterator/go v1.1.6 // indirect
	github.com/konsorten/go-windows-terminal-sequences v1.0.2 // indirect
	github.com/lusis/go-slackbot v0.0.0-20180109053408-401027ccfef5 // indirect
	github.com/lusis/slack-test v0.0.0-20180109053238-3c758769bfa6 // indirect
	github.com/micro/cli v0.1.0
	github.com/micro/go-api v0.7.0
	github.com/micro/go-bot v1.0.0
	github.com/micro/go-log v0.1.0
	github.com/micro/go-micro v1.1.0
	github.com/micro/go-proxy v0.2.0
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/opentracing/opentracing-go v1.1.0 // indirect
	github.com/prometheus/procfs v0.0.0-20190328153300-af7bedc223fb // indirect
	github.com/serenize/snaker v0.0.0-20171204205717-a683aaf2d516
	github.com/sirupsen/logrus v1.4.0 // indirect
	github.com/smartystreets/assertions v0.0.0-20190215210624-980c5ac6f3ac // indirect
	github.com/smartystreets/goconvey v0.0.0-20190306220146-200a235640ff // indirect
	github.com/softlayer/softlayer-go v0.0.0-20190107163317-a40f6fdd659f // indirect
	github.com/vmware/govmomi v0.20.0 // indirect
	github.com/vmware/vic v1.5.2 // indirect
	github.com/xlab/treeprint v0.0.0-20181112141820-a009c3971eca
	golang.org/x/net v0.0.0-20190328230028-74de082e2cca
	google.golang.org/appengine v1.5.0 // indirect
	google.golang.org/genproto v0.0.0-20190327125643-d831d65fe17d // indirect
	google.golang.org/grpc v1.19.1
	k8s.io/api v0.0.0-20190327184913-92d2ee7fc726 // indirect
	k8s.io/apimachinery v0.0.0-20190328224500-e508a7b04a89 // indirect
	k8s.io/client-go v10.0.0+incompatible // indirect
	k8s.io/klog v0.2.0 // indirect
)

exclude github.com/Sirupsen/logrus v1.4.0

exclude github.com/Sirupsen/logrus v1.3.0

exclude github.com/Sirupsen/logrus v1.2.0

exclude github.com/Sirupsen/logrus v1.1.1

exclude github.com/Sirupsen/logrus v1.1.0

replace github.com/testcontainers/testcontainer-go => github.com/testcontainers/testcontainers-go v0.0.0-20181115231424-8e868ca12c0f

replace sourcegraph.com/sourcegraph/go-diff v0.5.1 => github.com/sourcegraph/go-diff v0.5.1

replace github.com/golang/lint => github.com/golang/lint v0.0.0-20190227174305-8f45f776aaf1

 
pkg\mod\github.com\sirupsen    There are two versions
logrus@v1.4.0   logrus@v1.4.2

I think two package subcontracts depend on different versions of the package

**Comment by asim** [comment]
I've updated go.mod to fix this.

**Comment by pennkao** [comment]
thinks
