### ISSUE TITLE
`micro call` use `json` codec, that failed to unmarshal to proto with `oneof` field

### ISSUE THREAD

**Issue by magodo** [micro/micro#274]
Since `micro call` not only meant to be used to send request to api, it should probably provide full support of conversion between proto and json (as mentioned [here](https://developers.google.com/protocol-buffers/docs/proto3#json)).

Suppose to use [`jsonpb`](https://godoc.org/github.com/golang/protobuf/jsonpb) in this case.

**Comment by asim** [comment]
Your pr is merged
