### ISSUE TITLE
build failed with plugins

### ISSUE THREAD

**Issue by subzerobo** [micro/micro#278]
Hi @asim 

i can build the last tag for micro/micro 1.6.0 with no problem but when i add plugin.go to the root of project like the sample here 
```
package main

import (
        _ "github.com/micro/go-plugins/registry/etcdv3"
	_ "github.com/micro/go-plugins/transport/nats"
)

```

and trying to build **micro** with etcdv3 and nats transport support, for instance, I will face these problems : 

 go build -o micro ./main.go ./plugin.go 

these errors will show up : 
```
go: finding github.com/micro/go-plugins/registry/etcdv3 latest
go: finding github.com/micro/go-plugins/transport/nats latest
go: finding github.com/micro/go-plugins/transport latest
go: finding github.com/micro/go-plugins/registry latest
go: github.com/testcontainers/testcontainer-go@v0.0.2: parsing go.mod: unexpected module path "github.com/testcontainers/testcontainers-go"
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: error loading module requirements
```
so i 've added these lines to the go.mod to replace these repos 

```
replace (
	github.com/golang/lint => github.com/golang/lint v0.0.0-20190227174305-8f45f776aaf1
	github.com/testcontainers/testcontainer-go => github.com/testcontainers/testcontainers-go v0.0.0-20181115231424-8e868ca12c0f
)
```
the below errors will come up 

```
build command-line-arguments: cannot load github.com/hashicorp/consul/api: ambiguous import: found github.com/hashicorp/consul/api in multiple modules:
        github.com/hashicorp/consul v1.4.4 (/Users/alikaviani/Projects/go/pkg/mod/github.com/hashicorp/consul@v1.4.4/api)
        github.com/hashicorp/consul/api v1.1.0 (/Users/alikaviani/Projects/go/pkg/mod/github.com/hashicorp/consul/api@v1.1.0)
```

**Comment by vtolstov** [comment]
@asim, i think that we can bring up testcontainers-go to v0.0.4
try to pin consul to v1.5.1

**Comment by subzerobo** [comment]
> @asim, i think that we can bring up testcontainers-go to v0.0.4
> try to pin consul to v1.5.1

thank you @vtolstov, pining consul to v1.5.1 fixed the problem but shouldn't these be added to go.mod?

**Comment by vtolstov** [comment]
it already in go.mod of go-plugins in indirect dep. i don't know may be this is not enough

**Comment by asim** [comment]
This looks like a fairly old issue I believe is fixed.
