### ISSUE TITLE
How to use zookeeper instead of mdsn as registry service when using "micro web" ??

### ISSUE THREAD

**Issue by gaolv123tyu** [micro/micro#279]
How to use zookeeper instead of mdsn as registry service when using "micro web" ??
Any boss could show me the  command ?

**Comment by milosgajdos83** [comment]
We don't currently have support for `zookeeper` registry. But feel free to open a PR in https://github.com/micro/go-micro

**Comment by asim** [comment]
We do have a zookeeper registry. It's in go-plugins https://github.com/micro/go-plugins/tree/master/registry/zookeeper. You can initialise this by doing the following.

Create a separate plugin.go file

```
package main

import _ "github.com/micro/go-plugins/registry/zookeeper"
```

Build micro with the plugin

```
go build -o micro main.go plugin.go
```

Set zookeeper registry via env var

```
MICRO_REGISTRY=zookeeper micro web
```

**Comment by milosgajdos83** [comment]
Oh, I see! @gaolv123tyu feel free to reopen the issue

**Comment by duke-dksky** [comment]
> We do have a zookeeper registry. It's in go-plugins https://github.com/micro/go-plugins/tree/master/registry/zookeeper. You can initialise this by doing the following.
> 
> Create a separate plugin.go file
> 
> ```
> package main
> 
> import _ "github.com/micro/go-plugins/registry/zookeeper"
> ```
> 
> Build micro with the plugin
> 
> ```
> go build -o micro main.go plugin.go
> ```
> 
> Set zookeeper registry via env var
> 
> ```
> MICRO_REGISTRY=zookeeper micro web
> ```

But how i can force new registry_address ? Why micro still trying 127.0.0.1?
