### ISSUE TITLE
Does this project support other language?

### ISSUE THREAD

**Issue by chennqqi** [micro/micro#281]

**Comment by gaolv123tyu** [comment]
That's what I want to know.

**Comment by asim** [comment]
We provide a single language framework in Go. If you would like to speak to services via a different language you can use the micro API and send a http/json based query or via its /rpc endpoint for the specific service you want to call. 

If you want all services to be able to speak to each other you should use grpc via the grpc client and server and use the grpc framework in other languages. 

We're working on clients for different languages but they will not be introduced for a while.
