### ISSUE TITLE
[bug] go-micro`s new code doesn`t match micro`s new code；micro code doesn`t update; code issues cann`t compile

### ISSUE THREAD

**Issue by DuckulaGL** [micro/micro#285]
go get -u github.com/micro/micro
# github.com/micro/micro/server
GoWork/src/github.com/micro/micro/server/server.go:53:2: too many arguments to return
	have (<-chan *router.Update, error)
	want (error)
# github.com/micro/micro/router
GoWork/src/github.com/micro/micro/router/router.go:79:25: multiple-value r.Advertise() in single-value context

**Comment by gbandres98** [comment]
This is happening to me when doing "go get -u github.com/micro/micro" on go1.12.5 linux/amd64

**Comment by milosgajdos83** [comment]
This should hopefully be fixed now by merging #284

**Comment by DuckulaGL** [comment]
It is fixed, thanks.
