### ISSUE TITLE
option for increasing default client timeout

### ISSUE THREAD

**Issue by onceatime** [micro/micro#30]
hi,
we have a task that needs longer to execute (fetch imap mails). If we use micro query cli we get:

```
error calling opencloud.srv.mail.Mail.Search: {"id":"go.micro.client","code":408,"detail":"request timeout","status":"Request Timeout"}
```

is it possible to get an cli option to increase?

**Comment by asim** [comment]
Should be fairly straight forward. I'll have a look a bit later. Basically add something like --client_timeout and set via client.Init internally.

**Comment by asim** [comment]
Done within go-micro. Allows it to be used beyond the CLI https://github.com/micro/go-micro/commit/844979be06ff5c75c3fd6e688dd78b81ce975c54

Usage: `micro --client_request_timeout=10s query opencloud.srv.mail Mail.Search`

**Comment by onceatime** [comment]
Perfect thx
