### ISSUE TITLE
how to change to use consul for  these commands, for example "micro api", "micro web"  

### ISSUE THREAD

**Issue by jiayiming001** [micro/micro#300]
Now the default is to use mdns,How to change to consul
![image](https://user-images.githubusercontent.com/32919372/62475304-58f7d780-b7d7-11e9-9f2d-97552bc275fa.png)

![image](https://user-images.githubusercontent.com/32919372/62475434-99575580-b7d7-11e9-9e7c-3068353510b3.png)

**Comment by asim** [comment]
```MICRO_REGISTRY=consul micro web```

**Comment by jiayiming001** [comment]
nice !!!
