### ISSUE TITLE
when handler=api, can not get request body

### ISSUE THREAD

**Issue by flymzero** [micro/micro#306]
i write a srv service, and  micro api --handler=api --namespace=xxx.xxx

then i use postman test, the srv service can not receive any reequest body, if i set --handler=rpc, it is ok 

log:
2019/08/16 10:46:33 Registering API Request Handler at /
2019/08/16 10:46:33 HTTP API Listening on [::]:8080
2019/08/16 10:46:33 Transport [http] Listening on [::]:64405
2019/08/16 10:46:33 Broker [http] Connected to [::]:64406
2019/08/16 10:46:33 Registry [mdns] Registering node: go.micro.api-ba8e3880-318a-44b6-aa46-98f5c3b54c77

code:
`
func (d *Driver) Read(ctx context.Context, req *driver.ReadRequest, rsp *driver.ReadResponse) error {
	fmt.Println(req)
        return nil
} 
`
postman-requestBody:
 {"user_id":222}

[![mZ3T8s.jpg](https://s2.ax1x.com/2019/08/16/mZ3T8s.jpg)](https://imgchr.com/i/mZ3T8s)

request is all error 

what is error, i can not find....

**Comment by asim** [comment]
The "api" handler uses a specific request/response format you can find in go-micro/API/proto. Otherwise you should use the default rpc handler.

**Comment by flymzero** [comment]
thanks very much
