### ISSUE TITLE
Does the template code generate support golang modules

### ISSUE THREAD

**Issue by fouadkada** [micro/micro#309]
when using the "micro new" code generation tool, is it possible to generate go modules services?

I have tried the following
`micro new example.com/micro/service --gopath=false` but it does seem to create a go.mod file with the respective imports.

Is this something to be supported?

**Comment by tooolbox** [comment]
I think [this](https://github.com/micro/micro/blob/master/new/new.go#L139) code answers your question.  Do `export GO111MODULE on` before running `micro new`.

**Comment by asim** [comment]
Hopefully the answer provided is sufficient
