### ISSUE TITLE
how can i set cookie on rpc server?

### ISSUE THREAD

**Issue by lubia** [micro/micro#31]
```
func (s *Say) Hello(ctx context.Context, req *hello.Request, rsp *hello.Response) error {
    //set cookie here
	return nil
}
```

**Comment by asim** [comment]
Hey. There's no way to set http response headers with RPC services. If you would like to write services that serve directly back to the user with that sort of flexibility, it's best to either write API services or Web services. The default API services will allow you to set response Headers while the proxy method will allow you to basically write http handlers. 

Learn more about that below:
https://github.com/micro/micro/tree/master/api
https://github.com/micro/micro/tree/master/web

**Comment by lubia** [comment]
get it ,thanks
