### ISSUE TITLE
ambiguous import

### ISSUE THREAD

**Issue by wahello** [micro/micro#315]
I have the following problem, when run 
```
go get -u github.com/micro/micro 
```
The previous logs looks good, the last a few lines looks bad, as following:
```

build github.com/micro/micro: cannot load github.com/hashicorp/consul/api: ambiguous import: found github.com/hashicorp/consul/api in multiple modules:
	github.com/hashicorp/consul v1.4.2 (/Users/xxx/envi/golang/pkg/mod/github.com/hashicorp/consul@v1.4.2/api)
	github.com/hashicorp/consul/api v1.2.0 (/Users/xxx/envi/golang/pkg/mod/github.com/hashicorp/consul/api@v1.2.0)
```

**Comment by milosgajdos83** [comment]
@keyeMyria is there any particular reason you are trying to **update** `micro` dependencies?

**Comment by xmlking** [comment]
looks like similar issue  https://github.com/micro/go-plugins/issues/394
this workaround (in go.mod) solved my problem.   
```
replace (
	github.com/hashicorp/consul => github.com/hashicorp/consul v1.6.0
)
```

**Comment by milosgajdos83** [comment]
I did not realize when making my comment that @keyeMyria was trying to upgrade `micro` as opposed to updating its dependencies! The workaround @xmlking mentions might work.

**Comment by anotherGoogleFan** [comment]
I met the same problem now. Haven't this problem be resolve?

**Comment by asim** [comment]
Please do go get rather than go get -u. When you update dependencies we have no control over how this operates especially with consul's use of sub package go modules.

**Comment by asim** [comment]
We've not had any other reports of this issue. Doing `go get github.com/micro/micro` with go modules on should solve any issues related to dependencies and import issues.
