### ISSUE TITLE
build command-line-arguments: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519

### ISSUE THREAD

**Issue by yeaze** [micro/micro#317]
go.mod

module github.com/gcc/kaihu-micro/tool-srv

go 1.12

require (
	github.com/bmizerany/assert v0.0.0-20160611221934-b7ed37b82869 // indirect
	github.com/go-sql-driver/mysql v1.4.1 // indirect
	github.com/golang/protobuf v1.3.2
	github.com/hashicorp/consul/api v1.2.0 // indirect
	github.com/imroc/req v0.2.4
	github.com/marten-seemann/qtls v0.4.0 // indirect
	github.com/micro/go-micro v1.9.1
	github.com/miekg/dns v1.1.16 // indirect
	github.com/nats-io/nats-server/v2 v2.0.4 // indirect
	github.com/onsi/ginkgo v1.10.1 // indirect
	github.com/onsi/gomega v1.7.0 // indirect
	github.com/stretchr/testify v1.4.0 // indirect
	golang.org/x/net v0.0.0-20190909003024-a7b16738d86b // indirect
	golang.org/x/sys v0.0.0-20190909082730-f460065e899a // indirect
	google.golang.org/appengine v1.6.2 // indirect
	google.golang.org/genproto v0.0.0-20190905072037-92dd089d5514 // indirect
	google.golang.org/grpc v1.23.0 // indirect
	gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 // indirect
	gopkg.in/mgo.v2 v2.0.0-20190816093944-a6b53ec6cb22 // indirect
	upper.io/db.v3 v3.6.3+incompatible
)

when I exec "go run main.go", en error occur:
build command-line-arguments: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519

**Comment by ying2025** [comment]
How do you solve this problem ? I occure the same probelm.

**Comment by godsoul** [comment]
update golang version to 1.13.4，solve this problem.
