### ISSUE TITLE
Can Micro API serve both HTTP request translation and RESTful proxy together?

### ISSUE THREAD

**Issue by Lsozke** [micro/micro#32]
I would like to add the API Gateway in front of an existing RESTful service and add additional service using Go. A planned setup:

```
request --> Micro API --> Proxy : /rest  --> Sidecar : existing RESTful service, e.g. https://127.0.0.1/myservice/
                      --> /greeter : Go Service 1
                      --> /hello : Go Service 2
```

Is it feasible?

**Comment by asim** [comment]
This is currently not supported. The API either serves API services or acts as a reverse proxy. There's been discussion around making this configurable on a per path basis or per service but it's not yet clear how it will be accomplished.
