### ISSUE TITLE
Instruction on using micro network

### ISSUE THREAD

**Issue by williampgdv** [micro/micro#322]
I see a network feature in micro which can connect network across different DC.

But i am wonder how to use it, since i cannot find any doc.

**Comment by asim** [comment]
We're still in the midst of building it, its not yet feature complete hence no docs.

The flags may change but you can use it like so.

```
# Start a node (quic transport will bind to :8085
micro network

# Start another node pointing to the first
micro network --address=:8086 --node=:8085
```

This will create two nodes which share routes based on their local registry. You can then directly route traffic through them as if it were a proxy. So when you start your service or client just do the following.

```
MICRO_PROXY=go.micro.network ./myservice
```

We're working on better integration into the existing system.

**Comment by asim** [comment]
We've written a short document to help with this https://micro.mu/docs/network.html

Hopefully this helps. Please let us know if you need more info. Join the slack to discuss.
