### ISSUE TITLE
lucas-clemente/quic-go throw error when compile with go-dep

### ISSUE THREAD

**Issue by hamidabdul1994** [micro/micro#331]
```shell
angelbroking.com/abma/lite-app-mw/applaunch/vendor/github.com/lucas-clemente/quic-go/internal/handshake
vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:501:72: undefined: qtls.CipherSuite
vendor/github.com/lucas-clemente/quic-go/internal/handshake/crypto_setup.go:523:73: undefined: qtls.CipherSuite
hamid@CSOSTAR0432D:~/go/src/angelbroking.com/abma/lite-app-mw/applaunch$ cd vendor/github.com/lucas-clemente/quic-go/
```

I am getting if i am using go-dep. Please give me alternative for the same

**Comment by milosgajdos83** [comment]
I'm not familiar with how compatible go-dep is with `go.mod`.

We've decided to adopt `go.mod` as the default dependency management tool as it's part of the core `go` toolchain and it will be turned on by default from `go 1.13` for everyone.

My best guess would be to ask at go dep developers about the compatibility with `go.mod`.

Sorry I could not be more useful.
