### ISSUE TITLE
undefined: network.Nodes

### ISSUE THREAD

**Issue by oggminator** [micro/micro#336]
While running "go get -u github.com/micro/micro" the following error is thrown:

```
github.com/micro/micro/network
go/src/github.com/micro/micro/network/network.go:104:3: undefined: network.Nodes
```

Context:
1. Host OS - Windows 10
2. VS CODE IDE
3. root directory "test-micro"
4. Dockerfile inside "test-micro": FROM golang:latest
5. VS CODE: Open a remote window: Remote-Containers: Open Folder in Container...
6. Select "test-micro" directory -> build from Dockerfile
7. Wait for the container to start...
8. The Docker container is successfully up and running
9. go get -u github.com/micro/micro
.
.
```
ERROR:
github.com/micro/micro/network
go/src/github.com/micro/micro/network/network.go:104:3: undefined: network.Nodes
```

Note: yesterday, while making some tests like the one above (same steps) everything was just fine... no errors were thrown and the "micro" command was globally registered (I've managed to successfully create a new service running "micro new ..."

PS: A new master merge was made 6 hours ago (also involving the network/network.go file)... maybe the issue is directly connected to that...

**Comment by milosgajdos83** [comment]
Yes, this is a bit of an oversight on our side. `network.Nodes` has been changed in https://github.com/micro/go-micro/pull/772 to `network.Peers` whilst the toolkit `go.mod` has not been updated.
