### ISSUE TITLE
Request micro api to support using MICRO_PROXY=xxx

### ISSUE THREAD

**Issue by williampgdv** [micro/micro#339]
When using micro api to setup an API Gateway, it cannot use proxy or tunnel to connect remote services.

**Scenario**
1. Development on remote server and local server
2. API Gateway setup on the remote server with micro api.
3. A tunnel setup to connect remote server and local server.
4. A go micro service develop and run on local server.
5. The remote micro api can invoke a rpc on the local server.

**Problem now**
The micro cannot call the rpc on the local server.

**Comment by ben-toogood** [comment]
Micro Network solves this usecase: https://micro.mu/docs/network.html
