### ISSUE TITLE
access etcdv3 with self-signed cert

### ISSUE THREAD

**Issue by quexer** [micro/micro#373]
Hello,

We're using etcdv3 with a self-signed cert.  so we can't use the default micro binary although etcdv3 support has been built in since v1.11.0

Is there any approach to access it without rebuilding the micro binary?

If the rebuild is needed, where should I put the "tls.Config initialize" code?

micro version: 1.11.0

Thanks.

refer, #210 #178

---

update: 

It seems micro support customized tls confg:
```
   --tls_cert_file value           Path to the TLS Certificate file [$MICRO_TLS_CERT_FILE]
   --tls_key_file value            Path to the TLS Key file [$MICRO_TLS_KEY_FILE]
   --tls_client_ca_file value      Path to the TLS CA file to verify clients against [$MICRO_TLS_CLIENT_CA_FILE]
```

but 

```
micro --tls_client_ca_file=ca.pem --tls_key_file=key.pem --tls_cert_file=cert.pem  --registry=etcdv3 --registry_address=https://xxxx web     
```
doesn't work at all, the command above only print useage info

---
update:

`--enable_tls` flag doesn't help either.  so is there any document describe the detail about all these flags ?

micro is awsome，yet lack of user guild is a real pain 

thanks!

**Comment by jakexks** [comment]
Those flags apply to the `micro api` and `micro web` commands, not the etcd client. It can be confusing.

**Comment by darfurfashir484** [comment]
> 

> 

> 

> 

> ###

**Comment by Balkar007** [comment]
Ok

**Comment by DoubleColl** [comment]
thank you

**Comment by Naplest** [comment]
Thank you

**Comment by CarlaBehan1212** [comment]
https://href.li/?http://trickytracker.live/tracker.php?a=pushthegoodnews

**Comment by Balkar007** [comment]
https://onetimesecret.com/secret/lowq0gcbshisjpledy7xvqev1ks58nv
