### ISSUE TITLE
micro proxy --protocol=grpc DeadlineExceeded error when setting       - MICRO_PROXY_ADDRESS=0.0.0.0:8085

### ISSUE THREAD

**Issue by xmlking** [micro/micro#375]
`micro proxy` with these options cause , following error 
      - MICRO_PROXY_PROTOCOL=grpc
      - MICRO_PROXY_ADDRESS=0.0.0.0:8085
      - MICRO_SELECTOR=static
      - MICRO_REGISTRY=memory

"error": "13 INTERNAL: rpc error: code = Internal desc = rpc error: code = DeadlineExceeded desc = context deadline exceeded"

**Comment by asim** [comment]
8085 is the wrong address
