### ISSUE TITLE
The json parse of the micro web client page parses the error when it encounters a long number

### ISSUE THREAD

**Issue by lifenglin** [micro/micro#383]
The json parse of the micro web client page parses the error when it encounters a long number

![image](https://user-images.githubusercontent.com/3182728/67364865-fb3b8600-f5a2-11e9-8247-cad0096e792e.png)

web/templates.go:235
`var request = {
                                "service": document.forms[0].elements["service"].value,
                                "endpoint": endpoint,
                                "request": JSON.parse(document.forms[0].elements["request"].value)
                        }
                        alert(JSON.stringify(request))
                        req.open("POST", "/rpc", true);
                        req.setRequestHeader("Content-type","application/json");
                        req.send(JSON.stringify(request));`

like this:
https://stackoverflow.com/questions/15689790/parse-json-in-javascript-long-numbers-get-rounded

**Comment by asim** [comment]
Will resolve later
