### ISSUE TITLE
creating a developer environment

### ISSUE THREAD

**Issue by roderm** [micro/micro#388]
I'm struggeling with setting up a developer environment. I setted up a Docker-Compose (in docker-machine) with consul, micro and own micro-services. I'd like to let these services running and connect my service which is in production to the network. 

The micro framework can call the service, but I'm unable to call a different service in the micro-framework, where the port is randomly generated and not mapped to the docker-machine. 

I tried:
* add network to the docker-compose and start the service with MICRO_PROXY_ADDRESS=/MICRO_NETWORK_ADDRESS=
* add a tunnel to the docker-compose and start the service with MICRO_TUNNEL_SERVER=/MICRO_NETWORK_ADDRESS=

Am I missing something or isn't that possible?

Container Version: microhq/micro:v1.13.2
go-micro: v1.13.2

**Comment by asim** [comment]
Much has changed since then so this is stale
