### ISSUE TITLE
#Suggestion - Mac Installation Command Requires Update

### ISSUE THREAD

**Issue by containeraki** [micro/micro#389]
Unable to install Micro in Mac with existing command, pls see logs below -
`curl -fsSL https://micro.mu/install.sh | /bin/bash
`
When tried this command, it installed successfully -
curl -0L https://micro.mu/install.sh | /bin/bash

Logs -
```
➜  ~ curl -fsSL https://micro.mu/install.sh | /bin/bash
Getting system information
Your machine is running darwin on amd64 CPU architecture
Checking machine system support
Checking HTTP client
Getting the latest micro release
Latest micro release found: v1.14.0
Downloading https://github.com/micro/micro/releases/download/v1.14.0/micro-v1.14.0-darwin-amd64.tar.gz ...
tar: Error opening archive: Unrecognized archive format
Failed to install micro
For support, please file an issue in https://github.com/micro/micro/issues
```

**Comment by jakexks** [comment]
![image](https://user-images.githubusercontent.com/333465/67589698-f583a300-f750-11e9-9b23-127d2d27ddbc.png)

Try again? maybe you got a corrupted download

**Comment by milosgajdos83** [comment]
It seems to work for me as well. I wonder what version of `curl` you're on @containeraki and what version of `macOS`

**Comment by containeraki** [comment]
@jakexks - I tried multiple scenarios as well as changing network. But that one failed, the exact error looks particular to OS as it says error opening archive. 
![image](https://user-images.githubusercontent.com/39021707/67589974-dabe2800-f76a-11e9-9af0-78d9d951a887.png)


@milosgajdos83 
**Mac Version** - OS Catalina v10.15 (19A583)

**Curl Version** -
`➜  /bin curl --version                                  
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets`

Thanks again for quick support in community!

**Comment by asim** [comment]
What version of tar are you using?

**Comment by containeraki** [comment]
@asim Tar Version

```
➜  learning tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
```

**Comment by asim** [comment]
Can you delete the tar archive from /tmp and try again

**Comment by containeraki** [comment]
@asim - Doesn't looks like this file is in /tmp or anywhere in system.

**Comment by asim** [comment]
Are you behind a firewall or something? Can you download the binary directly?

```
curl -SsL https://github.com/micro/micro/releases/download/v1.14.0/micro-v1.14.0-darwin-amd64.tar.gz -o /tmp/micro-v1.14.0-darwin-amd64.tar.gz
```

**Comment by asim** [comment]
Actually. I'm closing this issue because I've missed the fact that you can successfully download the binary. It does not matter if the flags don't work. You managed to install it.

**Comment by containeraki** [comment]
Yes, it was a suggestion only in-case if the suggested method doesn't work people can change flag.

`curl -0L https://micro.mu/install.sh | /bin/bash`

Thanks again all!

**Comment by Birjemin** [comment]
Command:
```
curl -fsSL https://micro.mu/install.sh | /bin/bash
```
I got this all time(tried many times...):
```
Getting system information
Your machine is running darwin on amd64 CPU architecture
Checking machine system support
Checking HTTP client
Getting the latest micro release
Latest micro release found: v1.18.0
Downloading https://github.com/micro/micro/releases/download/v1.18.0/micro-v1.18.0-darwin-amd64.tar.gz ...
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
Failed to install micro
For support, please file an issue in https://github.com/micro/micro/issues
```
So I handled by this way

1. Just directly downloaded from web using chrome
```
https://github.com/micro/micro/releases/download/v1.18.0/micro-v1.18.0-darwin-amd64.tar.gz 
```
2. excuted command from `https://micro.mu/install.sh`
```
// my directory is: `~/Downloads`
tar xf micro-v1.18.0-darwin-amd64.tar.gz -C ./
chmod o+x micro
// move this micro to your bin
cp micro /Users/birjemin/Developer/Go/bin
```
3. Got it!
