### ISSUE TITLE
It appeared new errors , when use "go get github.com/micro/micro" command

### ISSUE THREAD

**Issue by DuckulaGL** [micro/micro#390]
go get github.com/micro/micro
package github.com/cenkalti/backoff/v3: cannot find package "github.com/cenkalti/backoff/v3" in any of:
	/usr/local/Cellar/go/1.13.3/libexec/src/github.com/cenkalti/backoff/v3 (from $GOROOT)
	/Users/glenlau/GoWork/src/github.com/cenkalti/backoff/v3 (from $GOPATH)

**Comment by alex88** [comment]
@DuckulaGL how did you fix this?

**Comment by lucasjohnston** [comment]
@alex88 i ran into this too, didn't have the time to debug why but if you need unblocking you can just grab the latest binary and use the shell script to install - `curl -fsSL https://micro.mu/install.sh | /bin/bash`

@DuckulaGL why did you close this issue? do you have a fix?

**Comment by DuckulaGL** [comment]
@alex88 you could use these
export GO111MODULE=on
go get github.com/micro/go-micro
go get github.com/micro/micro
