### ISSUE TITLE
Micro uses etcd error

### ISSUE THREAD

**Issue by aredcup** [micro/micro#403]
```Go
cmd.Init(
		// grpc 通信
		micro.Transport(grpc.NewTransport()),
		micro.Registry(etcd.NewRegistry(func(options *registry.Options) {
			options.Addrs = []string{"127.0.0.1:2379"}
		})),
	)
```

when i visit http://127.0.0.1:8082/registry

`handler: /registry   s.registry.ListServices()` is  `mdnsRegistry`

```Go
// use the caching registry(default mdnsRegistry)
cache := cache.New((*cmd.DefaultOptions().Registry))
reg := &reg{Registry: cache}
```

how should i use etcd in micro web/api
（My English is very poor, please forgive me）

**Comment by milosgajdos83** [comment]
set `MICRO_REGISTRY` environment variable to `etcd`

**Comment by aredcup** [comment]
thany you, it is normal  when i set MICRO_REGISTRY and MICRO_REGISTRY_ADDRESS
