### ISSUE TITLE
can't run with --registry=consul --registry_address=192.168.1.3

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/micro#405]
today when I run srv it can't work with consul
go run main.go --registry=consul --registry_address=192.168.1.3
or 
MICRO_REGISTRY=consul MICRO_REGISTRY_ADDRESS=192.168.1.3 go run main.go

but can work use go run main.go

**Comment by bluedragonflyliu** [comment]
micro version 1.14.0
can't run api gateway
micro --registry=consul --server_address=192.168.1.3 api --handler=api --namespace=com.sotp.api

**Comment by asim** [comment]
Consul has moved to go-plugins https://micro.mu/blog/2019/10/04/deprecating-consul.html

**Comment by bluedragonflyliu** [comment]
the code which i write i can add plugin.go but how to change the micro api gateway use consul

**Comment by asim** [comment]
You will need to import and build the binary

**Comment by bluedragonflyliu** [comment]
It seems a little difficult for me,Where can I find an example

**Comment by asim** [comment]
See go-plugins repo readme

**Comment by xuhrc** [comment]
@bluedragonflyliu here is the solution:
step1: cd into the $GOPATH/src/github.com/micro/micro
step2: create a go file, exp: plugins.go
step3: import consul plugin
```
package main

import (
    _ "github.com/micro/go-plugins/registry/consul"
)
```
step4:  run `go build`
step5: override micro program in the $GOPATH/bin with the build result.
step6: run the api command as usual

**Comment by doubleycn** [comment]
create a go file, main.go
`
package main

import (
	//	"github.com/micro/go-micro"
	_ "github.com/micro/go-plugins/registry/consul"
	"github.com/micro/micro/cmd"
)

func main() {

	cmd.Init()
}
`
go build -o micro-api

micro-api --registry=consul  api
