### ISSUE TITLE
question about micro web

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/micro#415]
I want use  micro.service api in web.service It seem not work, does that need more  flags when start web service or need start micro api with --handler=web

**Comment by asim** [comment]
Run micro web

**Comment by bluedragonflyliu** [comment]
I try run micro  web with flag --registry=** --registry_address=*** --namespace=*** I can see in page 127.0.0.1:8082/registry have api applications and srv applications and go.micro.web but not have web application, and web.Service can start with flag --registry and registry_address.

**Comment by asim** [comment]
What is the name of your application?

It's prefix should match the namespace

E.g namespace go.micro.web and service name go.micro.web.foo

Look in the registry for your service names

**Comment by bluedragonflyliu** [comment]
does the prefix must must start with go.micro.web.def or can use com.abc.web.def

**Comment by bluedragonflyliu** [comment]
micro --registry=consul --registry_address=172.16.1.135 web --namespace=com.abc.web
web.Name("com.abc.web.def"),

**Comment by asim** [comment]
Does go.micro.web == com.abc.web?

**Comment by bluedragonflyliu** [comment]
srv applications and api applications is work and namespace not start with go.micro.srv or go.micro.api.

**Comment by bluedragonflyliu** [comment]
thanks, the trouble resolved.
