### ISSUE TITLE
Unknown unix

### ISSUE THREAD

**Issue by ImportTaste** [micro/micro#430]
First off, I love micro, it's exactly the terminal text editor I needed for my remote server. Love it to pieces. But there is an odd issue I'm having with it. While editing any file, there's this `Unknown unix` message in the lower left:

![image](https://user-images.githubusercontent.com/53661808/69225392-ed4a3800-0b43-11ea-9272-9a0d2cda482c.png)

While I think it may be related to using xfce4-terminal, or perhaps just Ubuntu 18.04 LTS with a xfce4 DE in general. If this is addressed somewhere in the documentation, I apologize in advance, but I didn't see anything. I could use some guidance on how this impacts the program, and how I should go about fixing it. Thanks!

**Comment by asim** [comment]
This is the wrong project. You're looking for the micro editor.

**Comment by ImportTaste** [comment]
Oops, I had starred it before but I brought this project up blindly from a google search. My apologies.
