### ISSUE TITLE
micro build error from go-micro on windows

### ISSUE THREAD

**Issue by crazybber** [micro/micro#435]
go version  1.13.3 

![image](https://user-images.githubusercontent.com/3401462/69441515-d98e1400-0d85-11ea-858c-d0a6f139b816.png)

linked with https://github.com/micro/go-micro/issues/968 and https://github.com/micro/go-micro/issues/949

+ how to reproduce ?
clone micro on window & cd micro & run go build.

**Comment by asim** [comment]
This was updated in master. Just go get -u github.com/micro/go-micro.

**Comment by crazybber** [comment]
issue still there, did i miss something ?

 some details: 
OS : win10 x64
go: version 1.13.4
ENV:
GOPROXY=direct
GOSUMDB=sum.golang.google.cn
mod  github.com/micro/go-micro v1.16.1-0.20191121173113-8dc3fb964eaa

**Comment by asim** [comment]
Updated. Platform specific code is a bit trickier than expected.

**Comment by crazybber** [comment]
checked .
