### ISSUE TITLE
Can't call service exposed with `micro service` command

### ISSUE THREAD

**Issue by rjmunhoz** [micro/micro#437]
## What I'm trying to do
I'm running the `main.go` file from [the docs](https://micro.mu/docs/micro-service.html#http-app) and calling it with `micro call -o raw helloworld /`

## The expected result
Micro completes the call and "hello world" is printed to the console.

## The actual result
Micro prints out an error:

```bash
> micro call -o raw helloworld /
error calling helloworld./: rpc: service/endpoint request ill-formed: /
```

## Steps to reproduce:
1. Copy the contents of the server file from the docs
2. `pbpaste > main.go`
3. `micro service --name helloworld --endpoint http://localhost:9090 go run main.go`
4. `micro call -o raw helloworld /`

## Other useful info
This happens everytime I try calling a service that I ran with `micro service` command.
Trying the request through `micro web` does not work either

- go version: go1.13.4 darwin/amd64
- micro version: 1.16.0
- OS: MacOS 10.15.1
- shell: zsh 5.7.1 (x86_64-apple-darwin19.0.0)

**Comment by rjmunhoz** [comment]
Please, let me know if there's anything I can do to help

**Comment by asim** [comment]
There's a fix in master branch but has not yet been released

```
go get github.com/micro/micro@master
```

The example should then run. Sorry for the inconvenience.

**Comment by rjmunhoz** [comment]
No problem!
That works, thankyou :D

**Comment by rjmunhoz** [comment]
Is there any way in wich I can specify the HTTP method to be used?

**Comment by asim** [comment]
You could try --header "Micro-Method: GET"
