### ISSUE TITLE
errors.Error{Id:"go.micro.client", Code:500, Detail:"service xxx not found"}

### ISSUE THREAD

**Issue by Fitsh** [micro/micro#441]
There are two services on different hosts of the same local area network , why sometimes one service can't find another service by grpc client? And I can't find another service  sometimes by “micro list services", but two services are running normally.

**Comment by vtolstov** [comment]
try to change to another registry (not mdns) and recheck

**Comment by milosgajdos83** [comment]
Agree with @vtolstov, test a different registry and see if things work. 

The only possible issues I can think of are:
* some of the tools/services do not share the same service registry
* services are deregistering due to networking problems
