### ISSUE TITLE
micro config design discussion

### ISSUE THREAD

**Issue by printfcoder** [micro/micro#446]
we know Go-Micro has integrated Etcd/Consul `k-v store `and `watch` for distributed configuration.

But for most services, just reading the configs is not enough. we need a service to support reading and watching configs and also have the ability to manage data on a web portal. 

- to be a service
- distributed
- store pluggable: MySQL/PostgreSQL/Redis/Etcd/Consul/Git etc etc
- cluster: supports different clusters. they can share and copy configs from each other.
- version: easy for clients to read special version data
- canary tests: supports push data to special clients based on IP/Metadata/...
- able to roll-back: supports rolling back the last push. 
- global and unified management entrance(web portal). 

## Design:

![image](https://user-images.githubusercontent.com/20906540/69901711-06fb4300-13c0-11ea-81d3-3e2280ec8ecc.png)

- Clients: any client or service which reading configs from `config-srv(micro config)`
- Platform-web: UI-Portal,  web dashboard.
- Config-Srv: `micro config`，supports for micro-services to read configs and watch the change of config.  but only supports update/delete data for `admin-srv`
- admin-srv:  management srv for `micro config`(we can merge `config-srv` and `admin-srv`)

## Config Data structure:

![image](https://user-images.githubusercontent.com/20906540/69901773-01eac380-13c1-11ea-80e9-19b0d97af190.png)

- App: application name
  - Cluster: eg. dev-a, dev-b, test-a, test-b
    - Namespace
      - Item: config item
        - Key
        - Value

## Request AND Protocol AND Store

> VERSION1:#{APP}/#{CLUSTER}/#{Namespace1}

### Core Store

id | namespace_id | key | value 
--- | --- | --- | --- 
1 | 2 | micro.book.name | BOOK-NAME 
2 | 2 | micro.book.price | 123 

### Format Convertible

Easy converts to JSON、Properties、YAML：

```json
{
  "micro": {
    "book": {
      "name": "BOOK-NAME",
      "price": "123"
    }
  }
}
```

So we don't support the data below:

id | namespace_id | key | value 
--- | --- | --- | --- 
1 | 2 | micro.book.name | BOOK-NAME 
2 | 2 | micro.book.price | 123 
3| 2 | **micro.book** | I am a good man

there are sub-keys in `micro.book`,  so it could not be a key, otherwise, it will get a conflict.

**Comment by vtolstov** [comment]
Nice, but needs to be in development repo.
I need something like you wrote, also watching for changes
