### ISSUE TITLE
connect: can't assign requested address when benchmark

### ISSUE THREAD

**Issue by lubia** [micro/micro#45]
every request use one port,so i run out of ports when benchmark.
will there be connection pool?

```
2016/05/08 15:34:31 {"id":"go.micro.client","code":500,"detail":"Error sending request: dial tcp 192.168.199.214:57616: connect: can't assign requested address","status":"Internal Server Error"}
```

**Comment by asim** [comment]
Do you have more info? A test case? What kind of concurrency are you pushing? What are your response times? Whats the file descriptor limit in the session you're using?

**Comment by lubia** [comment]
just run the greeter example (https://github.com/micro/micro/tree/master/examples/greeter)
and change client to 
```
for i := 0; i < 500000; i++ {
		if err := cli.Call(ctx, req, rsp); err != nil {
			log.Println(err)
			// return
		}
	}
```
I work on mac osx yosemite, ulimit -a show
```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              65536
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       709
-n: file descriptors                65536
```

**Comment by asim** [comment]
I've just run through this on mac os x yosemite with absolutely no issues. Here's my ulimit -a 

```

**Comment by asim** [comment]
Found a way to replicate when using caching selector. I think the rate at which requests are made were slowed by the registry lookup in my previous attempt.

```

**Comment by asim** [comment]
I'm thinking more about this. It's yet unclear at what layer a connection pool would be implemented. If its done within the HTTP transport, then the benefit is only provided to that implementation of the transport. If done at the Selector level it complicates the implementation of a selector and requires every implementation to handle pooling.

This may be something that needs to be solved in the Client itself. The client selects, dials, makes the request and closes the connection. Implementing it at the Client level would ensure every Transport would get the benefit.

**Comment by asim** [comment]
This is the actual issue being faced. Saturation the ephemeral port limit. http://danielmendel.github.io/blog/2013/04/07/benchmarkers-beware-the-ephemeral-port-limit/

**Comment by asim** [comment]
Started writing some connection pooling code. Literally just an hours work as of this morning but I'll share when I have something concrete. There's probably a ton of edge cases but we have to start somewhere. Done at the RPC level so that ALL the transports will benefit.

**Comment by asim** [comment]
https://github.com/micro/go-micro/pull/86

**Comment by lubia** [comment]
great job,i will do some testing

**Comment by asim** [comment]
Any follow up? How's the testing going?

**Comment by asim** [comment]
I'm closing this since the work has already begun.
