### ISSUE TITLE
why use so many consul port 

### ISSUE THREAD

**Issue by doubleycn** [micro/micro#453]
i change micro code for consul:
```go
package main

import (
	consulapi "github.com/hashicorp/consul/api"
	"github.com/micro/go-micro"
	"github.com/micro/go-plugins/registry/consul"
	"github.com/micro/micro/cmd"
	"os"
)

func main() {

	consulconf := consulapi.DefaultConfig()
	consulconf.Token = os.Getenv("CONSUL_TOKEN")
	consulconf.Address = os.Getenv("CONSUL_ADDRESS")
	cmd.Init(
		micro.Registry(
			consul.NewRegistry(
				consul.Config(consulconf),
			),
		),
	)
}
```
run
```bash
go build -o micro

./micro --registry=consul api --handler=web
```

found so many port.
```bash
netstat -anp | grep 8500|wc -l

598
```

Many ports are used。why？

like this https://github.com/micro/micro/issues/170

micro version 1.16.0

Consul 1.6.1-dev
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

**Comment by asim** [comment]
Please use an issue template to report issues

**Comment by doubleycn** [comment]
`Goroutine 332 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 333 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 334 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 335 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 336 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 337 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 338 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 339 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 340 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 341 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 342 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 343 - User: /yangyu/www/go/pkg/mod/github.com/hashicorp/consul/api@v1.2.0/health.go:192 github.com/hashicorp/consul/api.(*Client).Health (0xf2f975)
  Goroutine 344 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 345 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 346 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 347 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 348 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 349 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 350 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 351 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 352 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 353 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 354 - User: /usr/lib/golang/src/net/http/transport.go:1226 net/http.(*Transport).getConn (0xec19bb)
  Goroutine 355 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 356 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 357 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 358 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)
  Goroutine 359 - User: /usr/lib/golang/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0xa8177e)
  Goroutine 360 - User: /usr/lib/golang/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0xc2d120)`

**Comment by doubleycn** [comment]
i know.
github.com/micro/go-plugins@v1.5.1/registry/consul/watcher.go
```golang
189 func (cw *consulWatcher) handle(idx uint64, data interface{}) {
190     services, ok := data.(map[string][]string)
191     if !ok {
192         return
193     }
194
195     // add new watchers
196     for service, _ := range services {
197         // Filter on watch options
198         // wo.Service: Only watch services we care about
199         if len(cw.wo.Service) > 0 && service != cw.wo.Service {
200             continue
201         }
...
210         if err == nil {
211             wp.Handler = cw.serviceHandler
212             go wp.RunWithClientAndLogger(cw.r.Client(), log.New(os.Stderr, "", log.LstdFlags))
213             cw.watchers[service] = wp
214             cw.next <- &registry.Result{Action: "create", Service: &registry.Service{Name: service}}
215         }
...
`

**go wp.RunWithClientAndLogger(cw.r.Client(), log.New(os.Stderr, "", log.LstdFlags))**

This line of code to establish a connection, How many services will establish how many connections！

**Comment by asim** [comment]
Please open your issue in go-plugins. Consul is not part of the core.

**Comment by doubleycn** [comment]
```golang
21     reg := consul.NewRegistry(
 22         consul.Config(consulconf),
 23     )
 24     reg.Watch(registry.WatchService("mu.micro.book.srv.user"))
 31
 32     cmd.Init(
 37         micro.Registry(reg),
 39     )
```
 **reg.Watch(registry.WatchService("xxx"))**

reg not set watchoptions in cmd.Init.

github.com/micro/go-micro@v1.17.1/api/router/registry/registry.go:377
```golang
377 func newRouter(opts ...router.Option) *registryRouter {
378     options := router.NewOptions(opts...)
379     r := &registryRouter{
380         exit: make(chan bool),
381         opts: options,
382         rc:   cache.New(options.Registry),
383         eps:  make(map[string]*api.Service),
384     }
385     go r.watch()
386     go r.refresh()
387     return r
388 }
```
on line 385 call 
github.com/micro/go-micro@v1.17.1/api/router/registry/registry.go:179
```golang
179 func (r *registryRouter) watch() {
180     var attempts int
181
182     for {
183         if r.isClosed() {
184             return
185         }
186
187         // watch for changes
188         w, err := r.opts.Registry.Watch()
```
on line 188 ，watch not set watchoptions.
