### ISSUE TITLE
In Stream Rpc, stream object don't know connect disconnect message when i kill client to close connect.

### ISSUE THREAD

**Issue by zhang431705** [micro/micro#455]
I’ve just started to study go micro. I need process message like tcp long connect, so i chose use stream rpc, and create service with tcp transport. I define a read rpc and a write rpc in proto,  and use this two rpc create read/write stream:
rpc Request (stream ReqMessage) returns (ResMessage) { }
rpc Response (ReqMessage) returns (stream ResMessage) { }

in my server code,  i use two goroutine to process Requeststream/ResponseStream read/write:
func (c *ClientStream) WriteLoop(stream pb.MicroService_ResponseStream) {
	for {
		select {
		case msg := <-c.chBuf:
			if err := stream.Send(msg); err != nil {
				log.Errorf("WriteLoop error:%v", err)
				break
			}
		case <-c.close:
			return
		}
	}
}

func (c *ClientStream) ReadLoop(rsp pb.MicroService_RequestStream) {
	for {
		msg, err := rsp.Recv()
		if err != nil {
			log.Errorf("ReadLoop error:%s", err.Error())
			break
		}
		c.Recv(msg)
	}
	close(c.close)
}
 
if I  kill client to disconnect from server， but this two stream can't capture disconnect event,  this two loop can't  break. In go micro source code rpc_server.go，i found transprot.socket close was blocked by wg.wait() :
func (s *rpcServer) ServeConn(sock transport.Socket) {
	var wg sync.WaitGroup
	var mtx sync.RWMutex
	// streams are multiplexed on Micro-Stream or Micro-Id header
	sockets := make(map[string]*socket.Socket)

	defer func() {
		// wait till done
		wg.Wait()

		// close underlying socket
		sock.Close()

		// close the sockets
		mtx.Lock()
		for id, psock := range sockets {
			psock.Close()
			delete(sockets, id)
		}
		mtx.Unlock()

		// recover any panics
		if r := recover(); r != nil {
			log.Log("panic recovered: ", r)
			log.Log(string(debug.Stack()))
		}
	}()
      ...
}

in debug, i found wg value was 2,  so defer was blocked.

problem：
1 Please explain why wg value was 2.  
     I guess,  psock have two goroutine(read/write).。If  no message in psock's chan(send and recv), this two goroutine will be blocked, can't break loop ??

2 How to solve wg.wait() block problem in stream rpc?

**Comment by asim** [comment]
If still an issue please reopen
