### ISSUE TITLE
How to handle 500 error when --handler=web

### ISSUE THREAD

**Issue by LockGit** [micro/micro#458]
1，it's my mcrio api gateway , --handler=web
```
micro --registry etcdv3 --register_ttl 30 --register_interval 10 api  --handler=web
```
2，curl -vvv  https://mydomain.com/xxx/yyy
```
I'm sure the service /xxx/yyy doesn't exist ！
I wrote this path randomly and I know will return 500 Internal Server Error !
```

**But:**
```
1，I want' to know How I handler this 500 error
2，I hope the 【micro API gateway】 can have a custom error handling method when the service does not exist
```

**Comment by asim** [comment]
Write a micro plugin which injects a http handler and short circuit any 500 processing. https://github.com/micro/micro/tree/master/plugin

Example plugins https://github.com/micro/go-plugins/tree/master/micro

**Comment by LockGit** [comment]
thx

**Comment by LockGit** [comment]
>injects a http handler and short circuit any 500 processing

If so,  that the 500 errors in the backend are handled. 
If it's a real exist service have 500 will return plugin deal result to frontend，but then only hope real error to frontend instead of plugin deal result. 
Hope return plugin deal result only the service does not exist.

**Comment by LockGit** [comment]
@asim I see plugin dir no application scenario for me  ,  have some demo code ? thx
