### ISSUE TITLE
go get 下载不全框架

### ISSUE THREAD

**Issue by wang348570qi** [micro/micro#477]
go: finding gopkg.in/check.v1 latest

go: github.com/h2non/gock@v0.0.0-00010101000000-000000000000: unexpected status (https://goproxy.io/github.com/h2non/gock/@v/v0.0.0-00010101000000-000000000000.info): 410 Gone
go: finding github.com/aliyun/alibaba-cloud-sdk-go v1.60.304
go get: error loading module requirements

代理也设置了，总是下载不全，能帮我看看咋回事吗？qq： 1487315598

**Comment by wang348570qi** [comment]
go get github.com/micro/micro
这个下载出现以下报错
build github.com/micro/micro: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
总是找不到

**Comment by Kuri-su** [comment]
you need upgrade go version to 1.13+

**Comment by Kuri-su** [comment]
#317

**Comment by Kuri-su** [comment]
@milosgajdos83 This issue can be closed
