### ISSUE TITLE
stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Breezess** [micro/micro#480]
How can this be resolved?

only for http ：
![image](https://user-images.githubusercontent.com/6211684/71665037-530e1e80-2d96-11ea-873d-a30f99db3408.png)

{"id":"go.micro.client","code":500,"detail":"stream terminated by RST_STREAM with error code: PROTOCOL_ERROR","status":"Internal Server Error"}
cli and  code client Is successful

run code:
https://github.com/micro/examples/tree/master/service

in web  client  run:
![image](https://user-images.githubusercontent.com/6211684/71664744-2574a580-2d95-11ea-8a7d-1b5973ce5e4c.png)
{
  "id": "go.micro.client",
  "code": 500,
  "detail": "Bad Request: HTTP status code 400; transport: received the unexpected content-type \"text/plain; charset=utf-8\"",
  "status": "Internal Server Error"
}

etcd Version: 3.3.18
docker Version
![image](https://user-images.githubusercontent.com/6211684/71664834-81d7c500-2d95-11ea-96e0-a55418b00b4f.png)

**Comment by asim** [comment]
Can you provide more info on what you're doing?

**Comment by Breezess** [comment]
@asim There is no problem in my local environment, but this problem appears in my docker test suit

**Comment by asim** [comment]
What versions of micro/go-micro are you using? We're in the process of moving to grpc by default so master might be slightly incompatible in places.

**Comment by Breezess** [comment]
docker pull micro/micro:latest

我用的这个获取的

**Comment by asim** [comment]
The latest image will be at the latest commit tag. What version of go-micro are your services running? You should either switch your micro image to use tag 1.18.0 or switch your go-micro services to use the latest commit.

**Comment by Breezess** [comment]
switch  1.18.0 is ok,  Thank you for your answer

**Comment by Breezess** [comment]
> What versions of micro/go-micro are you using? We're in the process of moving to grpc by default so master might be slightly incompatible in places.

Migration to GRPC, when will it be released?

**Comment by asim** [comment]
Within a week I think

**Comment by Breezess** [comment]
> Within a week I think

Thank you for your answer :smile:

**Comment by SkyWingZhang** [comment]
I also met this problem. Have you solved it
