### ISSUE TITLE
Cannot install micro - cannot find package cenkalti/backoff/v3

### ISSUE THREAD

**Issue by loganintech** [micro/micro#481]
```
package github.com/cenkalti/backoff/v3: cannot find package "github.com/cenkalti/backoff/v3" in any of:
	/home/logan/go/src/github.com/cenkalti/backoff/v3 (from $GOROOT)
	/home/logan/Dev/go/src/github.com/cenkalti/backoff/v3 (from $GOPATH)
```

However, it most definitely is in `/home/logan/Dev/go/src/github.com/cenkalti/backoff`

11 days ago centkali release v4 of library, and doesn't have a v3.0* (although it should use `^3*`, right?).

What am I doing wrong here?

----

After some things it seems `GO111MODULE=on` was the issue, but when enabling that we came across this issue

```
../../pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/handshake/crypto_setup.go:433:40: not enough arguments in call to h.conn.GetSessionTicket
```

**Comment by asim** [comment]
You may have modified the go mod or have existing go modules installed causing issues. Ensure go mod is not modified in micro or go-micro, clean the modcache and then try again
