### ISSUE TITLE
How to make some system services available over tcp?

### ISSUE THREAD

**Issue by waj334** [micro/micro#489]
I'm having trouble changing the transport type from 'http' to 'tcp' when running the 'micro service' command from the terminal. using the --transport=http argument works, but --transport=tcp fails with help output. I'm getting by by doing:

micro service --name memcached-activation --endpoint localhost:11212 --metadata host=localhost:11212

micro service --name mqtt-broker --endpoint localhost:1883 --metadata host=tcp://localhost:1883

and then reading the metadata, but I'd rather it just forward the traffic from the url given by the registry. I do understand that micro has a tcp plugin, but how do I use or install it properly using the micro command?

**Comment by asim** [comment]
Plugins are not included by default, you have to import it

**Comment by waj334** [comment]
So I take it I'll have to write a small service app to handle this instead of just using the micro command on the terminal, correct?
