### ISSUE TITLE
Reskin Dashboard

### ISSUE THREAD

**Issue by asim** [micro/micro#49]
Need to reskin the dashboard. It's a bit.... yea. My web skills aren't all that. Help welcome.

There's also all the platform dashboards that need a similar rework with a unified theme if anyone is looking for other stuff to do.

**Comment by joeblew99** [comment]
I had to build a dashboard on the last project. I needed super simple and used one that needed zero JavaScript. It did what I needed but was very very limited  in the ability to customise.

The other one I used is this :

https://www.muicss.com

I don't know what sort of things are important to your project though

**Comment by asim** [comment]
That looks interesting. My friend pointed towards http://www.material-ui.com/#/ as being the defacto material design solution.

I don't mind the use of javascript. Just looking for something thats going to provide a good design and solution long term.

**Comment by joeblew99** [comment]
I have used that one also. Had lots of bugs when I used it 8 months ago.
I used more simple material UI libs and had more luck.

**Comment by iflamed** [comment]
It's interesting, may be I can wirte a new dashboard, using vue.js and the keenui https://github.com/JosephusPaye/Keen-UI. 

I know much about php, javascript, css, vue.js. I learnd golang a few months ago, but now I think I have forgot most of it.

**Comment by cgabbadon** [comment]
@asim My brother is actually a core contributor on the Material-UI project you mentioned, so I am also biased towards it. Perhaps we could give it a stab.

**Comment by asim** [comment]
Thanks Craig, appreciate it. Any existing examples of how you guys structure projects with material-ui? I want to get an idea of how its built, what the dependencies are, etc. Right now as you can see it's all using go templates so from a user perspective nothing has to be done to build it when you check it out.

**Comment by joeblew99** [comment]
I am using it. +1 from me.

**Comment by joeblew99** [comment]
Also there is a gopherjs project for react. It is a binding, so it can talk
to material UI.

This means that there is nothing to do but do a gopherjs build and the
front runs.

It also has a react router integrated.

The http endpoints, or whatever we want to call then can easily be produced
from golang so that the proxy service is produced from the actual service
interface.
So everything joins up at compile time.

It works surprisingly well. I can grab the github link tomorrow if your
interested.

**Comment by joeblew99** [comment]
Found it:
https://github.com/bep/gr

Also this is worth reading:
https://groups.google.com/forum/m/#!topic/golang-nuts/2xhqPFpzEos

**Comment by cgabbadon** [comment]
Hey @asim, we have typically used npm and webpack to build the projects. Ultimately, the only dependency that would be needed to build would be npm. `npm install` to download the necessary dependencies and and `npm run build` to build the distribution.

I am not 100% sure the best way to bundle it with the Micro source code, however. One example of a React/Go project I saw was [Mattermost](https://github.com/mattermost/platform). They have a webapp folder within the project that contains the React app. Part of the build process in the Makefile was to also run the `npm run build` to build the app for distribution there (in the webapp directory).

Could it be worthwhile to keep the UI in a separate service altogether to keep the Micro core lean?

**Comment by asim** [comment]
Ok interesting. Let me have a think. The idea with the micro dashboard is basically a small skeleton that provides an entry point and some CLI equivalent features without introducing any further dependencies.

The more feature rich dashboards are indeed separate. An example would be what one of my friends @Margatroid built https://github.com/Margatroid/micro-dashboard. If you ran this behind the web proxy it would be available under the /dashboard path.

Here's the current dashboard http://web.micro.pm. It definitely needs some work but given what I achieved with templates I feel like the same could be done going one step further. If not then having a precompiled version might not be a bad idea.

**Comment by asim** [comment]
I want to revisit this at a later date and will open a new issue with its relevant. I don't think it makes sense to reskin at the moment.
