### ISSUE TITLE
The latest version of micro is 1.14.0 in docker hub, but in github the latest version is 1.18.0

### ISSUE THREAD

**Issue by nahida05** [micro/micro#491]
It causes an error "rpc: service/endpoint request ill-formed:" in docker container, but it  works properly in local.

**Comment by asim** [comment]
Which image? Our latest images are at micro/micro.

**Comment by nahida05** [comment]
> micro/micro

this microhq/micro image .

**Comment by asim** [comment]
Please see the readme on dockerhub, that image is now deprecated in favour of micro/micro

**Comment by nahida05** [comment]
> Please see the readme on dockerhub, that image is now deprecated in favour of micro/micro

Thank you for  your quick response.It worked
