### ISSUE TITLE
micro web client execute error

### ISSUE THREAD

**Issue by aimingo** [micro/micro#494]
start srv server(type=grpc)
`2020-01-14 16:43:36.088470 I | Server [grpc] Listening on [::]:9527
2020-01-14 16:43:36.088844 I | Broker [http] Connected to [::]:49981
2020-01-14 16:43:36.089858 I | Registering node: qk.micro.filter.srv.filter-07dee634-dda2-4675-bdf5-bb563e63e3ac`

start micro 
`micro`

micro web client execute error . I don't understand why.

`curl 'http://localhost:8082/rpc' 
 -H 'Connection: keep-alive' 
 -H 'Origin: http://localhost:8082' 
 -H 'Content-type: application/json' 
 -H 'Accept: */*' 
 -H 'Sec-Fetch-Site: same-origin' 
 -H 'Sec-Fetch-Mode: cors' 
 -H 'Referer: http://localhost:8082/client' 
 -H 'Accept-Encoding: gzip, deflate, br' 
 -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' 
--data-binary '{"service":"qk.micro.filter.srv.filter","endpoint":"Filter.WorldList","request":{"request_id":"","page":1,"limit":100,"bid":0,"rid":0}}' --compressed`

[{
  "id": "go.micro.client.transport",
  "code": 500,
  "detail": "malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"",
  "status": "Internal Server Error"
}](url)

**Comment by peti2001** [comment]
Hi, same problem here.
Any suggested solution?

**Comment by peti2001** [comment]
I think I found the solution. Just use gRPC client. Like this:
Import the gRPC client
`import grpcClient "github.com/micro/go-micro/v2/client/grpc"`
create the client:
`mClient := grpcClient.NewClient()`
Use this client when you are talking to another service. 

In my case, it solved the issue.
