### ISSUE TITLE
Service not found when building rpc microservices using mdns service dicsovery

### ISSUE THREAD

**Issue by rickynyairo** [micro/micro#498]
I have an RPC micro service running with under a namespace. 

After starting the micro api under the same namespace, I cannot seem to reach my microservice:

Here's the output for `micro --namespace='namespace'  api --handler=rpc --server=:8080`

```
2020-01-21 17:41:38.274333 I | [api] Registering API RPC Handler at /
2020-01-21 17:41:38.274802 I | [api] HTTP API Listening on [::]:8080
2020-01-21 17:41:38.275045 I | [api] Transport [http] Listening on [::]:42829
2020-01-21 17:41:38.275210 I | [api] Broker [http] Connected to [::]:44871
2020-01-21 17:41:38.277168 I | [api] Registry [mdns] Registering node: go.micro.api-1aa2a721-0446-4723-9054-be0ef462fd0c

```

If I list the services running on the namespace using the command:
`micro --namespace='namespace' list services`

I am able to see the micro api service as well as my running service

However, when I attempt to make a request via  micro, I get a response with 'service not found'
`Request ==> POST : http://localhost:8080/rpc`
```
{
    "service": "shippy.auth",
    "method": "Auth.Create",
    "request": {
        "name": "test erer",
        "company": "company",
        "email": "tester@email.com",
        "password": "test123"
    }
}
```

I'm getting a response that the service cannot be found:

```
{
    "id": "go.micro.api",
    "code": 500,
    "detail": "service not found",
    "status": "Internal Server Error"
}
```
The service is running correctly as well, I can reach it via a CLI that makes RPC calls

**Comment by rickynyairo** [comment]
I solved this by setting the environment as follows before running micro:
```
export MICRO_API_HANDLER=rpc
export MICRO_API_REGISTRY=mdns
export MICRO_API_NAMESPACE=" "
export MICRO_API_ENABLE_RPC=true
export MICRO_API_ADDRESS=":8080"
```

**Comment by 01Student10** [comment]
@rickynyairo Thank you very much.
I was trying to get it work with docker-compose.. and you finally gave me the solution. Cheers!
