### ISSUE TITLE
[Discuss] micro dashboard

### ISSUE THREAD

**Issue by printfcoder** [micro/micro#500]
is different from `micro web`.  `micro dashboard` works for internal enviroment. `micro web` works for the open side which include services, network, ...

`micro dashboard` cares below features:

- config management
- microservice management
- microservice call
- gateway management
- monitor metrics
- bot management
- ...
- pluggable, people can integrate everything like Ops tools into it.

**Comment by asim** [comment]
Sounds like the platform dashboard. 

Micro web is definitely sort of a frame/skeleton rather than where everything is baked in. 

Every service should have its own web dashboard BUT we need a platform dashboard that consolidates and links everything.

I thinking we need micro platform.

**Comment by crufter** [comment]
@printfcoder Hi!

I believe I'm currently working on something like that. Currently the goal is to let people launch a service on the micro homepage, once that's in place we can sketch out the rest of the things.

**Comment by asim** [comment]
There's a lot of overlap and bleed, its not yet clear how this plays out. @Margatroid wrote a micro dashboard a long time ago https://github.com/Margatroid/micro-dashboard but I didn't want to replace the existing thing, I wasn't sure why back then but I realise now. `micro web` is an "entry point" like the api gateway and other things. Its a window to the environment as opposed to the thing that has the features.

Each service in the runtime should have an api and web ui. 

Example
- Registry
  * {Service, API, Web}
- Broker
  * {Service, API, Web}
- Config
  * {Service, API, Web}
- Runtime
  * {Service, API, Web}

All these things start as interfaces in go-micro. That's always the starting point. In which case a "platform" does not make sense there. Platform is essentially the encapsulation of all these concerns.

So in the first instance I think starting external probably makes sense, but we will likely need a "platform" service that acts as the point of aggregation to build a dashboard. That could be a `micro platform` command that starts a service.

Thoughts?

**Comment by asim** [comment]
Actually I had a thought. `micro platform` should spin up all the services rather than this being the `micro` command itself.

**Comment by asim** [comment]
@printfcoder I think you're right that we need this platform dashboard. Maybe we should cleanup micro-in-cn/platform-web and integrate here? Obviously styling should match existing stuff https://web.micro.mu/ (white space, black font, no borders, etc).

**Comment by printfcoder** [comment]
@asim yea, I do think so we need platform-web to be the entry point for management of Micro. So  I also plan to clean up  `micro-in-cn/platform-web` and remove the non-micro functions, make it only focus on Micro side.

so let's create a new repo named platform-web for that. I think its the time now.

**Comment by printfcoder** [comment]
https://github.com/Margatroid/micro-dashboard is dead, I think.

**Comment by asim** [comment]
Well we need to decide how this is going to work. If we create any new repo it would be micro/platform but I hesitate to do that without knowing if its going to split a focus. Should there be a `micro platform` command or should this be a separate concern? Should the platform dashboard be a built in sub command like `micro config` and other things or separate?

How do we decide the separation between these concerns. I'm also aware that are micro binary is becoming bloated. So should we be slimming it down or keeping web apps separate?

**Comment by printfcoder** [comment]
@crufter Hi, man. Emm, I think that what you are doing is for the open side and to be a platform. right? platform-web is built for the internal side for teams.

**Comment by asim** [comment]
@printfcoder we're going to create a new repository for platform I think micro/platform and then have micro/platform/web

**Comment by printfcoder** [comment]
@asim I know your mean. if we build it into micro,  then micro will become too heavy, too bloated. 

yea, I think we should let web apps separate.  micro should be built for the runtime side stuff, platform-web is built for visualization management side.

**Comment by printfcoder** [comment]
@asim I see. `micro/platform` will be built for web/apps?

**Comment by asim** [comment]
platform will run the entire runtime and be for all service management, it will include the dashboards I think, so we should probably extract them from micro itself.

**Comment by asim** [comment]
Structure

repo micro/platform
- main.go - run the runtime plus the web apps and consolidated dashboard
- web - for web apps
- kubernetes - for the kubernetes configuration
- ....

**Comment by asim** [comment]
What do you think @printfcoder?

**Comment by printfcoder** [comment]
Emm. Let me think about it. it will be a big repo

**Comment by crazybber** [comment]
agreed with your guys' discussion .
i also felt that micro binary is becoming bigger and bigger . we also think that we should slim it down . 

considering DDD model and microservice domain scope.maybe we need to extract out api-gateway which is an application domain entry point like many other gw,such as traefik /kong /apache-apisix; and network which is a network link layer  component under applicaton domain .

@printfcoder @hb-chen

**Comment by asim** [comment]
Key thing is understanding how we separate these concerns in a way that continues to make the tooling easy to use. A single drop in binary is much easier for the runtime than many separate things. But I also know the separate binaries can mean much much lighter apps.

runtime:
- api
- web
- cli
- bot
- proxy
- router
- network
- store
- broker
- registry
- config
- ...

Services which act as entry points or abstractions for underlying infrastructure.

Calling `micro registry` is useful but we could also have github.com/micro/micro/cmd/{api, web, config} for standalone apps. Thoughts?

**Comment by asim** [comment]
Or maybe `micro` itself only becomes the cli tool and all the things are separate processes

**Comment by printfcoder** [comment]
about separate, how about coding in one repo, building for every tool?
means we still let all of the code stay in the `micro/micro` and create build-script or sth for every tool eg api, web, bot.

**Comment by asim** [comment]
Yes that might work well

**Comment by printfcoder** [comment]
@asim 

> repo micro/platform
> 
> * main.go - run the runtime plus the web apps and consolidated dashboard
> * web/ - for web apps
> * deploy/ - for the kubernetes configuration
> * resources - for profile files. 

seems enough. 

found a UI framework: https://zeit.co/design. looks  like micro-style, very terse

**Comment by printfcoder** [comment]
I also think we can define profiles protocol:

all profile files should be put into "resources" directory

```
main.go
resources/
```

for the profiles of micro, it will start with micro.

micro.yml
```yml
micro:
  config:
     server_name: xxx
     server_address: xxxx
  bot:
     xxx
  api:
     handler: web
     server_name: xxx
     server_address: xxxx
```

OR

micro.json

```
{
  "micro": {
    "config": {
      "server_name": "xxx",
      "server_address": "xxxx"
    },
    "bot": "xxx",
    "api": {
      "handler": "web",
      "server_name": "xxx",
      "server_address": "xxxx"
    }
  }
}
```

if people think the profile would be to long, they can separate it like:

micro-config.yml
```yml
micro:
  config:
     server_name: xxx
     server_address: xxxx
```

micro-bot.yml
```yml
micro:
  bot:
     xxx
```

and enable config and bot:

micro.yml
```yml
micro:
  includes: config, bot
```

this design is inspired by Spring.

**Comment by asim** [comment]
Makes sense, we want to define common config in a single place, and then override. The config service supports this. Ideally we should be moving go-micro towards using Config interface rather than Cmd to support this by default but in the short term we can let platform set env var values against each thing.

**Comment by crazybber** [comment]
all above is good options ,here provide a new view for reference： 

i think we can make it more clear and reasonable by some necessary separation.

now we consider micro as tooling set which I think maybe not enough, when comparing with microservice ecology

which consider gateway/mesh/network as different components.

Let's reflect about micro tools with the following perspective to see if we can use some.

**gateway** :Targeting to run as a application domain traffic entry point  which will include :
+ api - Http rest calling 
+ web - Websocket
+ proxy-Reverse proxy
+ broker-Publish operation event or something else
+ registry -Dynamic service calling
+ router(ingress)-Hot configuration and path
+ .....

i thinks it better to integrate them into one  not scattered cmd to support full gateway design.

**micro** : Targeting to provide runtime service management and tooling set ,plus a micro/platform/web extendable web front-end. 
 
+ config -Service governance and configuration.
+ cli -interface  tool 
+ bot -Message agent or notification
+ store -data permanent
+ ...

**Network**:Which run  as a overlay  tunnel  under application domain  to provide a steady network connection to cross edge and cloud or multi-cloud .
include :
+ network-Message routing and connection
+ tunnel -link point to point 
+ ....

**Comment by asim** [comment]
The problem with the external ecosystem of tooling is that they are all working on single specialist tools. Every company is focused on delivering just one piece of an overall architecture. Micro has always had a platform focus. It takes many systems in coordination to create a platform. And so I think splitting it, while it creates nice standalone tools, is not a good fit for micro. 

I think that should be a completely separate effort or again as I mentioned something that sits as independently loadable binaries via cmd/{api, web, proxy, network}.

If we did go down the route of splitting everything out, I just feel like people would be confused because our tooling is very tightly coupled to our own way. It's a bit like using a specific standalone piece of an operating system. Its not useful. It's the overall operating system thats of value.

**Comment by asim** [comment]
Code for the platform should go here https://github.com/micro/platform

We're going to provide something fully automated that can be created on kubernetes

**Comment by crazybber** [comment]
great, let's keep moving forward.
