### ISSUE TITLE
Micro command flag does not set namespace

### ISSUE THREAD

**Issue by refs** [micro/micro#504]
```console
micro -v // micro version 1.18.0

micro api --namespace "foo.bar"

[...]
micro list services
go.micro.api
go.micro.http.broker
```

I was expecting to see:

```console
foo.bar.api
go.micro.http.broker
```

**Comment by asim** [comment]
Namespace is the namespace used to resolve services, not the namespace of the api itself. You will need to set server name.

**Comment by asim** [comment]
If you would like to contribute a change that sets namespace across the tooling when specified we welcome a PR
