### ISSUE TITLE
micro new uses v1 tmpl while protoc-gen-micro does v2

### ISSUE THREAD

**Issue by naxmefy** [micro/micro#522]
### Some edge info

- [protoc-gen-micro master](https://github.com/micro/protoc-gen-micro) says install with go get github.com/micro/protoc-gen-micro/v2
- [micro install info](https://github.com/micro/micro#install) ([the v2.0.0 README too](https://github.com/micro/micro/tree/v2.0.0)) just says GO111MODULE and install with `go get github.com/micro/micro`
- micro version 1.18.0 will be installed

### Problem

The command "micro new" generates the service with **v1**. Protoc will generate with **v2**. The new project is not buildable.

#### main.go

```go
        "github.com/micro/go-micro/util/log"
	"github.com/micro/go-micro"
```

#### handler/{service-name}.go

```go
        "github.com/micro/go-micro/util/log"
```

#### subscriber/{service-name}.go

```go
        "github.com/micro/go-micro/util/log"
```

### extra hint

the plugin .go template in v2 should be checked as well ([check here](https://github.com/micro/micro/blob/v2.0.0/internal/template/plugin.go)). Tried the **new** command with flag "--plugin=registry=etcd". 

**got**

```go
package main

import (
	_ "github.com/micro/go-plugins/registry/etcd"
)
```

**produced following error in windows (build)**

```bash
build command-line-arguments: cannot load github.com/micro/go-plugins/registry/etcd: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/registry/etcd
```

**changed plugin.go**

```go
package main

import (
	_ "github.com/micro/go-micro/v2/registry/etcd"
)
```

**worked**

**Comment by vtolstov** [comment]
do you try go get github.com/micro/micro/v2@master ?

**Comment by naxmefy** [comment]
> do you try go get github.com/micro/micro/v2@master ?

tried it - same issue

**Comment by domwong** [comment]
Imports have been updated to v2 back in Feb. Closing
