### ISSUE TITLE
Can support fasthttp as well as net/http?

### ISSUE THREAD

**Issue by wangyjx** [micro/micro#53]
As the title, do you have any plan to support fasthttp

**Comment by asim** [comment]
This is the first I'm hearing of fasthttp. From the docs `Unfortunately, fasthttp doesn't provide API identical to net/http`. I'm not sure it will be something supported in the short term.

**Comment by wangyjx** [comment]
yes, fasthttp API is not compatible with nethttp, but it is much faster than net/http. iris and echo have supported fasthttp, I think it can be considered because of its performance, :-)

**Comment by asim** [comment]
I agree on the performance front but its not something likely to be done in the near future. I'll open a new issue when its being considered. Thanks.
