### ISSUE TITLE
When I ran into problems using etcd and micro API。

### ISSUE THREAD

**Issue by arCzWw** [micro/micro#533]
**I'm a novice at micro. Can someone help me?
When I run micro API -- handler = http。I use etcd locally, but the following error occurs in the micro API**
```
2020-02-10 18:16:03.331662 I | http: proxy error: dial tcp 192.168.19.235:53796: connectex: A connection attempt failed because the co
nnected party did not properly respond after a period of time, or established connection failed because connected host has failed to r
espond.
127.0.0.1 - - [10/Feb/2020:18:15:42 +0800] "POST /api/v1/login HTTP/1.1" 502 0 "http://127.0.0.1:8888/" "Mozilla/5.0 (Windows NT 10.0;
 WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
```
**192.168.19.235 here doesn't know what it is, and why isn't it 127.0.0.1?**

**Comment by arCzWw** [comment]
I've added global variables MICRO_REGISTRY=etcd。

**Comment by ben-toogood** [comment]
Why are you using hander=http? This is used by micro to map requests from micro api to your service, I suspect you don't need this.
