### ISSUE TITLE
Python server greeter example does not contain service registration

### ISSUE THREAD

**Issue by nii236** [micro/micro#55]
Hello,

I've been trying to write a python service into the sidecar but was stumped at the registration bit.

It turns out that there is code in the Ruby example containing service registration, but the Python example does not.

- nii236

**Comment by asim** [comment]
Here's an example. 

https://github.com/micro/micro/commit/79b11310d99a421d1f74b35972fb6f871236ccba

You can look at the ruby code to see how it works as well or the curl example in the docs https://github.com/micro/micro/tree/master/car. If you know how to write python its a fairly straight forward http call.

**Comment by nii236** [comment]
Awesome thanks!
