### ISSUE TITLE
why no newline at end of file by default?

### ISSUE THREAD

**Issue by pravi** [micro/micro#555]
vim and probably other editors add a newline at end of file by default. Any reason for micro not adding it by default? It looks weird when creating a file in micro and running cat.

I think this will cause unnecessary changes when someone else opens the same file in vim.

```
root@gitlab:~# micro a
root@gitlab:~# cat a
helloroot@gitlab:~# vim a
root@gitlab:~# cat a
hello
root@gitlab:~# 

```
Note: using root inside a container

**Comment by asim** [comment]
This is not the micro editor

**Comment by pravi** [comment]
oops! sorry for the noise.
