### ISSUE TITLE
Micro grpc proxy cannot close socket

### ISSUE THREAD

**Issue by aimingo** [micro/micro#559]
Micro grpc proxy cannot close socket.
When I use the command 'micro --client=grpc --server=grpc proxy --protocol grpc' to proxy SRV requests.
Client of proxy cannot close socket at this time. When using the 'ss -s' command to view the closed parameter in the docker centos system, he became more than 5000.
When I finished the micro program, the system closed decreased.

The result of running the command netstat -anp 
tcp        0      0 192.168.2.242:35084     192.168.1.216:9527      ESTABLISHED 
tcp        0      0 192.168.2.242:57502     192.168.1.216:9527      ESTABLISHED 
tcp        0      0 192.168.2.242:37952     192.168.1.216:9527      ESTABLISHED 
tcp        0      0 192.168.2.242:57766     192.168.1.216:9527      ESTABLISHED 
tcp        0      0 192.168.2.242:34450     192.168.1.216:9527      ESTABLISHED 
tcp        0      0 192.168.2.242:37938     192.168.1.216:9527      ESTABLISHED

netstat -anp | grep 9527 | wc -l
1021

But each request requires a new socket connection to be created, and I don't understand why.
Setting the number of connection pools does not control the number of socket connections.

But by requesting the SRV program directly, the connection can be released normally.
When using micro GRPC proxy stream, the connection cannot be released properly.

The problem I have come across approximates to ISSUE.
https://github.com/micro/micro/issues/170

**Comment by aimingo** [comment]
micro version 1.18.0

**Comment by atakanozceviz** [comment]
I opened an issue for the same reason  (https://github.com/micro/go-micro/issues/1223). I think the reason is that potential client errors (e.g. io.EOF) do not propagate to the server.

**Comment by aimingo** [comment]
#

> I opened an issue for the same reason ([micro/go-micro#1223](https://github.com/micro/go-micro/issues/1223)). I think the reason is that potential client errors (e.g. io.EOF) do not propagate to the server.

Yes.

**Comment by asim** [comment]
Please reopen if still an issue
