### ISSUE TITLE
Add ability to disable CORS checking or whitelisting origins for sidecar

### ISSUE THREAD

**Issue by nii236** [micro/micro#56]
Due to the CheckOrigin in [broker.go](https://github.com/micro/micro/blob/master/internal/handler/broker.go#L32) not being set, it is `nil`. This means that websocket connections from a different origin (in my case, outside the docker machine) can not connect to it.

Please allow the `sidecar_cors` option to be passed into this field. At the moment, `sidecar_cors` is not currently working (I think).

Comments for CheckOrigin are here:
```
// CheckOrigin returns true if the request Origin header is acceptable. If
// CheckOrigin is nil, the host in the Origin header must not be set or
// must match the host of the request.
```

**Comment by asim** [comment]
I know your use case is related to trying to access the broker directly from the browser but thats not really the typical use case. I'll give this a think but I'm not sure its likely to change.

**Comment by nii236** [comment]
That's fine. But perhaps you should remove the [SIDECAR_CORS](https://github.com/micro/micro/blob/master/main.go#L95) flag in that case, to remove the ambiguity? Or does it get used for other things?

**Comment by asim** [comment]
It should be used to set things for the sidecar but is not setup.

**Comment by asim** [comment]
Cors for the sidecar added with this commit https://github.com/micro/micro/commit/86510f6d1f17a801b2f22570c47e111855d9bd59

**Comment by jacobeverist** [comment]
> I know your use case is related to trying to access the broker directly from the browser but thats not really the typical use case. I'll give this a think but I'm not sure its likely to change.

Actually the use case was more for debugging and development purposes.  Trying to figure out the protocol for interacting with the sidecar from an application running on the desktop.
