### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [micro/micro#573]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/micro/micro)](https://www.tickgit.com/browse?repo=github.com/micro/micro)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/micro/micro)](https://www.tickgit.com/browse?repo=github.com/micro/micro)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by asim** [comment]
Hey, thanks for the suggestion. Out of curiousity, are @packethost users of micro?

**Comment by patrickdevivo** [comment]
Hi @asim, nope not as far as I know!

**Comment by asim** [comment]
We'll think to add later
