### ISSUE TITLE
micro web call  unsupported content type

### ISSUE THREAD

**Issue by echopairs** [micro/micro#574]
response:
`{
  "id": "go.micro.client",
  "code": 500,
  "detail": "Bad Request: HTTP status code 400; transport: received the unexpected content-type \"text/plain; charset=utf-8\"",
  "status": "Internal Server Error"
}`

call service Metadata
`
broker=http protocol=mucp registry=etcd server=mucp transport=http
`
go.micro.web Metadata
`
broker=http protocol=mucp registry=etcd server=mucp transport=http
`

**Comment by asim** [comment]
Should no longer be an issue
