### ISSUE TITLE
golang 1.14 install errors 

### ISSUE THREAD

**Issue by enddering** [micro/micro#586]
go version: go version go1.14 darwin/amd64
system: mac os 10.15.3
`
$ go get github.com/micro/micro/v2
go: downloading github.com/micro/micro/v2 v2.2.0
go: downloading github.com/micro/go-micro/v2 v2.2.0
go: downloading github.com/micro/mdns v0.3.0
go: downloading github.com/micro/cli/v2 v2.1.2
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../../pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/micro/go-micro/v2/api/server/acme/certmagic
../../../pkg/mod/github.com/micro/go-micro/v2@v2.2.0/api/server/acme/certmagic/certmagic.go:22:19: certmagic.Default.CA undefined (type certmagic.Config has no field or method CA)
../../../pkg/mod/github.com/micro/go-micro/v2@v2.2.0/api/server/acme/certmagic/certmagic.go:25:20: certmagic.Default.DNSProvider undefined (type certmagic.Config has no field or method DNSProvider)
# github.com/micro/go-micro/v2/transport/quic
../../../pkg/mod/github.com/micro/go-micro/v2@v2.2.0/transport/quic/quic.go:54:12: q.s.Close undefined (type quic.Session has no field or method Close)
../../../pkg/mod/github.com/micro/go-micro/v2@v2.2.0/transport/quic/quic.go:121:3: unknown field 'IdleTimeout' in struct literal of type quic.Config

`

**Comment by IamTonyZHOU** [comment]
I got the same problem. could u please let me know how you resolve it?

**Comment by vtolstov** [comment]
enable go modules, or use go 1.14. also don't do go get -u

**Comment by ppusapati** [comment]
Have already update my packages. What's the possible solution?

**Comment by vtolstov** [comment]
rollback update for all and use only needed updates

**Comment by Nemo-VII** [comment]
replace github.com/lucas-clemente/quic-go v0.15.2 => github.com/lucas-clemente/quic-go v0.14.1

**Comment by crazybber** [comment]
make sure to  use the go mod way ，Not traditional go package update.

**Comment by marvinliu1** [comment]
I'm new to the Golang, today I ran the command line "go get github.com/micro/micro/v2" and got this:
`# github.com/micro/go-micro/v2/transport/quic
..\..\..\user-srv-master\pkg\mod\github.com\micro\go-micro\v2@v2.4.0\transport\quic\quic.go:54:12: q.s.Close undefined (type quic.Session has no field or method Close)
..\..\..\user-srv-master\pkg\mod\github.com\micro\go-micro\v2@v2.4.0\transport\quic\quic.go:121:3: unknown field 'IdleTimeout' in struct literal of type quic.Config`

Please help!

**Comment by marvinliu1** [comment]
> I'm new to the Golang, today I ran the command line "go get github.com/micro/micro/v2" and got this:
> `# github.com/micro/go-micro/v2/transport/quic
> 
> ......\user-srv-master\pkg\mod\github.com\micro\go-micro\v2@v2.4.0\transport\quic\quic.go:54:12: q.s.Close undefined (type quic.Session has no field or method Close)
> 
> ......\user-srv-master\pkg\mod\github.com\micro\go-micro\v2@v2.4.0\transport\quic\quic.go:121:3: unknown field 'IdleTimeout' in struct literal of type quic.Config`
> 
> Please help!

Never mind, my quic-c version is 15.3 not 15.2, so basically Nemo-VII solution works after replacing the version in the command line.
replace github.com/lucas-clemente/quic-go **v0.15.2** => github.com/lucas-clemente/quic-go v0.14.1
replace github.com/lucas-clemente/quic-go **v0.15.3** => github.com/lucas-clemente/quic-go v0.14.1

**Comment by zstone12** [comment]
I'm new to the Golang,I meet the same probrem.how to konw my quic-c version?
