### ISSUE TITLE
"open" command autocompletion has incorrect functionality on Windows because of backslashes

### ISSUE THREAD

**Issue by tfcat** [micro/micro#609]
Example:
```
>open Des <tab>
>open Desktop\
>open Desktop\tes <tab>
>open Desktop\test.lua
```

This command is expected to open the file `Desktop\test.lua`, but instead creates a new file called `Desktoptest.lua`.

Using forward slashes instead has correct functionality, but autocompletions inside a directory no longer work.

Video of issue in action:
https://files.catbox.moe/s1edjq.mp4

**Comment by asim** [comment]
Wrong project

**Comment by tfcat** [comment]
WHOOPS, sorry!
