### ISSUE TITLE
`micro new` doesn't work on Windows

### ISSUE THREAD

**Issue by sunfmin** [micro/micro#61]
```
c:\GoPKG\src\github.com\micro\micro\new>micro new github.com/sunfmin/hellomicro
creating service go.micro.srv.hellomicro
creating C\src\github.com\sunfmin\hellomicro\main.go
open C\src\github.com\sunfmin\hellomicro\main.go: The system cannot find the path specified.
```

**Comment by asim** [comment]
I think it might have something to do with these two lines in the code https://github.com/micro/micro/blob/master/new/new.go#L130L131

I have a GOPATH with multiple paths separated by a colon. On windows obviously this seems to destroy `c:\`. I need to find a better way.

**Comment by asim** [comment]
Made a fix. Pull master. Let me know if it works.

**Comment by asim** [comment]
Please provide feedback or the issue will be closed.

**Comment by zet4** [comment]
similar issue here, don't want to open a new issue for it though, built from master:
```
H:\gopath\src\github.com>micro new --type srv --alias randomimages --namespace pm.zeta github.com/zet4/randomimages-srv/
creating service pm.zeta.srv.randomimages
creating H:\gopath\src\github.com\zet4\randomimages-srv\main.go
open H:\gopath\src\github.com\zet4\randomimages-srv\main.go: The system cannot find the path specified.
```

**Comment by danbopes** [comment]
Attempting to create a service on windows, I get the following error (No service is created, nor a folder created):

C:\Users\Daniel\Go\bin>micro new greeter
creating service go.micro.srv.greeter
creating C:\Users\Daniel\Go\src\greeter\main.go
open C:\Users\Daniel\Go\src\greeter\main.go: The system cannot find the path specified.

Additional Debugging:
C:\Users\Daniel\Go\bin>echo %GOPATH%
C:\Users\Daniel\Go

C:\Users\Daniel\Go\bin>echo %GOROOT%
C:\Go\
