### ISSUE TITLE
panic: proto: duplicate enum registered: authpb.Permission_Type

### ISSUE THREAD

**Issue by SkyWingZhang** [micro/micro#622]
in build micro
panic: proto: duplicate enum registered: authpb.Permission_Type

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
        /Users/zty/go/pkg/mod/github.com/golang/protobuf@v1.3.2/proto/properties.go:458
go.etcd.io/etcd/auth/authpb.init.0()
        /Users/zty/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191031170918-4388404f56cb/auth/authpb/auth.pb.go:115 +0x1e5
exit status 2

**Comment by SkyWingZhang** [comment]
micro v2.2

**Comment by chenqin0611** [comment]
I encountered the same problem, have you solved it？

**Comment by SkyWingZhang** [comment]
@chenqin0611 Whether the version is aligned？micro and go-micro version
