### ISSUE TITLE
Let's Encrypt support

### ISSUE THREAD

**Issue by asim** [micro/micro#65]
Micro provides HTTP entry points via the API, Web UI/Proxy and Sidecar. Let's Encrypt is now becoming a standard way to provide free TLS based certificates for secure communication. Others like Caddy, Traefik, etc are supporting Let's Encrypt as an automatic way of securing web servers. We should do the same with Micro. We can reuse existing implementations such as Russ Cox's code here https://github.com/rsc/letsencrypt. I'm sure other implementations also exist.

**Comment by asim** [comment]
Potentially use this https://github.com/xenolf/lego

**Comment by bruth** [comment]
A low-hanging fruit could be to replace the implicit self-signed cert mentioned [here](https://github.com/micro/go-micro/blob/master/transport/options.go#L48-L49) (and implemented [here](https://github.com/micro/go-micro/blob/master/transport/http_transport.go#L423-L428)) with an anonymous Let's Encrypt cert. This appears straightforward with Russ' implementation, but I have not looked at the lego repo.

**Comment by asim** [comment]
Close for now.
