### ISSUE TITLE
Service created with micro new does not compile 

### ISSUE THREAD

**Issue by JayantaP** [micro/micro#669]
Hi,
I've create a new micro service with: 
micro new example --namespace=<namespace> --gopath=false

ran protoc:
protoc --proto_path=.:$GOPATH/src --go_out=. --micro_out=. proto/example/example.proto

Created a module with: 
go mod init example

Installed go-micro v1.18.0 with:
go get github.com/micro/go-micro@v1.18.0

Then tried to build using the makefile but got an error:

make build && ./example-srv
protoc --proto_path=/root/go/src:. --micro_out=. --go_out=. proto/example/example.proto
go build -o example-srv *.go

cannot use service.Server() (type "github.com/micro/go-micro/server".Server) as type "github.com/micro/go-micro/v2/server".Server in argument to <namespace>_srv_example.RegisterexampleHandler:
"github.com/micro/go-micro/server".Server does not implement "github.com/micro/go-micro/v2/server".Server (wrong type for Handle method)
have Handle("github.com/micro/go-micro/server".Handler) error
want Handle("github.com/micro/go-micro/v2/server".Handler) error
Makefile:12: recipe for target 'build' failed
make: *** [build] Error 2

I've installed go-micro/v2 with go get github.com/micro/protoc-gen-micro/v2. But that did not solve the problem.
I tried to install latest with go get github.com/micro/protoc-gen-micro@master
Got an error:
go get github.com/micro/protoc-gen-micro@master: github.com/micro/protoc-gen-micro@v1.0.1-0.20200222160529-fe9054acb2c3: invalid version: go.mod has post-v1 module path "github.com/micro/protoc-gen-micro/v2" at revision fe9054acb2c3

I want to start with go-micro, but need your help to proceed.

**Comment by domwong** [comment]
Please use github.com/micro/go-micro/v2 rather than v1.18.0
