### ISSUE TITLE
Bot slack, messages not coming through

### ISSUE THREAD

**Issue by marsn** [micro/micro#68]
It works fine on year ago compilation, but current version go/micro has ~50% success rate delivered messages

**Comment by asim** [comment]
The bot code has not changed. Could you please explain what source you are using, how many instances you are running, what the configuration is.

**Comment by marsn** [comment]
go1.7, ubuntu 16.04 tested on 5 instances, same issue. I have year ago micro, copied to one of them and surprisingly it works fine

**Comment by asim** [comment]
Any issues are likely related to the slack library used https://github.com/nlopes/slack. Are you using the recent version of this? Looks like there are some recent fixes.

**Comment by marsn** [comment]
not sure if it's related https://github.com/nlopes/slack/issues/97 , yes  go get -u github.com/micro/micro and bot/slack stop working

**Comment by asim** [comment]
Yea that potentially looks related. Will wait for updates in that thread.

**Comment by favoretti** [comment]
@asim You can work that around with using normal API to post. 
Basically:

```
+       b.Client.PostMessage(evt.Channel, msg, params)
-       b.RTM.SendMessage(b.RTM.NewOutgoingMessage(msg, evt.Channel))
```

**Comment by marsn** [comment]
Update https://github.com/nlopes/slack/pull/102 fixed that
