### ISSUE TITLE
API doesn't override namespace when using CLI

### ISSUE THREAD

**Issue by sayden** [micro/micro#69]
Using go version `go1.7.1 linux/amd64` when running `micro --api_namespace=[some_namespace]` micro must set the variable `api.Namespace` to the value passed in the flag. It does it on `micro/main.go` on line 131:

```go
	app.Before = func(ctx *ccli.Context) error {
		...
		if len(ctx.String("api_namespace")) > 0 {
			api.Namespace = ctx.String("api_namespace")
		}
```

`app.Before` is a closure that it's returned when calling `setup(app)` in main func.

**Expected result**: The namespace is changed when running the API service.

**Current result**: 
```shell
micro --api_namespace=**com.myNamespace** api
2016/09/16 23:55:40 Registering RPC Handler at /rpc
2016/09/16 23:55:40 Registering API Handler at /
2016/09/16 23:55:40 Listening on [::]:8080
2016/09/16 23:55:40 Listening on [::]:38694
2016/09/16 23:55:40 Broker Listening on [::]:37253
2016/09/16 23:55:40 Registering node: **go.micro.api**-4ee2fb62-7c58-11e6-b16a-d850e60dbf43
```

I would be happy to help but I'm not sure why you need all the `app.Before` member and closure.

**Comment by asim** [comment]
I'm not sure what you're implying with "current result". Namespace is not logged. Where it says "Registering node go.micro.api" that is the actual name of the api itself. The API Namespace flag basically affects how the API routes requests. It uses the namespace + path as the service name to route a request to. The default namespace is "go.micro.api" which can be seen here https://github.com/micro/micro/blob/master/api/api.go#L23 but it might be confusing that its also the name of the api itself. 

Have you actually tried making requests once the namespace is changed?

**Comment by sayden** [comment]
I understand. Definitely it's a bit misleading.

The actual problem that I throght was involved with the namespace is that the RPC calls were working but not the HTTP ones.

In your example here https://github.com/micro/micro/tree/master/examples/greeter the "Test API via Curl" it always gives me:

```bash
curl http://localhost:8080/greeter/say/hello\?name\=John 
{"id":"go.micro.client","code":500,"detail":"none available","status":"Internal Server Error"}
```

I just copy pasted the commands in the example. It works when using the RPC endpoint.

I managed to run some code using the HTTP API but params always arrive emtpy

```go
Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil)
```

I have tried POST and GET.

Any ideas?

**Comment by asim** [comment]
I have a feeling you're running the example incorrectly.

You must run:
1. Service Discovery. Default being consul
2. The greeter server in examples/greeter/server
3. The greeter api in examples/greeter/api
4. The micro api

When you curl http://localhost:8080/greeter/say/hello it will send a request to the micro api which makes a request to the greeter api and that queries the greeter server.

I have just started all of these in a terminal and get the response:
```
$ curl http://localhost:8080/greeter/say/hello?name=John
{"message":"Hello John"}
```
If using the micro api as a proxy by specifying `--api_handler=proxy` then you must use the go-restful api example in examples/greeter/api/go-restful which is then queried as follows:

```
$ curl http://localhost:8080/greeter/john
{
  "msg": "Hello john"
 }
```

It's difficult to know what you're running and in what configuration from that last comment. Also If you changed the API namespace then the names for all example applications must also be changed from go.micro.{api,srv}.greeter to whatever your namespace is.

**Comment by sayden** [comment]
Ok, I managed. I deleted all contents and did `go get -u` again. The example worked fine.

I also didn't realize that I had to explicitly implement the `api` service apart from the service itself to allow HTTP queries. The fact that the RPC service worked without `api` using `micro api` made me thought that it also worked for HTTP requests.

Maybe it could be a good improvement. Do you think that `micro api` could parse the params and build the RPC call by itself without implementing an `api` service too?

**Comment by asim** [comment]
There are a number of reasons for the separation of API services. The primary reason being for architectural design purposes. Please read https://blog.micro.mu/2016/04/18/micro-architecture.html for more info.

**Comment by sayden** [comment]
Thank you for your time, Asim.

**Comment by anuragbhardwaj** [comment]
I was running the greeter/server and greeter/client example. The server starts fine, however, when I start the client as specified, it throws me an error saying {"id":"go.micro.client","code":500,"detail":"none available","status":"Internal Server Error"}

Can you please advice what I might be doing wrong here?

**Comment by asim** [comment]
Please do not comment in a closed issue. Please join the slack to discuss usage. The error implies the client cannot find the server. Please the readme to clearly understand the setup.
