### ISSUE TITLE
context package moved

### ISSUE THREAD

**Issue by qiukeren** [micro/micro#72]
`golang.org/x/context` has been removed to `context` in go 1.7 as an official package

Any plan to move it ?

**Comment by asim** [comment]
Only if there's a way to do it without breaking backwards compatibility.

**Comment by qiukeren** [comment]
I suggest to migrate to `context` after go 1.11 or go 1.12 released (about 2 years later)

😂😂😂

**Comment by asim** [comment]
Thanks for the helpful feedback.
