### ISSUE TITLE
Question: Micro Service Discovery over WAN using Consul

### ISSUE THREAD

**Issue by ramukima** [micro/micro#78]
Here is my deployment:

1. Consul server agent running on machine A
2. Consul agent running on Machine B, joined member with A
3. A service 'example' runs on machine A
4. micro list services and micro get service foo.example works from Machine A as well as from B
5. micro query foo.example GetApi - This works only from machine A. I get an error when trying the same on machine B.

ERROR:  {"id":"go.micro.client","code":408,"detail":"call timeout: context deadline exceeded","status":"Request Timeout"}

I am using go 1.7.4 on Ubuntu 16.04. Any advice to resolve this ?

**Comment by ramukima** [comment]
I see a warning like below on the consul server running on machine A. Not sure if that can be the cause.

2016/12/03 19:51:54 [WARN] Service name "foo.example" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.

**Comment by asim** [comment]
The warning is non-issue but if you want to avoid that then you need to specify a service name that matches consul's requirements. 

The timeout error mentioned above could be any number of reasons.  `micro list services` and `micro get service foo.example` only query consul while `micro query` makes a request to the service itself. It's likely that you have dead entries in consul and its attempting to request one of these. To avoid such an issue you should use the register ttl and interval options. Example here https://github.com/micro/micro/blob/master/examples/greeter/server/main.go#L24L25.

**Comment by asim** [comment]
The other likely issue could be that your other service is not accessible or registering a local address.

**Comment by ramukima** [comment]
Thanks for the reply, will try to define the TTL as well as refresh consul completely. I will close the issue once I have it working if that is OK.

**Comment by asim** [comment]
That's fine, please test and respond asap if looking to leave the issue open until resolved. Lingering issues unrelated to the code itself is not ideal.

**Comment by ramukima** [comment]
No luck, after trying the following -
1. Add TTL per your feedback
2. Cleared consul data and started with clean slate on both machines A and B
3. The server is accessible using public IP, may be the RPC port used for communication is being blocked somehow (checking, not sure)

**Comment by asim** [comment]
Please ensure your service is binding to the publicly accessible IP and attempt to manually connect to it. Are these two machines accessible on a private network? Are they two machines in completely different networks with public interfaces? What address is actually being registered in the service registry? Is that address accessible?

**Comment by ramukima** [comment]
Both nodes of the consul cluster reside on public facing network and the node2node communication is over WAN gossip. Regarding "What address is actually being registered in the service registry? Is that address accessible?" - Looks like this is the issue -

```
#micro stats foo.example
service  foo.example

version latest

node		address:port		started	uptime	memory	threads	gc
foo.example-19129b57-bc4a-11e6-b092-0cc47ab587da		x.x.x.x:34588					0
``` 

In the result above, I see that x.x.x.x is actually used from a private network and not from the public network.

I agree that it is non-issue for the micro toolkit.

**Comment by ramukima** [comment]
I am reopening this as a question:

I have a Consul Cluster (Server) in a DC say SFO and another Consul Cluster (Server) in another DC say BOS. Both these are joined over wan (consul join -wan <ip>). I can see them connected fine.

I then start a micro service in SFO with registry_address as the the address of SFO consul server.
Using 'http://bos-server:8500/v1/catalog/services?dc=sfo', I can see that the micro service was registered to consul in SFO dc from BOS dc.

When I run 'micro list services' in SFO, I see my micro service listed.
When I run 'micro list services' in BOS, I do not see my micro service listed.

Is there a way I can list/call services running in SFO dc from the server in BOS dc ? Apologies if this has been answered before.

**Comment by asim** [comment]
I'm sorry but this is a consul specific issue. Micro only abstract consul away as a registry, it does not control the underlying functionality of consul. `micro list services` just uses consul.Catalog().Services(nil). You may need to talk to hashicorp about how WAN clustering works.

**Comment by pawmart** [comment]
FYI i have similar problems on NATS, so that's not only consul specific...

**Comment by ZiyunYang** [comment]
> FYI i have similar problems on NATS, so that's not only consul specific...
Hi, I meet the same problem in NATS, have you found any solutions?

**Comment by ZiyunYang** [comment]
@pawmart  Hi, I meet same problems on NATs, have you found any solutions?
