### ISSUE TITLE
micro auth service 

### ISSUE THREAD

**Issue by aredcup** [micro/micro#784]
micro auth serivce  function Generate code
// set a refresh token
if err := a.setRefreshToken(acc.ID, uuid.New().String()); err != nil {
   return errors.InternalServerError("go.micro.auth", "Unable to set a refresh token: %v", err)
}
when i call Token function
// If the refresh token is set, check this
if len(req.RefreshToken) > 0 {
   accID, err := a.accountIDForRefreshToken(req.RefreshToken)
   if err == store.ErrNotFound {
      return errors.BadRequest("go.micro.auth", "Invalid token")
   } else if err != nil {
      return errors.InternalServerError("go.micro.auth", "Unable to lookup token: %v", err)
   }
   accountID = accID
}
it always return store,ErrNotFount.because i don't known RefreshToken(it is uuid.New()String() what is not return) .version is v2.4.1 (edited)

**Comment by asim** [comment]
We are not in a place to discuss the usage of the Auth service at this time.

**Comment by mefloresz** [comment]
I stay working on windows (using wsl) and the micro server all the past year without problems, but recently with the new Micro version and the new Go version the server doesn't work ...
