### ISSUE TITLE
consulRegistry design imperfection？Use consul service mechanism...

### ISSUE THREAD

**Issue by ZhuJingfa** [micro/micro#79]
These days I tried out the micro framework, find it is amazing microservice framework. Yesterday I found some imperfection about it.

1. Firstly, It uses consul's service for registry to register and deregister micro's services, but I found that the consul utility use the first address provided by  --registry_address=host1:8500,host2:8500, and this can aviod another bug: the consul service is angent local stored. Maybe use kv store or etcd's kv sotre will be an better option? The consul service register in one agent can not be replicated to other nodes, when agent failed, this will be an single fail point. When agent failed, all serivces need to restart to use another registry. Another imperfection is the registry will be bottle neck, when massive requests routing to the right backend services.
About this, /v1/agent/services http api in agent A can not read services registed in agent B, consul dns interface can fetch services from all  agents, but the service name can not contain period ".", ref: [https://github.com/hashicorp/consul/issues/215](https://github.com/hashicorp/consul/issues/215)
```go
// check if there are any addrs
if len(options.Addrs) > 0 {
	addr, port, err := net.SplitHostPort(options.Addrs[0])
	if ae, ok := err.(*net.AddrError); ok && ae.Err == "missing port in address" {
		port = "8500"
		addr = options.Addrs[0]
		config.Address = fmt.Sprintf("%s:%s", addr, port)
	} else if err == nil {
		config.Address = fmt.Sprintf("%s:%s", addr, port)
	}
}	
```
2. As I test, when use start miro service with TTL option, the app need to handle reregistering intervally. Can this be handled by framework, this will decrease wrong usage about micro?
3. I'm a newer to micro, there may be some incorrect facts, I'm sorry if there is any.

**Comment by asim** [comment]
Thanks for using micro. To answer your questions.

1. Consul itself can be clustered which provides fault tolerance. Agents can be run locally as clients which connect to the main cluster and provide local services a fixed address to use. 

Micro itself is pluggable. You can used etcd, zookeeper or anything else which you feel like implementing. Existing plugins can be found here https://github.com/micro/go-plugins

Consul DNS is not something we support or care about but everything is encoded to fit the requirements. You define your own service name and must make that compatible to their requirements if you want to use Consul DNS, but again, we do not use it.

2. If you look at the godoc https://godoc.org/github.com/micro/go-micro#RegisterInterval. You'll see a RegisterInterval option which handles registering on an interval.

3. Please reads the docs https://github.com/micro/micro/tree/master/doc and the blog https://blog.micro.mu to learn more about Micro.
