### ISSUE TITLE
how to add wrapper in micro proxy

### ISSUE THREAD

**Issue by Ioridy** [micro/micro#799]
I have spent hours trying to add wrapper for micro proxy,  but not working.
I have some service and i want to call the service with grpc from client, so i create a  proxy (use micro proxy) 

I think i can add wrapper with options, but it didn't work when i call service with grpc use proxy.
Is it a rigth way? or other way can fix my question?
>  I can add wrapper for my  service and well done, but i have many service and don't add one by one.

Thanks in advance.

```golang
import (
	"context"
	"github.com/micro/go-micro/v2"
	"github.com/micro/go-micro/v2/server"
	"github.com/micro/micro/v2/cmd"
	"log"
)

// logWrapper is a handler wrapper
func logWrapper(fn server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, rsp interface{}) error {
		log.Printf("[wrapper] server request: %v", req.Endpoint())
		err := fn(ctx, req, rsp)
		return err
	}
}

func main() {
	cmd.Init(
		micro.WrapHandler(logWrapper),
		)
}

```

**Comment by asim** [comment]
Unsupported at this time. We'll come back on pluggable wrappers soon.
