### ISSUE TITLE
Missing micro releases on docker hub

### ISSUE THREAD

**Issue by OGKevin** [micro/micro#805]
The latest GitHub release is 2.5.0: https://github.com/micro/micro/releases

The last tag on docker hub is 2.0.0: https://hub.docker.com/r/micro/micro/tags

It seems that the latest tag is still being updated however, only the tagged tags are missing. This makes it of course hard to pin on a version as you either have to manually build and push the tag to your own registry or you must figure out the digest of the version you want and pull it that way.

**Comment by domwong** [comment]
@OGKevin thanks for the report. We've fixed the underlying issue so it should work for all future releases and have pushed v2.9.2 to reflect latest release.
