### ISSUE TITLE
Does protoc-gen-micro has generator option like 'go_opt'?

### ISSUE THREAD

**Issue by countstarlight** [micro/micro#826]
Same as https://github.com/golang/protobuf/issues/992 , if the project not in `$GOPATH`, and the `.proto`  file like:

```proto
syntax = "proto3";

package user;

option go_package = "github.com/foo/bar/api/user/proto;user";

import "srv/user/proto/user.proto";

service User {
	rpc Info(Request) returns (Response) {};
}

message Request {
	string uuid = 1;
}

message Response {
	repeated user.User userInfo = 1;
}
```
Run:
```bash
protoc --proto_path=. --micro_out=. --go_out=. --go_opt=module=github.com/foo/bar api/user/proto/user.proto
```
the output files will be
`foo/bar/api/user/proto/user.pb.go` 
and
`foo/bar/github.com/foo/bar/api/user/proto/user.pb.micro.go` 
the latter is what we don’t want.

Related: https://github.com/protocolbuffers/protobuf-go/commit/ffbc5fdf5a2a1220b58e51cecf8b7b8bf94956cf

**Comment by asim** [comment]
We're just using a fork of protoc-gen-go so whatever it provides

**Comment by Vabs3** [comment]
For those who didn't get the solution.
 --micro_opt=paths=source_relative
This flag is available.
