### ISSUE TITLE
package github.com/golang/protobuf/proto is deprecated

### ISSUE THREAD

**Issue by butonic** [micro/micro#847]
Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)

also see https://github.com/dominikh/go-tools/issues/732 and the [changes we intend to mak to protoc_gen_microweb](https://github.com/owncloud/protoc-gen-microweb/pull/3/files)

Just changing the string in https://github.com/micro/micro/blob/24e9b206767cf2a14e901a0da6ac1e759adb3fdc/cmd/protoc-gen-micro/generator/generator.go#L1249 won't be enough.

**Comment by asim** [comment]
Feel free to provide a PR for a fix
