### ISSUE TITLE
micro web client responded with connection closed.

### ISSUE THREAD

**Issue by luxuze** [micro/micro#858]
this is the web handler
<img width="977" alt="image" src="https://user-images.githubusercontent.com/35137889/81769181-882e3880-950f-11ea-8eb5-aba6621f05cc.png">

this is the web client call
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/35137889/81769219-a1cf8000-950f-11ea-97fa-b7347729ddaf.png">

**Comment by asim** [comment]
This is not possible. Please curl your service via the micro api
