### ISSUE TITLE
[question] up-to-date k8s docker image builds?

### ISSUE THREAD

**Issue by obataku** [micro/micro#859]
I noticed the most recent build with kubernetes support (`microhq/micro:kubernetes`) is 8 months old and associated with the old docker repository (https://hub.docker.com/r/microhq/micro); is it safe to assume those builds were discontinued indefinitely?

**Comment by asim** [comment]
Docker builds moved to micro/micro

**Comment by obataku** [comment]
yes, I saw @asim, but notice that there are no builds tagged `kubernetes` in the new repository: https://hub.docker.com/r/micro/micro/tags?name=kubernetes
... whereas there used to be in the old repository:
https://hub.docker.com/r/microhq/micro/tags?name=kubernetes

**Comment by obataku** [comment]
any updates @asim?

**Comment by obataku** [comment]
@asim I noticed `k8sbuild` is missing the `kubernetes` registry--are there any builds still containing it?
