### ISSUE TITLE
variable for service name

### ISSUE THREAD

**Issue by GJRTimmer** [micro/micro#86]
Which variable allows me to change the name of a micro api proxy service.
Screen shot is of dev environment, but a production environment will have multiple.
I want to change this name to 'PRODUCTNAME.gateway.api' for example; which variable allows me to do that. I've tried multiple and no success so far.

See screenshot
![overview-name](https://cloud.githubusercontent.com/assets/6072255/22582395/fe94bb84-e9e6-11e6-9054-d3460c5906bf.png)

**Comment by asim** [comment]
There is currently no way to change the name of the api.

"Screen shot is of dev environment, but a production environment will have multiple"

Why does this matter? You do know multiple instances of a service can be registered in Consul.

**Comment by GJRTimmer** [comment]
@asim The reason I would like to change it, is because of managing the consul environment, one consul cluster can manage multiple micro-api gateways which from the point of management would be quite troublesome if every micro api shows up in consul as go.micro.api.

I really hope you can follow me.

**Comment by GJRTimmer** [comment]
Let me give you a screen shot.

As seen below, 5 instance(s) for go.micro.api, but their config is different, so the actual result should be

- com.gateway.api 2(instances)
- com.backend.api 3(instances)

I really hope you would help me in creating a fix for this, I've went to the code and so far this should maybe be fixed within go-micro with a  ENV var ?

![different-api](https://cloud.githubusercontent.com/assets/6072255/22583936/ed8d14fe-e9ef-11e6-8a5b-7803e18bebb2.png)

**Comment by GJRTimmer** [comment]
@asim Question, is this global variable ```server_name``` supposed to handle this ?

**Comment by asim** [comment]
Issue resolved in relation to the PR.
