### ISSUE TITLE
 One sidecar instance(process) to handle several services' health checking, and at the same time serve the http proxy

### ISSUE THREAD

**Issue by liuluheng** [micro/micro#88]
I want use one sidecar instance(process) to handle several services' health checking, and at the same time serve the http proxy(for file upload). 
It seems impossible in current implemetation. Does the purpuse of sidecar is per service on per sidecar instance?

**Comment by asim** [comment]
The sidecar can be used in a one to many fashion but not with health checking. The health checking is built in as a convenience function, it's not how most primarily use the sidecar. The go-micro services periodically re-register with a TTL. You should do the same with your apps through the sidecar.

**Comment by liuluheng** [comment]
got it! thanks!
