### ISSUE TITLE
protoc-gen-micro: program not found or is not executable

### ISSUE THREAD

**Issue by dwschulze** [micro/micro#890]
protoc fails with the error message in the title.  Here's what I tried:

export GO111MODULE=on

go get github.com/micro/micro/v2/cmd/protoc-gen-micro@master
(This  was useless.  Didn't even install protoc compiler.)

sudo apt  install protobuf-compiler
(This did install the protoc compiler.)(

Also tried:
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}

All I can get is:

$ protoc --proto_path=$GOPATH/src:. --micro_out=. --go_out=. proto/greeter.proto
protoc-gen-micro: program not found or is not executable
--micro_out: protoc-gen-micro: Plugin failed with status code 1.

**Comment by asim** [comment]
This installs protoc-gen-micro which is our plugin. It installs it into your GOPATH/bin which you need to add to PATH.

```go get github.com/micro/micro/v2/cmd/protoc-gen-micro@master```

**Comment by dwschulze** [comment]
asim - That worked.  Thank you.

Their instructions are wrong.  Not even close.  Here are the necessary steps:

//  This installs protoc
sudo apt  install protobuf-compiler
export GO111MODULE=on
//  This installs $GOPATH/bin/protoc-gen-micro
go get github.com/micro/micro/v2/cmd/protoc-gen-micro@master
//  This installs $GOPATH/bin/protoc-gen-go
go get -u github.com/golang/protobuf/protoc-gen-go

Then:
export PATH=$GOPATH/bin:$PATH

**Comment by asim** [comment]
Will update instructions thanks
