### ISSUE TITLE
How to specify tls configuration for registry of api gateway?

### ISSUE THREAD

**Issue by jupiterwangq** [micro/micro#893]
I start api gateway with following command:
`MICRO_REGISTRY=etcd MICRO_REGISTRY_ADDRESS=https://x.x.x.x:2379 micro api --handler rpc` 
how to set tls configuration for the etcd registry? It seems that no flags for me to set it.

**Comment by asim** [comment]
If you are looking to add TLS to etcd we do not support this via flags or env vars at this time
