### ISSUE TITLE
call PingPong method fail 500 EOF

### ISSUE THREAD

**Issue by wubin1989** [micro/micro#898]
This is my command:
micro --registry=etcd call xxx.cloud.service.demo Demo.PingPong '{"stroke": 9}'

This is response:
error calling xxx.cloud.service.demo.PingPong: {"id":"go.micro.client","code":500,"detail":"EOF","status":"Internal Server Error"}

My service startup command:
./demo-service --registry=etcd  

Can anyone help me? I cannot figure out where is wrong.

**Comment by asim** [comment]
Please see examples for correct usage
