### ISSUE TITLE
Change Getting Started Documentation

### ISSUE THREAD

**Issue by hvram1** [micro/micro#90]
The getting started documentation says the following 

> docker run consul

This results in a connection denied error when you run the greeter example . The correct command is

> docker run -d -p 8500:8500 --name=consul consul agent -server -bootstrap -client=0.0.0.0

The -d flag ensures docker runs as a daemon
The -bootstrap flag ensures that Consul does not barf when run standalone and does not say no quorum
The -p ensures that the port is mapped to the 8500 port of the localhost .

The above commands work with Docker 1.13 on windows

**Comment by asim** [comment]
Updated. Thanks
