### ISSUE TITLE
Stream DATA End Stream is false when using micro proxy

### ISSUE THREAD

**Issue by onanying** [micro/micro#900]
![1590550013583](https://user-images.githubusercontent.com/16074765/82974700-2d1b3c00-a00d-11ea-8e13-2bb566ddfdb9.jpg)

We are trying to write grpc using php using micro runtime tool, but there is a problem when using micro proxy

```
MICRO_PROXY_ADDRESS=127.0.0.1:8081 micro --registry=etcd call go.micro.srv.greeter Say.Hello '{"name":"abc"}'
```

After using micro proxy, End Stream of Stream DATA is false, which makes it impossible to judge the end of the packet

```
micro --registry=etcd call go.micro.srv.greeter Say.Hello '{"name":"abc"}'
```

Normal call, End Stream of Stream DATA is true

**Comment by twose** [comment]
raw:
![image](https://user-images.githubusercontent.com/25978241/82975271-8768cc80-a00e-11ea-9c54-37e78aed5766.png)

---
proxy:
![image](https://user-images.githubusercontent.com/25978241/82975311-a5363180-a00e-11ea-8ec4-6d375bd59573.png)
