### ISSUE TITLE
searching for the go binary

### ISSUE THREAD

**Issue by ereli** [micro/micro#908]
I'm trying to follow the example
``` micro run github.com/micro/examples/greeter/srv```
and I'm getting an error about the location of the `go` binary.
```
fork/exec /Users/myusername/homebrew/bin/go: no such file or directory
```
I have a mac and the `go` binary is a symbolic link to the Cellar location `brew` used for the installation.
Where in the code does micro resolve the location of the go binary? can we set it manually?

**Comment by asim** [comment]
Hey Ereli, micro is using whatever is in your PATH so it's just offloading to the system to resolve the path to go. If you cannot access `go` like that then it will have issues. You'll need to add it to the PATH.

**Comment by asim** [comment]
No response from Ereli, closing. Reopen if still an issue.

**Comment by ereli** [comment]
Sorry of the delayed response.
I also can't reproduce on on Linux, just on Mac.
On Ubunutu, I tried running 
```export GO111MODULE=on   
apt-get update && apt-get install golang git fish
go install github.com/micro/micro/v2
cd /usr/bin
mv go mygo
cd /usr/local/bin
ln -s ../../bin/mygo go
~/go/bin/micro run github.com/micro/examples/greeter/srv
``` and there's no issue. same on `fish` as you shell, that has no difference on linux.

On macOS still having this issue. I looked at the code, searching for `exec/fork` and generally for exec statements trying to figure out where is this being called exactly. could you point me in the right direction?

**Comment by ereli** [comment]
if it was using `"os/exec"` or `syscall.Exec` the error would have been:
```
exec: "go": executable file not found in $PATH
```

**Comment by dr-zeta** [comment]
same here with mac os and micro v3.0.0-beta.

`fork/exec /usr/local/bin/go: no such file or directory
`

but it exists:
`lrwxr-xr-x  1 zeta  admin  26  8 Nov 00:36 /usr/local/bin/go -> ../Cellar/go/1.15.3/bin/go
`
