### ISSUE TITLE
[Proposal] Contribute a to a benchmark

### ISSUE THREAD

**Issue by waghanza** [micro/micro#910]
Hi,

I'm leading a benchmarking project => https://github.com/the-benchmarker/web-frameworks

The purpose of this project is to compare performances (other indicators will come), based on a fairest, as we can, comparison for `go` **frameworks** (comparing on the same version, **production-grade** environments, same compilation options ...).

Do you mind that I (or any member) add `micro`  ? :heart:

Regards,

**Comment by asim** [comment]
Feel free to add it.
