### ISSUE TITLE
micro run . does not work

### ISSUE THREAD

**Issue by t5w0rd** [micro/micro#914]
```./greeter-services  # it works```
 and 
```micro run .  # it doesn't work```
then
```micro status```
```
SERVICE
com.xxx.service.greeter
default/com.xxx.service.greeter   # what's "default/" meaning?
```

btw, after ```micro run helloworld```, ```micro logs helloworld``` will only get following result:
```
aaa
aaa
aaa
aaa
aaa
```
and ```micro call go.micro.service.helloworld Helloworld.Call '{"name":"Jane"}'```will fail

IMHO, as micro becomes more complex, quality is declining
I think the focus of micro should be on the core functions of microservices

**Comment by t5w0rd** [comment]
the services processes may be leak sometimes by starting by ```micro run```

**Comment by t5w0rd** [comment]
> @t5w0rd what version of micro are you using? We've been fixing a bunch of bugs around the CLI and will be cutting a new release in the next few days

```shell
$ micro --version
micro version latest
```
i think the version of micro was v2.8.0

**Comment by asim** [comment]
Please move to latest version and retry.
