### ISSUE TITLE
Account not issued by go.micro.srv

### ISSUE THREAD

**Issue by leopay** [micro/micro#927]
when I start micro api-gateway like below

> micro api --namespace=foo.bar

and call the api-gateway

> curl localhost:8080/greeter/say/hello 

it return

> Account not issued by foo.bar

if I remove --namespace parameter, every thing is ok

it seems when add the --namespace, the auth is activated

**Comment by bluedragonflyliu** [comment]
have the same problem

**Comment by bluedragonflyliu** [comment]
crazy! crazy!  when this fixed or how to avoid

**Comment by bluedragonflyliu** [comment]
good news, Release v2.6.0 not check auth token,download  and replace

**Comment by doubleycn** [comment]
add --auth_namespace

**Comment by asim** [comment]
Appears fixed

**Comment by evan766** [comment]
go-micro/v2.9.0 , same problem

**Comment by domgolonka** [comment]
same problem for me at v2.9.2
