### ISSUE TITLE
file=registry/registry.go:238 level=error service=api error watching endpoints

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/micro#929]
micro --version
micro version latest

micro api --handler=api --namespace=com.micro.api
2020-06-09 05:28:07  file=api/api.go:233 level=info service=api Registering API Request Handler at /
2020-06-09 05:28:07  file=http/http.go:90 level=info service=api HTTP API Listening on [::]:8080
2020-06-09 05:28:07  file=registry/registry.go:238 level=error service=api error watching endpoints: {"id":"go.micro.client","code":500,"detail":"Error creating stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused\"","status":"Internal Server Error"}
2020-06-09 05:28:07  file=api/api.go:313 level=fatal service=api {"id":"go.micro.client","code":500,"detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused\"","status":"Internal Server Error"}

**Comment by bluedragonflyliu** [comment]
It is seem have stored somewhere how can I remove that?

**Comment by elimisteve** [comment]
Similarly, when I run

    $ micro server

on Debian 9.12, x86_64, kernel version `4.19.107-1.pvops.qubes.x86_64`, micro version `v2.9.0-rc5-0fb1fe8-1591884856`, I get

> {"id":"go.micro.client","code":500,"detail":"service go.micro.auth: not found","status":"Internal Server Error"}

**Comment by domwong** [comment]
> Similarly, when I run
> 
> ```
> $ micro server
> ```
> 
> on Debian 9.12, x86_64, kernel version `4.19.107-1.pvops.qubes.x86_64`, micro version `v2.9.0-rc5-0fb1fe8-1591884856`, I get
> 
> > {"id":"go.micro.client","code":500,"detail":"service go.micro.auth: not found","status":"Internal Server Error"}

@elimisteve can you please raise a separate issue with a bit more information? I'm not sure how this is related to this issue as your error messages are different. In your new issue can you please also provide a bit more logs and context? For example, does that error stop things from running/working? Or is it just a log line that is causing you concern but things work as expected apart from that?

**Comment by domwong** [comment]
@bluedragonflyliu the detailed error `"Error creating stream: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused""` seems to suggest it can't connect to `:8081` which is the port for the `micro proxy`. Can you double check that it's running?

For future reference micro stores everything under `$TMPDIR/micro` so if you need to reset everything you can delete that directory

**Comment by ben-toogood** [comment]
@domwong the error `{"id":"go.micro.client","code":500,"detail":"service go.micro.auth: not found","status":"Internal Server Error"}` is fatal and resulting in the proxy crashing.

I'm investigating this bug, however I suggest we open a ticket to add restarts to the local runtime.

**Comment by bluedragonflyliu** [comment]
when run micro env while found the server :8081, but when and how I add that I have forget,I just change that api gateway all well,no have that problem. thinks.

**Comment by domwong** [comment]
@bluedragonflyliu are you using a VPN? We've recently fixed a bug which meant that if you were on a VPN it might not work.

**Comment by asim** [comment]
No response. Closing
