### ISSUE TITLE
Add to docs: compare Micro to Kubernetes, Nomad, and Flynn

### ISSUE THREAD

**Issue by elimisteve** [micro/micro#940]
This would help clarify what Micro does and doesn't do, and how it fits into the current landscape. Thanks!

**Comment by asim** [comment]
I'll start by saying, Micro is not a process manager or a container orchestrator. We offload these concerns to the underlying runtime like linux or kubernetes. Micro provides a service layer abstraction on top for core distributed systems concerns and focuses on the developers needs to write microservices.
