### ISSUE TITLE
[CMD]: micro new "name" results in connection error

### ISSUE THREAD

**Issue by xzjkya** [micro/micro#943]
**Environment:**
```
Linux host? 5.4.43-1-lts #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 Linux
```

**go.mod**
```
module github.com/xzjkya/gossip

go 1.14

require github.com/micro/micro/v2 // indirect
```

**go env**
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vitoriano/.cache/go-build"
GOENV="/home/vitoriano/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vitoriano/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vitoriano/Go/src/github.com/xzjkya/gossip/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build570178386=/tmp/go-build -gno-record-gcc-switches"
```

**Problem:**
Starting a fresh service with `micro new` in v2.9 gives me this:

```
{"id":"go.micro.client","code":500,"detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused\"","status":"Internal Server Error"}
```

If I do `micro server` beforehand it works well. At least the service directory is being created and I get what seems to be an error on my part. Although I'm sure it's installed:

```
Creating service go.micro.service.account in account

Unable to find go-micro version. Please try `go get github.com/micro/go-micro/v2`
```

**Expected:**
Not really a bug, but having micro server up before issuing a simple scaffolding command seems a bit counter intuitive. Not sure if this behavior was in previous releases though. I could see this as a design choice if before creating a service the system checks if there is an account service already created (or registered), but that's not really what happens. I created 2 services named `account` in different directories and they both ran without problems. At Linux level I have 2 processes both named `account-service`, but when I do a `micro list services` only one seem to be registered (my guess is that due to naming scheme they superpose each other, last service being the winner). If there's no previous check for this why do I have to have micro server up for a simple scaffolding? If this is true why not taking the users filesystem as a namespace for the service? Might solve a lot of issues related to how users may organize a micro project. e.g I'm placing all my services under `github.com/xzjkya/gossip/services` whereas another project may hold a different scheme. Also the doc doesn't mention this behavior. If you follow it top-bottom you will never notice this by the way.

**Comment by asim** [comment]
I'm only going to answer a couple of your questions as you've asked quite a few. I'll let someone else chime in on those. The `micro new` throwing an error is indeed a bug and should be fixed in the next release. We don't expect the server to be running to create a new service. 

In regards to list services. If two services have the same name they will indeed appear as one in a list considering its a unique name, list does not show duplicates. If you do `micro get service account` you will see the two different versions running.

**Comment by xzjkya** [comment]
Thanks @asim . You're right, but not entirely. Issuing `micro get service account` was not enough to find the service, but `go.micro.service.account` was enough to solve the problem. So what actually `micro list services` do is give me a registry namespace where all my "related" services are registered I assume? Can I also assume somewhere in between the bunch of services and the registry there will be a load balancer or another kind of proxy too? Do you guys have any sort of old/new docs for micro command? Besides skimming through the code for help the `help` isn't much of a help when it comes to behavior no pun intended. I'm closely following the project reason I'm interested about the innards of the architecture.

**Comment by asim** [comment]
We're slowly rebuilding docs so you can look at this old blog post which describes the discovery, load balancing, etc https://m3o.com/blog/2016/05/15/resiliency.html

Your services which you name when creating them in code are registered with that name in the registry. This is much like when you'd explicitly pick a DNS name for something.

**Comment by asim** [comment]
A new release has gone out which should fix the issue. Please report back.

**Comment by xzjkya** [comment]
I took the liberty to run a thorough test with all commands and eyed the PR done. Everything seems ok. One weird behavior is that running `micro` or `micro anything` without server being up I end up stumbling in the same connection problem. Once again, not really a big deal,  but quite confusing. Specially when I run `micro ronaldmcdonald` and it actually gives me a connection error. This behavior doesn't happen when server is up it actually gives me the right response `Unrecognized micro command: ronaldmcdonald. Please refer to "micro help"`

**Comment by domwong** [comment]
@xzjkya thanks for the update. I've made a note to investigate why it's trying to connect to something when it doesn't recognise the command

**Comment by xzjkya** [comment]
@domwong , we keep this issue open until this behavior is solved?

**Comment by domwong** [comment]
@xzjkya I've created a new ticket with appropriate title so we can track and have tagged you in it #952. Will close this one.
