### ISSUE TITLE
New example greeter: micro api --handler=api 

### ISSUE THREAD

**Issue by DuckulaGL** [micro/micro#944]
os: OSX 10.15
first run: 
go run api/api.go
it is OK

second run:
greeter git:(master) ✗ go run srv/main.go
it is OK

third run:
➜  ~ micro api --handler=api
report error:
{"id":"go.micro.client","code":500,"detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8081: connect: connection refused\"","status":"Internal Server Error"}

**Comment by DuckulaGL** [comment]
So if run "curl http://localhost:8080/greeter/say/hello?name=John", it reports error too.

**Comment by DuckulaGL** [comment]
If just run "micro api", it runs OK

**Comment by DuckulaGL** [comment]
run "consul agent -dev", it still reports error.

**Comment by DuckulaGL** [comment]
English version micro Doc has issues, so who can supply the right description about it. The Chinese doc just has some right description but incomplete.

**Comment by doubleycn** [comment]
github.com/micro/micro/v2@v2.9.1/client/api/api.go
modify code at line 202:

```
201     ropts := []resolver.Option{
202         //resolver.WithNamespace(nsResolver.ResolveWithType),
203         resolver.WithNamespace(nsResolver.Resolve),
204         resolver.WithHandler(Handler),
205     }
```
rebuild micro:
cd github.com/micro/micro/v2@v2.9.1/
go build
go install

**Comment by godliam** [comment]
> github.com/micro/micro/v2@v2.9.1/client/api/api.go
> modify code at line 202:
> 
> ```
> 201     ropts := []resolver.Option{
> 202         //resolver.WithNamespace(nsResolver.ResolveWithType),
> 203         resolver.WithNamespace(nsResolver.Resolve),
> 204         resolver.WithHandler(Handler),
> 205     }
> ```
> 
> rebuild micro:
> cd github.com/micro/micro/v2@v2.9.1/
> go build
> go install
> 
> or not modiy code:
> run api
> 
> ```
> micro --api_namespace=mu.micro.book.web --auth_namespace=mu.micro.book.web  api --handler=web
> ```
> 
> create web service Name add *.api.xxx
> 
> ```
> 11     // create new web service
>  12     service := web.NewService(
>  13         web.Name("mu.micro.book.web.api.user"),
>  14         web.Version("latest"),
>  15     )
> ```

I got same problem, i follow you (modify code) and it works.
Thks!
