### ISSUE TITLE
'micro new' - error in generated files if template has _, -, or capitals

### ISSUE THREAD

**Issue by dcam0050** [micro/micro#961]
Observed behaviour:
```
micro new --namespace a.b --type=service x_y
cd x_y
make proto 
make build
``` 
results in the errors:
```
handler/x_y.go:21:89: undefined: a_b_service_x_y.x_y_StreamStream
handler/x_y.go:37:58: undefined: a_b_service_x_y.x_y_PingPongStream
```
If instead of x_y I use x-y it compiles correctly

Expected behaviour: 
```
micro new --namespace a.b --type=service x_y
cd x_y
make proto 
make build
```
should result in a correct build or throw an error / message asking user to change template name.

Additional information:
Micro Version - `micro version v2.9.1-77504c2-1592234657`

**Comment by dcam0050** [comment]
Using `micro new --namespace a.b --type=service x-y` results in correct build because y is discarded in generating the service name resulting in service called x

**Comment by domwong** [comment]
Thanks for the report. We'll look in to this

**Comment by domwong** [comment]
@dcam0050 we've addressed this in latest `master` so should appear in the next release. Thanks for the report!
