### ISSUE TITLE
Sending a query in micro web only displays the response if the response code is 200

### ISSUE THREAD

**Issue by andrew-jones** [micro/micro#97]
Looks like this is the intended behavior, but it would be good to see the response regardless of the status.

https://github.com/micro/micro/blob/master/web/templates.go#L187

**Comment by asim** [comment]
This should give you what you want https://github.com/micro/micro/commit/a3997a3e2836b4abb7d521a6c582635749dbb44e

**Comment by andrew-jones** [comment]
Thank you!
