### ISSUE TITLE
Graceful WEB service stop

### ISSUE THREAD

**Issue by vyacheslavk** [micro/micro#99]
is it possible to gracefully stop web service? Or need to implement own os.Signal listener?

**Comment by asim** [comment]
What web service? You mean `micro web`? Because it's listening for a kill signal and exits gracefully.

**Comment by vyacheslavk** [comment]
I use `github.com/micro/go-web` 
```go
service := web.NewService(
		web.Name("go.micro.api.service"))
```
and its no accept BeforeStop options

**Comment by asim** [comment]
Please create the issue in the relevant project.

**Comment by vyacheslavk** [comment]
created issue here https://github.com/micro/go-web/issues/7
